// Code generated by scripts/dbcdata. DO NOT EDIT.

package dbcmem

// ExtraAttackSpells maps spell IDs to spell names for all spells
// with the EffectAddExtraAttacks effect.
var ExtraAttackSpells = map[int32]string{
	677: "Holy Flurry II",
	1869: "Holy Flurry III",
	1870: "Holy Flurry IV",
	3391: "Thrash",
	8233: "Windfury Weapon",
	8236: "Windfury Weapon",
	8516: "Windfury Totem",
	10484: "Windfury Weapon",
	10608: "Windfury Totem",
	10610: "Windfury Totem",
	15494: "Fury of Forgewright",
	15601: "Hand of Justice",
	15642: "Ironfoe",
	16361: "Windfury Weapon",
	16459: "Sword Specialization",
	16843: "Crimson Fury",
	18797: "Flurry Axe",
	18941: "Double Attack",
	19105: "MHTest01 Effect",
	19109: "MHTest02 Effect",
	20178: "Reckoning",
	21919: "Thrash",
	25175: "Triple Attack",
	27035: "Sword Specialization (OLD)",
	49369: "Rage of the Mountain",
	51368: "Windfury Totem",
	52634: "Hack and Slash",
	52732: "Timeless Strike",
}
