# See the dedicated "version" documentation section.
version: "2"
linters:
  exclusions:
    paths:
      - "cmd/wasm/main\\.go$"
      - "database/gen/dump/.*"
      - "database/dbtestutil/.*"
      - "combatlog/parser/regexs/compiled/"
      - "database/spice/.*"