# fly.toml app configuration file generated for chronicleclassic on 2026-01-15T16:53:56-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'chronicleclassic'
primary_region = 'dfw'
kill_signal = 'SIGINT'
kill_timeout = '2m0s'

[experimental]
  cmd = ['server']

[build]
  image = 'emyrk/chronicled:latest'

[deploy]
  strategy = 'immediate'

[env]
  CHRONICLE_ACCESS_URL = 'https://chronicleclassic.com'
  CHRONICLE_ENABLE_PPROF = 'true'
  CHRONICLE_ENABLE_PROMETHEUS = 'true'
  CHRONICLE_HTTP_ADDRESS = '0.0.0.0:8080'
  CHRONICLE_JSON_LOGS = 'true'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 6060
  processes = ['app']

  [[services.ports]]
    port = 6060
    handlers = ['http']

[[services]]
  protocol = 'tcp'
  internal_port = 9090
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[[metrics]]
  port = 9091
  path = '/metrics'
