GIT_TAG := $(shell git describe --tags --abbrev=0)
GIT_COMMIT := $(shell git describe --always)
BUILD_TIME := $(shell TZ='America/Chicago' date +"%m-%d-%y_%H:%M")
LD_BUILD_FLAGS=-ldflags=-X=github.com/Emyrk/chronicle/internal/version.GitTag=$(GIT_TAG)\ -X=github.com/Emyrk/chronicle/internal/version.GitCommit=$(GIT_COMMIT)\ -X=github.com/Emyrk/chronicle/internal/version.BuildTime=$(BUILD_TIME)

.PHONY: install
install:
	go install ./cmd/chronicle
	go install ./cmd/chronicled

database/querier.go: database/sqlc.yaml database/dump.sql $(wildcard database/queries/*.sql)
	./database/generate.sh

.PHONY: test
test:
	gotestsum --format testname -- -race $$(go list ./...)

.PHONY: lint
lint:
	golangci-lint run

frontend/chronicle/dist: $(wildcard frontend/**)
	(cd frontend/chronicle; pnpm install; pnpm build)

.PHONY: develop
develop: frontend/chronicle/dist create-db
	go run --tags static $(LD_BUILD_FLAGS) ./cmd/chronicled server --dev-auth --jwt-secret-pem="dev"

develop-backend: create-db
	go run --tags static $(LD_BUILD_FLAGS) ./cmd/chronicled server --dev-auth --jwt-secret-pem="dev"

.PHONY: build
build: build-backend frontend/chronicle/dist

.PHONY: build-backend
build-backend:
	go build --tags static  $(LD_BUILD_FLAGS) -o bin/chronicled ./cmd/chronicled

# Docker Compose targets for local development services
COMPOSE_FILE := scripts/development/docker-compose.yml

.PHONY: services-up
services-up:
	docker compose -f $(COMPOSE_FILE) up -d

.PHONY: services-down
services-down:
	docker compose -f $(COMPOSE_FILE) down

.PHONY: services-logs
services-logs:
	docker compose -f $(COMPOSE_FILE) logs -f

.PHONY: services-clean
services-clean:
	docker compose -f $(COMPOSE_FILE) down -v

# Default postgres port for docker-compose setup (5433)
POSTGRES_PORT ?= 5433

.PHONY: create-db
create-db:
	PGPASSWORD='postgres' createdb -U postgres -h localhost -p $(POSTGRES_PORT) chronicle || true

frontend/chronicle/src/api/typesGenerated.ts: gen/go $(wildcard scripts/apitypings/*) $(shell find ./api/chroniclesdk $(FIND_EXCLUSIONS) -type f -name '*.go') go.mod go.sum
	# -C sets the directory for the go run command
	go run -C ./scripts/apitypings main.go > $@
	#(cd frontend/chronicle/ && pnpm exec biome format --write src/api/typesGenerated.ts)
	touch "$@"

# All files generated by the database should be added here, and this can be used
# as a target for jobs that need to run after the database is generated.
DB_GEN_FILES := \
	database/dump.sql \
	database/querier.go

database/dump.sql: $(wildcard database/migrations/*.sql)
	go run ./database/gen/dump/*.go

gen/db: $(DB_GEN_FILES)
.PHONY: gen/db


.PHONY: gen/go
gen/go:
	go generate ./...

.PHONY: gen
gen: gen/db gen/go database/unique_constraint.go frontend/chronicle/src/api/typesGenerated.ts
