// Code generated by 'guts'. DO NOT EDIT.

// From chroniclesdk/response.go
export interface LogUploadResponse {
    readonly log_id: string;
    readonly files: [
        string,
        string
    ];
}

// From chroniclesdk/response.go
/**
 * Response represents a generic HTTP response.
 */
export interface Response {
    /**
     * Message is an actionable message that depicts actions the request took.
     * These messages should be fully formed sentences with proper punctuation.
     * Examples:
     * - "A user has been created."
     * - "Failed to create a user."
     */
    readonly message: string;
    /**
     * CallToAction is an optional field that suggests next steps to the user
     * based on the Message. This field is intended to guide users on what to do
     */
    readonly call_to_action?: string;
    /**
     * Detail is a debug message that provides further insight into why the
     * action failed. This information can be technical and a regular golang
     * err.Error() text.
     * - "database: too many open connections"
     * - "stat: too many open files"
     */
    readonly detail?: string;
}


