// Code generated by 'guts'. DO NOT EDIT.

// From chroniclesdk/combat.go
export interface Ability {
    readonly total_damage: number;
    readonly hit_count: number;
    readonly crit_count: number;
    readonly miss_count: number;
    readonly dodge_count: number;
    readonly immune_count: number;
    readonly parry_count: number;
    /**
     * Partial resists and other stuff?
     */
    readonly other_count: number;
}

// From chroniclesdk/combat.go
export interface EncounterDamageSummary {
    readonly encounter_id: string;
    // this is likely an enum in an external package "github.com/Emyrk/chronicle/combatlog/parser/guid.GUID"
    readonly unit_guid: number;
    readonly damage_done_total: number;
    readonly damage_taken_total: number;
    readonly damage_done_abilities: Record<string, Ability>;
    readonly damage_taken_abilities: Record<string, Ability>;
    readonly is_player: boolean;
    // this is likely an enum in an external package "github.com/Emyrk/chronicle/combatlog/parser/guid.GUID"
    readonly owner_guid: number | null;
}

// From chroniclesdk/job.go
export interface JobStatus {
    readonly id: number;
    readonly attempt: number;
    readonly max_attempts: number;
    readonly state: RiverJobState;
    readonly created_at: string;
    readonly scheduled_at: string;
    readonly attempted_at: string | null;
    readonly finalized_at: string | null;
    readonly errors: readonly RiverAttemptError[];
    readonly kind: string;
    readonly output?: Record<string, string>;
}

// From chroniclesdk/response.go
export interface LogUploadResponse {
    readonly log_id: string;
    readonly file_ids: readonly string[];
}

// From chroniclesdk/response.go
/**
 * Response represents a generic HTTP response.
 */
export interface Response {
    /**
     * Message is an actionable message that depicts actions the request took.
     * These messages should be fully formed sentences with proper punctuation.
     * Examples:
     * - "A user has been created."
     * - "Failed to create a user."
     */
    readonly message: string;
    /**
     * CallToAction is an optional field that suggests next steps to the user
     * based on the Message. This field is intended to guide users on what to do
     */
    readonly call_to_action?: string;
    /**
     * Detail is a debug message that provides further insight into why the
     * action failed. This information can be technical and a regular golang
     * err.Error() text.
     * - "database: too many open connections"
     * - "stat: too many open files"
     */
    readonly detail?: string;
}

// From rivertype/river_type.go
/**
 * AttemptError is an error from a single job attempt that failed due to an
 * error or a panic.
 */
export interface RiverAttemptError {
    /**
     * At is the time at which the error occurred.
     */
    readonly at: string;
    /**
     * Attempt is the attempt number on which the error occurred (maps to
     * Attempt on a job row).
     */
    readonly attempt: number;
    /**
     * Error contains the stringified error of an error returned from a job or a
     * panic value in case of a panic.
     */
    readonly error: string;
    /**
     * Trace contains a stack trace from a job that panicked. The trace is
     * produced by invoking `debug.Trace()`.
     *
     * In the case of a non-panic or an error produced as a stuck job was
     * rescued, this value will be an empty string.
     */
    readonly trace: string;
}

// From rivertype/river_type.go
export type RiverJobState = string;

// From chroniclesdk/combat.go
export interface Unit {
    readonly name: string;
}

// From chroniclesdk/log.go
export interface WoWEncounter {
    readonly id: string;
    readonly instance_id: string;
    readonly boss: boolean;
    readonly name: string;
    readonly kill: boolean;
    readonly start_time: string;
    readonly end_time: string;
}

// From chroniclesdk/log.go
export interface WoWInstance {
    readonly id: string;
    readonly realm_id: string;
    readonly log_group_id: string;
    readonly name: string;
}

// From chroniclesdk/log.go
export interface WoWLogFile {
    readonly id: string;
    readonly owner: string;
    readonly wow_log_id: string;
    readonly hash: string;
    readonly size_bytes: number;
    readonly mime_type: string;
    // external type "github.com/jackc/pgx/v5/pgtype.Timestamptz", to include this type the package must be explicitly included in the parsing
    readonly created_at: unknown;
    // external type "github.com/jackc/pgx/v5/pgtype.Timestamptz", to include this type the package must be explicitly included in the parsing
    readonly updated_at: unknown;
}

// From chroniclesdk/log.go
export interface WoWLogGroup {
    readonly id: string;
    readonly owner: string;
    // external type "github.com/jackc/pgx/v5/pgtype.Timestamptz", to include this type the package must be explicitly included in the parsing
    readonly created_at: unknown;
    // external type "github.com/jackc/pgx/v5/pgtype.Timestamptz", to include this type the package must be explicitly included in the parsing
    readonly updated_at: unknown;
    readonly files: readonly WoWLogFile[];
    // empty interface{} type, falling back to unknown
    readonly processing_output?: unknown;
}

// From chroniclesdk/log.go
export interface WoWLogGroupState extends WoWLogGroup {
    readonly status: JobStatus;
}

// From chroniclesdk/log.go
export interface WoWParsedInstance extends WoWInstance {
    readonly encounters: readonly WoWEncounter[];
}

// From chroniclesdk/log.go
export interface WoWParsedLogJobOutput {
    readonly instance_failures: Record<string, string>;
    readonly instances: readonly WoWParsedInstance[];
}


