// Code generated by 'guts'. DO NOT EDIT.

// From chroniclesdk/response.go
export interface LogUploadResponse {
    readonly log_id: string;
    readonly file_ids: readonly string[];
}

// From chroniclesdk/response.go
/**
 * Response represents a generic HTTP response.
 */
export interface Response {
    /**
     * Message is an actionable message that depicts actions the request took.
     * These messages should be fully formed sentences with proper punctuation.
     * Examples:
     * - "A user has been created."
     * - "Failed to create a user."
     */
    readonly message: string;
    /**
     * CallToAction is an optional field that suggests next steps to the user
     * based on the Message. This field is intended to guide users on what to do
     */
    readonly call_to_action?: string;
    /**
     * Detail is a debug message that provides further insight into why the
     * action failed. This information can be technical and a regular golang
     * err.Error() text.
     * - "database: too many open connections"
     * - "stat: too many open files"
     */
    readonly detail?: string;
}

// From chroniclesdk/log.go
export interface WoWLogFile {
    readonly id: string;
    readonly owner: string;
    readonly wow_log_id: string;
    readonly hash: string;
    readonly size_bytes: number;
    readonly mime_type: string;
    // external type "github.com/jackc/pgx/v5/pgtype.Timestamptz", to include this type the package must be explicitly included in the parsing
    readonly created_at: unknown;
    // external type "github.com/jackc/pgx/v5/pgtype.Timestamptz", to include this type the package must be explicitly included in the parsing
    readonly updated_at: unknown;
}

// From chroniclesdk/log.go
export interface WoWLogGroup {
    readonly id: string;
    readonly owner: string;
    // external type "github.com/jackc/pgx/v5/pgtype.Timestamptz", to include this type the package must be explicitly included in the parsing
    readonly created_at: unknown;
    // external type "github.com/jackc/pgx/v5/pgtype.Timestamptz", to include this type the package must be explicitly included in the parsing
    readonly updated_at: unknown;
    readonly files: readonly WoWLogFile[];
}


