// @generated by protoc-gen-es v2.2.0 with parameter "target=ts"
// @generated from file chronicle.proto (package chronicleproto, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file chronicle.proto.
 */
export const file_chronicle: GenFile = /*@__PURE__*/
  fileDesc("Cg9jaHJvbmljbGUucHJvdG8SDmNocm9uaWNsZXByb3RvIiUKD0luc3RhbmNlUmVxdWVzdBISCgppbnN0YW5jZUlkGAEgASgJIjkKBlRhaWxlchITCgZhbW91bnQYASABKA1IAIgBARIPCgdoaXRUeXBlGAIgASgNQgkKB19hbW91bnQiNwoMRGFtYWdlUmVwb3J0EicKB2RhbWFnZXMYASADKAsyFi5jaHJvbmljbGVwcm90by5EYW1hZ2Ui5QEKBkRhbWFnZRITCgtvZmZzZXRNaWxsaRgBIAEoBRITCgZjYXN0ZXIYAiABKAlIAIgBARIWCglzcGVsbE5hbWUYAyABKAlIAYgBARIOCgZ0YXJnZXQYBCABKAkSDwoHaGl0VHlwZRgFIAEoDRIOCgZhbW91bnQYBiABKAUSJgoGc2Nob29sGAcgASgOMhYuY2hyb25pY2xlcHJvdG8uU2Nob29sEicKB3RhaWxlcnMYCCADKAsyFi5jaHJvbmljbGVwcm90by5UYWlsZXJCCQoHX2Nhc3RlckIMCgpfc3BlbGxOYW1lKmMKBlNjaG9vbBIICgROb25lEAASDAoIUGh5c2ljYWwQARIICgRIb2x5EAISCAoERmlyZRADEgoKBk5hdHVyZRAEEgkKBUZyb3N0EAUSCgoGU2hhZG93EAYSCgoGQXJjYW5lEAcyXQoQQ2hyb25pY2xlU2VydmljZRJJCgZEYW1hZ2USHy5jaHJvbmljbGVwcm90by5JbnN0YW5jZVJlcXVlc3QaHC5jaHJvbmljbGVwcm90by5EYW1hZ2VSZXBvcnQiAEIvWi1naXRodWIuY29tL0VteXJrL2Nocm9uaWNsZS9hcGkvY2hyb25pY2xlcHJvdG9iBnByb3RvMw");

/**
 * @generated from message chronicleproto.InstanceRequest
 */
export type InstanceRequest = Message<"chronicleproto.InstanceRequest"> & {
  /**
   * [(buf.validate.field).string = {
   *    min_len: 37,
   *    max_len: 37,
   *  }]
   *
   * @generated from field: string instanceId = 1;
   */
  instanceId: string;
};

/**
 * Describes the message chronicleproto.InstanceRequest.
 * Use `create(InstanceRequestSchema)` to create a new message.
 */
export const InstanceRequestSchema: GenMessage<InstanceRequest> = /*@__PURE__*/
  messageDesc(file_chronicle, 0);

/**
 * @generated from message chronicleproto.Tailer
 */
export type Tailer = Message<"chronicleproto.Tailer"> & {
  /**
   * @generated from field: optional uint32 amount = 1;
   */
  amount?: number;

  /**
   * @generated from field: uint32 hitType = 2;
   */
  hitType: number;
};

/**
 * Describes the message chronicleproto.Tailer.
 * Use `create(TailerSchema)` to create a new message.
 */
export const TailerSchema: GenMessage<Tailer> = /*@__PURE__*/
  messageDesc(file_chronicle, 1);

/**
 * @generated from message chronicleproto.DamageReport
 */
export type DamageReport = Message<"chronicleproto.DamageReport"> & {
  /**
   * @generated from field: repeated chronicleproto.Damage damages = 1;
   */
  damages: Damage[];
};

/**
 * Describes the message chronicleproto.DamageReport.
 * Use `create(DamageReportSchema)` to create a new message.
 */
export const DamageReportSchema: GenMessage<DamageReport> = /*@__PURE__*/
  messageDesc(file_chronicle, 2);

/**
 * @generated from message chronicleproto.Damage
 */
export type Damage = Message<"chronicleproto.Damage"> & {
  /**
   * Offset from the last message
   *
   * @generated from field: int32 offsetMilli = 1;
   */
  offsetMilli: number;

  /**
   * @generated from field: optional string caster = 2;
   */
  caster?: string;

  /**
   * @generated from field: optional string spellName = 3;
   */
  spellName?: string;

  /**
   * @generated from field: string target = 4;
   */
  target: string;

  /**
   * @generated from field: uint32 hitType = 5;
   */
  hitType: number;

  /**
   * @generated from field: int32 amount = 6;
   */
  amount: number;

  /**
   * @generated from field: chronicleproto.School school = 7;
   */
  school: School;

  /**
   * @generated from field: repeated chronicleproto.Tailer tailers = 8;
   */
  tailers: Tailer[];
};

/**
 * Describes the message chronicleproto.Damage.
 * Use `create(DamageSchema)` to create a new message.
 */
export const DamageSchema: GenMessage<Damage> = /*@__PURE__*/
  messageDesc(file_chronicle, 3);

/**
 * @generated from enum chronicleproto.School
 */
export enum School {
  /**
   * @generated from enum value: None = 0;
   */
  None = 0,

  /**
   * @generated from enum value: Physical = 1;
   */
  Physical = 1,

  /**
   * @generated from enum value: Holy = 2;
   */
  Holy = 2,

  /**
   * @generated from enum value: Fire = 3;
   */
  Fire = 3,

  /**
   * @generated from enum value: Nature = 4;
   */
  Nature = 4,

  /**
   * @generated from enum value: Frost = 5;
   */
  Frost = 5,

  /**
   * @generated from enum value: Shadow = 6;
   */
  Shadow = 6,

  /**
   * @generated from enum value: Arcane = 7;
   */
  Arcane = 7,
}

/**
 * Describes the enum chronicleproto.School.
 */
export const SchoolSchema: GenEnum<School> = /*@__PURE__*/
  enumDesc(file_chronicle, 0);

/**
 * @generated from service chronicleproto.ChronicleService
 */
export const ChronicleService: GenService<{
  /**
   * @generated from rpc chronicleproto.ChronicleService.Damage
   */
  damage: {
    methodKind: "unary";
    input: typeof InstanceRequestSchema;
    output: typeof DamageReportSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_chronicle, 0);

