// Code generated by "stringer -type DefenseType -trimprefix DefenseType"; DO NOT EDIT.

package dbc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DefenseTypeNone-0]
	_ = x[DefenseTypeMelee-1]
	_ = x[DefenseTypeRanged-2]
}

const _DefenseType_name = "NoneMeleeRanged"

var _DefenseType_index = [...]uint8{0, 4, 9, 15}

func (i DefenseType) String() string {
	if i < 0 || i >= DefenseType(len(_DefenseType_index)-1) {
		return "DefenseType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DefenseType_name[_DefenseType_index[i]:_DefenseType_index[i+1]]
}
