// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: batch.go

package database

import (
	"context"
	"errors"

	"github.com/Emyrk/chronicle/combatlog/parser/guid"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const insertEncounterCharacterFights = `-- name: InsertEncounterCharacterFights :batchexec
INSERT INTO
  log_instance_encounter_hostiles (id, encounter_id, periods)
VALUES
  ($1, $2, $3)
`

type InsertEncounterCharacterFightsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertEncounterCharacterFightsParams struct {
	ID          guid.GUID `db:"id" json:"id"`
	EncounterID uuid.UUID `db:"encounter_id" json:"encounter_id"`
	Periods     Periods   `db:"periods" json:"periods"`
}

func (q *sqlQuerier) InsertEncounterCharacterFights(ctx context.Context, arg []InsertEncounterCharacterFightsParams) *InsertEncounterCharacterFightsBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ID,
			a.EncounterID,
			a.Periods,
		}
		batch.Queue(insertEncounterCharacterFights, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertEncounterCharacterFightsBatchResults{br, len(arg), false}
}

func (b *InsertEncounterCharacterFightsBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertEncounterCharacterFightsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const insertInstancePlayers = `-- name: InsertInstancePlayers :batchexec
INSERT INTO
  log_instance_players (instance_id, unit_guid, name, level, class, race)
VALUES
  ($1, $2, $3, $4, $5, $6)
`

type InsertInstancePlayersBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertInstancePlayersParams struct {
	InstanceID uuid.UUID        `db:"instance_id" json:"instance_id"`
	UnitGuid   guid.GUID        `db:"unit_guid" json:"unit_guid"`
	Name       string           `db:"name" json:"name"`
	Level      int32            `db:"level" json:"level"`
	Class      WowPlayableClass `db:"class" json:"class"`
	Race       WowPlayableRace  `db:"race" json:"race"`
}

func (q *sqlQuerier) InsertInstancePlayers(ctx context.Context, arg []InsertInstancePlayersParams) *InsertInstancePlayersBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.InstanceID,
			a.UnitGuid,
			a.Name,
			a.Level,
			a.Class,
			a.Race,
		}
		batch.Queue(insertInstancePlayers, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertInstancePlayersBatchResults{br, len(arg), false}
}

func (b *InsertInstancePlayersBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertInstancePlayersBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const insertInstanceUnits = `-- name: InsertInstanceUnits :batchexec
INSERT INTO
  log_instance_units (instance_id, unit_guid, name, entry, owner_guid)
VALUES
  ($1, $2, $3, $4, $5)
`

type InsertInstanceUnitsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertInstanceUnitsParams struct {
	InstanceID uuid.UUID  `db:"instance_id" json:"instance_id"`
	UnitGuid   guid.GUID  `db:"unit_guid" json:"unit_guid"`
	Name       string     `db:"name" json:"name"`
	Entry      int32      `db:"entry" json:"entry"`
	OwnerGuid  *guid.GUID `db:"owner_guid" json:"owner_guid"`
}

func (q *sqlQuerier) InsertInstanceUnits(ctx context.Context, arg []InsertInstanceUnitsParams) *InsertInstanceUnitsBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.InstanceID,
			a.UnitGuid,
			a.Name,
			a.Entry,
			a.OwnerGuid,
		}
		batch.Queue(insertInstanceUnits, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertInstanceUnitsBatchResults{br, len(arg), false}
}

func (b *InsertInstanceUnitsBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertInstanceUnitsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const insertLogEncounterEvents = `-- name: InsertLogEncounterEvents :batchexec
INSERT INTO
  log_instance_encounter_events(encounter_id, start_time, type, events)
VALUES
  ($1, $2, $3, $4)
`

type InsertLogEncounterEventsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertLogEncounterEventsParams struct {
	EncounterID uuid.UUID                     `db:"encounter_id" json:"encounter_id"`
	StartTime   pgtype.Timestamptz            `db:"start_time" json:"start_time"`
	Type        LogInstanceEncounterEventType `db:"type" json:"type"`
	Events      []byte                        `db:"events" json:"events"`
}

func (q *sqlQuerier) InsertLogEncounterEvents(ctx context.Context, arg []InsertLogEncounterEventsParams) *InsertLogEncounterEventsBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.EncounterID,
			a.StartTime,
			a.Type,
			a.Events,
		}
		batch.Queue(insertLogEncounterEvents, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertLogEncounterEventsBatchResults{br, len(arg), false}
}

func (b *InsertLogEncounterEventsBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertLogEncounterEventsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
