// Code generated by scripts/dbgen/main.go. DO NOT EDIT.
package database

// CheckConstraint represents a named check constraint on a table.
type CheckConstraint string

// CheckConstraint enums.
const ()
