-- Code generated by 'make chronicle/database/generate'. DO NOT EDIT.


CREATE TYPE item_effect_type AS ENUM (
    'on_use',
    'on_equip',
    'on_hit',
    'proc'
);

CREATE TYPE spell_school AS ENUM (
    'physical',
    'fire',
    'frost',
    'shadow',
    'arcane',
    'holy',
    'nature'
);

CREATE TABLE item_effects (
    id uuid NOT NULL,
    item_id integer NOT NULL,
    effect_type item_effect_type NOT NULL,
    effect_index smallint,
    spell_id integer NOT NULL
);

CREATE TABLE item_templates (
    id integer NOT NULL,
    name text NOT NULL,
    quality smallint NOT NULL,
    item_level smallint NOT NULL,
    required_level smallint,
    class smallint NOT NULL,
    sub_class smallint NOT NULL,
    inventory_slot smallint NOT NULL,
    icon text,
    unique_limit smallint,
    bind_type smallint,
    stack_size smallint DEFAULT 1,
    description text,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);

COMMENT ON TABLE item_templates IS 'Items without data such as enchants.';

COMMENT ON COLUMN item_templates.id IS 'Matches the item id in WoW.';

COMMENT ON COLUMN item_templates.quality IS '0 grey, 1 white, 2 green, 3 blue, 4 purple, 5 legendary, 6 artifact';

CREATE TABLE spell_templates (
    id integer NOT NULL,
    name text NOT NULL,
    school spell_school NOT NULL,
    description text,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);

CREATE TABLE users (
    id uuid NOT NULL,
    username text NOT NULL
);

ALTER TABLE ONLY item_effects
    ADD CONSTRAINT item_effects_pkey PRIMARY KEY (id);

ALTER TABLE ONLY item_templates
    ADD CONSTRAINT item_templates_pkey PRIMARY KEY (id);

ALTER TABLE ONLY spell_templates
    ADD CONSTRAINT spell_templates_pkey PRIMARY KEY (id);

ALTER TABLE ONLY users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

ALTER TABLE ONLY item_effects
    ADD CONSTRAINT item_effects_item_id_fkey FOREIGN KEY (item_id) REFERENCES item_templates(id);

ALTER TABLE ONLY item_effects
    ADD CONSTRAINT item_effects_spell_id_fkey FOREIGN KEY (spell_id) REFERENCES spell_templates(id);


