// Code generated by scripts/dbgen/main.go. DO NOT EDIT.
package database

// ForeignKeyConstraint represents a named foreign key constraint on a table.
type ForeignKeyConstraint string

// ForeignKeyConstraint enums.
const (
	ForeignKeyItemEffectsItemID         ForeignKeyConstraint = "item_effects_item_id_fkey"           // ALTER TABLE ONLY item_effects ADD CONSTRAINT item_effects_item_id_fkey FOREIGN KEY (item_id) REFERENCES item_templates(id);
	ForeignKeyItemEffectsSpellID        ForeignKeyConstraint = "item_effects_spell_id_fkey"          // ALTER TABLE ONLY item_effects ADD CONSTRAINT item_effects_spell_id_fkey FOREIGN KEY (spell_id) REFERENCES spell_templates(id);
	ForeignKeyLogFileOwner              ForeignKeyConstraint = "log_file_owner_fkey"                 // ALTER TABLE ONLY log_file ADD CONSTRAINT log_file_owner_fkey FOREIGN KEY (owner) REFERENCES users(id);
	ForeignKeyLogFileWowLogID           ForeignKeyConstraint = "log_file_wow_log_id_fkey"            // ALTER TABLE ONLY log_file ADD CONSTRAINT log_file_wow_log_id_fkey FOREIGN KEY (wow_log_id) REFERENCES wow_log_groups(id) ON DELETE CASCADE;
	ForeignKeyUserAuthLinksUserID       ForeignKeyConstraint = "user_auth_links_user_id_fkey"        // ALTER TABLE ONLY user_auth_links ADD CONSTRAINT user_auth_links_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);
	ForeignKeyUserAuthSessionUserAuthID ForeignKeyConstraint = "user_auth_session_user_auth_id_fkey" // ALTER TABLE ONLY user_auth_session ADD CONSTRAINT user_auth_session_user_auth_id_fkey FOREIGN KEY (user_auth_id) REFERENCES user_auth_links(id);
	ForeignKeyUserAuthSessionUserID     ForeignKeyConstraint = "user_auth_session_user_id_fkey"      // ALTER TABLE ONLY user_auth_session ADD CONSTRAINT user_auth_session_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);
	ForeignKeyWowLogGroupsOwner         ForeignKeyConstraint = "wow_log_groups_owner_fkey"           // ALTER TABLE ONLY wow_log_groups ADD CONSTRAINT wow_log_groups_owner_fkey FOREIGN KEY (owner) REFERENCES users(id);
)
