// Code generated by scripts/dbgen/main.go. DO NOT EDIT.
package database

// ForeignKeyConstraint represents a named foreign key constraint on a table.
type ForeignKeyConstraint string

// ForeignKeyConstraint enums.
const (
	ForeignKeyFilesOwner                ForeignKeyConstraint = "files_owner_fkey"                    // ALTER TABLE ONLY files ADD CONSTRAINT files_owner_fkey FOREIGN KEY (owner) REFERENCES users(id);
	ForeignKeyItemEffectsItemID         ForeignKeyConstraint = "item_effects_item_id_fkey"           // ALTER TABLE ONLY item_effects ADD CONSTRAINT item_effects_item_id_fkey FOREIGN KEY (item_id) REFERENCES item_templates(id);
	ForeignKeyItemEffectsSpellID        ForeignKeyConstraint = "item_effects_spell_id_fkey"          // ALTER TABLE ONLY item_effects ADD CONSTRAINT item_effects_spell_id_fkey FOREIGN KEY (spell_id) REFERENCES spell_templates(id);
	ForeignKeyUserAuthLinksUserID       ForeignKeyConstraint = "user_auth_links_user_id_fkey"        // ALTER TABLE ONLY user_auth_links ADD CONSTRAINT user_auth_links_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);
	ForeignKeyUserAuthSessionUserAuthID ForeignKeyConstraint = "user_auth_session_user_auth_id_fkey" // ALTER TABLE ONLY user_auth_session ADD CONSTRAINT user_auth_session_user_auth_id_fkey FOREIGN KEY (user_auth_id) REFERENCES user_auth_links(id);
	ForeignKeyUserAuthSessionUserID     ForeignKeyConstraint = "user_auth_session_user_id_fkey"      // ALTER TABLE ONLY user_auth_session ADD CONSTRAINT user_auth_session_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);
	ForeignKeyWowLogsFirstLogFile       ForeignKeyConstraint = "wow_logs_first_log_file_fkey"        // ALTER TABLE ONLY wow_logs ADD CONSTRAINT wow_logs_first_log_file_fkey FOREIGN KEY (first_log_file) REFERENCES files(id);
	ForeignKeyWowLogsOwner              ForeignKeyConstraint = "wow_logs_owner_fkey"                 // ALTER TABLE ONLY wow_logs ADD CONSTRAINT wow_logs_owner_fkey FOREIGN KEY (owner) REFERENCES users(id);
	ForeignKeyWowLogsSecondLogFile      ForeignKeyConstraint = "wow_logs_second_log_file_fkey"       // ALTER TABLE ONLY wow_logs ADD CONSTRAINT wow_logs_second_log_file_fkey FOREIGN KEY (second_log_file) REFERENCES files(id);
)
