// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ItemEffectType string

const (
	ItemEffectTypeOnUse   ItemEffectType = "on_use"
	ItemEffectTypeOnEquip ItemEffectType = "on_equip"
	ItemEffectTypeOnHit   ItemEffectType = "on_hit"
	ItemEffectTypeProc    ItemEffectType = "proc"
)

func (e *ItemEffectType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ItemEffectType(s)
	case string:
		*e = ItemEffectType(s)
	default:
		return fmt.Errorf("unsupported scan type for ItemEffectType: %T", src)
	}
	return nil
}

type NullItemEffectType struct {
	ItemEffectType ItemEffectType `json:"item_effect_type"`
	Valid          bool           `json:"valid"` // Valid is true if ItemEffectType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullItemEffectType) Scan(value interface{}) error {
	if value == nil {
		ns.ItemEffectType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ItemEffectType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullItemEffectType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ItemEffectType), nil
}

func (e ItemEffectType) Valid() bool {
	switch e {
	case ItemEffectTypeOnUse,
		ItemEffectTypeOnEquip,
		ItemEffectTypeOnHit,
		ItemEffectTypeProc:
		return true
	}
	return false
}

func AllItemEffectTypeValues() []ItemEffectType {
	return []ItemEffectType{
		ItemEffectTypeOnUse,
		ItemEffectTypeOnEquip,
		ItemEffectTypeOnHit,
		ItemEffectTypeProc,
	}
}

type SpellSchool string

const (
	SpellSchoolPhysical SpellSchool = "physical"
	SpellSchoolFire     SpellSchool = "fire"
	SpellSchoolFrost    SpellSchool = "frost"
	SpellSchoolShadow   SpellSchool = "shadow"
	SpellSchoolArcane   SpellSchool = "arcane"
	SpellSchoolHoly     SpellSchool = "holy"
	SpellSchoolNature   SpellSchool = "nature"
)

func (e *SpellSchool) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SpellSchool(s)
	case string:
		*e = SpellSchool(s)
	default:
		return fmt.Errorf("unsupported scan type for SpellSchool: %T", src)
	}
	return nil
}

type NullSpellSchool struct {
	SpellSchool SpellSchool `json:"spell_school"`
	Valid       bool        `json:"valid"` // Valid is true if SpellSchool is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSpellSchool) Scan(value interface{}) error {
	if value == nil {
		ns.SpellSchool, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SpellSchool.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSpellSchool) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SpellSchool), nil
}

func (e SpellSchool) Valid() bool {
	switch e {
	case SpellSchoolPhysical,
		SpellSchoolFire,
		SpellSchoolFrost,
		SpellSchoolShadow,
		SpellSchoolArcane,
		SpellSchoolHoly,
		SpellSchoolNature:
		return true
	}
	return false
}

func AllSpellSchoolValues() []SpellSchool {
	return []SpellSchool{
		SpellSchoolPhysical,
		SpellSchoolFire,
		SpellSchoolFrost,
		SpellSchoolShadow,
		SpellSchoolArcane,
		SpellSchoolHoly,
		SpellSchoolNature,
	}
}

type File struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Owner     uuid.UUID          `db:"owner" json:"owner"`
	Hash      string             `db:"hash" json:"hash"`
	SizeBytes int64              `db:"size_bytes" json:"size_bytes"`
	MimeType  string             `db:"mime_type" json:"mime_type"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ItemEffect struct {
	ID          uuid.UUID      `db:"id" json:"id"`
	ItemID      int32          `db:"item_id" json:"item_id"`
	EffectType  ItemEffectType `db:"effect_type" json:"effect_type"`
	EffectIndex pgtype.Int2    `db:"effect_index" json:"effect_index"`
	SpellID     int32          `db:"spell_id" json:"spell_id"`
}

// Items without data such as enchants.
type ItemTemplate struct {
	// Matches the item id in WoW.
	ID   int32  `db:"id" json:"id"`
	Name string `db:"name" json:"name"`
	// 0 grey, 1 white, 2 green, 3 blue, 4 purple, 5 legendary, 6 artifact
	Quality       int16              `db:"quality" json:"quality"`
	ItemLevel     int16              `db:"item_level" json:"item_level"`
	RequiredLevel pgtype.Int2        `db:"required_level" json:"required_level"`
	Class         int16              `db:"class" json:"class"`
	SubClass      int16              `db:"sub_class" json:"sub_class"`
	InventorySlot int16              `db:"inventory_slot" json:"inventory_slot"`
	Icon          pgtype.Text        `db:"icon" json:"icon"`
	UniqueLimit   pgtype.Int2        `db:"unique_limit" json:"unique_limit"`
	BindType      pgtype.Int2        `db:"bind_type" json:"bind_type"`
	StackSize     pgtype.Int2        `db:"stack_size" json:"stack_size"`
	Description   pgtype.Text        `db:"description" json:"description"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type SpellTemplate struct {
	ID          int32              `db:"id" json:"id"`
	Name        string             `db:"name" json:"name"`
	School      SpellSchool        `db:"school" json:"school"`
	Description pgtype.Text        `db:"description" json:"description"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type User struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Username  string             `db:"username" json:"username"`
	Email     string             `db:"email" json:"email"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type UserAuthLink struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	LinkedID  string             `db:"linked_id" json:"linked_id"`
	UserID    uuid.UUID          `db:"user_id" json:"user_id"`
	Provider  string             `db:"provider" json:"provider"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type UserAuthSession struct {
	ID                uuid.UUID          `db:"id" json:"id"`
	UserAuthID        uuid.UUID          `db:"user_auth_id" json:"user_auth_id"`
	AccessToken       string             `db:"access_token" json:"access_token"`
	AccessTokenSecret string             `db:"access_token_secret" json:"access_token_secret"`
	RefreshToken      string             `db:"refresh_token" json:"refresh_token"`
	ExpiresAt         pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type WoWLog struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	Owner         uuid.UUID          `db:"owner" json:"owner"`
	FirstLogFile  uuid.UUID          `db:"first_log_file" json:"first_log_file"`
	SecondLogFile uuid.UUID          `db:"second_log_file" json:"second_log_file"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
