// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"

	"github.com/Emyrk/chronicle/combatlog/parser/guid"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const instanceEvent = `-- name: InstanceEvent :one
SELECT
  log_instance_events.instance_id, log_instance_events.type, log_instance_events.events
FROM
  log_instance_events
LEFT JOIN
    log_instances
    ON log_instance_events.instance_id = log_instances.id
WHERE
  instance_id = $1 AND
  log_instance_events.type =$2 :: text :: log_instance_event_type
`

type InstanceEventParams struct {
	InstanceID uuid.UUID `db:"instance_id" json:"instance_id"`
	Type       string    `db:"type" json:"type"`
}

func (q *sqlQuerier) InstanceEvent(ctx context.Context, arg InstanceEventParams) (LogInstanceEvent, error) {
	row := q.db.QueryRow(ctx, instanceEvent, arg.InstanceID, arg.Type)
	var i LogInstanceEvent
	err := row.Scan(&i.InstanceID, &i.Type, &i.Events)
	return i, err
}

const deleteWoWLogGroup = `-- name: DeleteWoWLogGroup :exec
DELETE FROM
  wow_log_groups
WHERE
  id = $1
`

func (q *sqlQuerier) DeleteWoWLogGroup(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteWoWLogGroup, id)
	return err
}

const deleteWoWLogGroupFiles = `-- name: DeleteWoWLogGroupFiles :many
UPDATE
  log_file
SET
  storage_deleted_at = $1
WHERE
  wow_log_id = $2
RETURNING id, owner, wow_log_id, hash, size_bytes, mime_type, created_at, updated_at, storage_deleted_at
`

type DeleteWoWLogGroupFilesParams struct {
	StorageDeletedAt pgtype.Timestamptz `db:"storage_deleted_at" json:"storage_deleted_at"`
	WowLogID         uuid.UUID          `db:"wow_log_id" json:"wow_log_id"`
}

func (q *sqlQuerier) DeleteWoWLogGroupFiles(ctx context.Context, arg DeleteWoWLogGroupFilesParams) ([]LogFile, error) {
	rows, err := q.db.Query(ctx, deleteWoWLogGroupFiles, arg.StorageDeletedAt, arg.WowLogID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LogFile
	for rows.Next() {
		var i LogFile
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.WowLogID,
			&i.Hash,
			&i.SizeBytes,
			&i.MimeType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StorageDeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFileByHash = `-- name: GetFileByHash :one
SELECT id, owner, wow_log_id, hash, size_bytes, mime_type, created_at, updated_at, storage_deleted_at FROM log_file WHERE hash = $1
`

func (q *sqlQuerier) GetFileByHash(ctx context.Context, hash string) (LogFile, error) {
	row := q.db.QueryRow(ctx, getFileByHash, hash)
	var i LogFile
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.WowLogID,
		&i.Hash,
		&i.SizeBytes,
		&i.MimeType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StorageDeletedAt,
	)
	return i, err
}

const getWoWLogFilesByGroupID = `-- name: GetWoWLogFilesByGroupID :many
SELECT
  id, owner, wow_log_id, hash, size_bytes, mime_type, created_at, updated_at, storage_deleted_at
FROM
  log_file
WHERE
  wow_log_id = $1
ORDER BY
  created_at DESC
`

func (q *sqlQuerier) GetWoWLogFilesByGroupID(ctx context.Context, wowLogID uuid.UUID) ([]LogFile, error) {
	rows, err := q.db.Query(ctx, getWoWLogFilesByGroupID, wowLogID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LogFile
	for rows.Next() {
		var i LogFile
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.WowLogID,
			&i.Hash,
			&i.SizeBytes,
			&i.MimeType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StorageDeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWoWLogGroupByID = `-- name: GetWoWLogGroupByID :one
SELECT
  wow_log_groups.id, wow_log_groups.owner, wow_log_groups.created_at, wow_log_groups.updated_at,
  COALESCE(
      jsonb_agg(
      jsonb_build_object(
        'id', json_file.id,
        'owner', json_file.owner,
        'wow_log_id', json_file.wow_log_id,
        'hash', json_file.hash,
        'size_bytes', json_file.size_bytes,
        'mime_type', json_file.mime_type,
        'created_at', json_file.created_at,
        'updated_at', json_file.updated_at,
        'storage_deleted_at', json_file.storage_deleted_at
      )
      ORDER BY json_file.created_at
               ) FILTER (WHERE json_file.id IS NOT NULL),
      '[]'::jsonb
  )::wow_log_group_files AS files
FROM
  wow_log_groups
LEFT JOIN log_file json_file
    ON json_file.wow_log_id = wow_log_groups.id
WHERE
  wow_log_groups.id = $1
GROUP BY
  wow_log_groups.id
`

type GetWoWLogGroupByIDRow struct {
	WoWLogGroup WoWLogGroup `db:"wo_wlog_group" json:"wo_wlog_group"`
	Files       []LogFile   `db:"files" json:"files"`
}

func (q *sqlQuerier) GetWoWLogGroupByID(ctx context.Context, id uuid.UUID) (GetWoWLogGroupByIDRow, error) {
	row := q.db.QueryRow(ctx, getWoWLogGroupByID, id)
	var i GetWoWLogGroupByIDRow
	err := row.Scan(
		&i.WoWLogGroup.ID,
		&i.WoWLogGroup.Owner,
		&i.WoWLogGroup.CreatedAt,
		&i.WoWLogGroup.UpdatedAt,
		&i.Files,
	)
	return i, err
}

const getWoWLogGroupsByOwner = `-- name: GetWoWLogGroupsByOwner :many
SELECT
  wow_log_groups.id, wow_log_groups.owner, wow_log_groups.created_at, wow_log_groups.updated_at,
  files_agg.files,
  latest_job.output AS processing_output
FROM
  wow_log_groups
    LEFT JOIN LATERAL (
    SELECT COALESCE(
    jsonb_agg(
      jsonb_build_object(
        'id', lf.id,
        'owner', lf.owner,
        'wow_log_id', lf.wow_log_id,
        'hash', lf.hash,
        'size_bytes', lf.size_bytes,
        'mime_type', lf.mime_type,
        'created_at', lf.created_at,
        'updated_at', lf.updated_at,
        'storage_deleted_at', lf.storage_deleted_at
      )
      ORDER BY lf.created_at) FILTER (WHERE lf.id IS NOT NULL),
      '[]'::jsonb
    )::wow_log_group_files AS files
    FROM log_file lf
    WHERE lf.wow_log_id = wow_log_groups.id
    ) files_agg ON true

    LEFT JOIN LATERAL (
    SELECT rj.metadata->'output' AS output
    FROM river_job rj
    WHERE rj.args ->> 'log_group_id' = wow_log_groups.id::text
    ORDER BY rj.created_at DESC
    LIMIT 1
    ) latest_job ON true
WHERE
  wow_log_groups.owner = $1
ORDER BY
  wow_log_groups.created_at DESC
`

type GetWoWLogGroupsByOwnerRow struct {
	WoWLogGroup      WoWLogGroup `db:"wo_wlog_group" json:"wo_wlog_group"`
	Files            []LogFile   `db:"files" json:"files"`
	ProcessingOutput interface{} `db:"processing_output" json:"processing_output"`
}

func (q *sqlQuerier) GetWoWLogGroupsByOwner(ctx context.Context, owner uuid.UUID) ([]GetWoWLogGroupsByOwnerRow, error) {
	rows, err := q.db.Query(ctx, getWoWLogGroupsByOwner, owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWoWLogGroupsByOwnerRow
	for rows.Next() {
		var i GetWoWLogGroupsByOwnerRow
		if err := rows.Scan(
			&i.WoWLogGroup.ID,
			&i.WoWLogGroup.Owner,
			&i.WoWLogGroup.CreatedAt,
			&i.WoWLogGroup.UpdatedAt,
			&i.Files,
			&i.ProcessingOutput,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertLogFile = `-- name: InsertLogFile :one
INSERT INTO
  log_file(
    id,
    owner,
    hash,
    wow_log_id,
    size_bytes,
    mime_type,
    created_at,
    updated_at
  )
VALUES
  (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
   )
RETURNING id, owner, wow_log_id, hash, size_bytes, mime_type, created_at, updated_at, storage_deleted_at
`

type InsertLogFileParams struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Owner     uuid.UUID          `db:"owner" json:"owner"`
	Hash      string             `db:"hash" json:"hash"`
	WowLogID  uuid.UUID          `db:"wow_log_id" json:"wow_log_id"`
	SizeBytes int64              `db:"size_bytes" json:"size_bytes"`
	MimeType  string             `db:"mime_type" json:"mime_type"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *sqlQuerier) InsertLogFile(ctx context.Context, arg InsertLogFileParams) (LogFile, error) {
	row := q.db.QueryRow(ctx, insertLogFile,
		arg.ID,
		arg.Owner,
		arg.Hash,
		arg.WowLogID,
		arg.SizeBytes,
		arg.MimeType,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i LogFile
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.WowLogID,
		&i.Hash,
		&i.SizeBytes,
		&i.MimeType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StorageDeletedAt,
	)
	return i, err
}

const insertWoWLogGroup = `-- name: InsertWoWLogGroup :one
INSERT INTO
  wow_log_groups(
    id,
    owner,
    created_at,
    updated_at
  )
VALUES
  (
    $1,
    $2,
    $3,
    $4
  )
RETURNING id, owner, created_at, updated_at
`

type InsertWoWLogGroupParams struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Owner     uuid.UUID          `db:"owner" json:"owner"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *sqlQuerier) InsertWoWLogGroup(ctx context.Context, arg InsertWoWLogGroupParams) (WoWLogGroup, error) {
	row := q.db.QueryRow(ctx, insertWoWLogGroup,
		arg.ID,
		arg.Owner,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i WoWLogGroup
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllWoWLogGroupsWithOwner = `-- name: ListAllWoWLogGroupsWithOwner :many
SELECT
  wow_log_groups.id, wow_log_groups.owner, wow_log_groups.created_at, wow_log_groups.updated_at,
  u.username AS owner_name,
  files_agg.files,
  latest_job.output AS processing_output
FROM
  wow_log_groups
    LEFT JOIN users u ON u.id = wow_log_groups.owner
    LEFT JOIN LATERAL (
    SELECT COALESCE(
    jsonb_agg(
      jsonb_build_object(
        'id', lf.id,
        'owner', lf.owner,
        'wow_log_id', lf.wow_log_id,
        'hash', lf.hash,
        'size_bytes', lf.size_bytes,
        'mime_type', lf.mime_type,
        'created_at', lf.created_at,
        'updated_at', lf.updated_at
      )
      ORDER BY lf.created_at) FILTER (WHERE lf.id IS NOT NULL),
      '[]'::jsonb
    )::wow_log_group_files AS files
    FROM log_file lf
    WHERE lf.wow_log_id = wow_log_groups.id
    ) files_agg ON true

    LEFT JOIN LATERAL (
    SELECT rj.metadata->'output' AS output
    FROM river_job rj
    WHERE rj.args ->> 'log_group_id' = wow_log_groups.id::text
    ORDER BY rj.created_at DESC
    LIMIT 1
    ) latest_job ON true
ORDER BY
  wow_log_groups.created_at DESC
`

type ListAllWoWLogGroupsWithOwnerRow struct {
	WoWLogGroup      WoWLogGroup `db:"wo_wlog_group" json:"wo_wlog_group"`
	OwnerName        pgtype.Text `db:"owner_name" json:"owner_name"`
	Files            []LogFile   `db:"files" json:"files"`
	ProcessingOutput interface{} `db:"processing_output" json:"processing_output"`
}

func (q *sqlQuerier) ListAllWoWLogGroupsWithOwner(ctx context.Context) ([]ListAllWoWLogGroupsWithOwnerRow, error) {
	rows, err := q.db.Query(ctx, listAllWoWLogGroupsWithOwner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllWoWLogGroupsWithOwnerRow
	for rows.Next() {
		var i ListAllWoWLogGroupsWithOwnerRow
		if err := rows.Scan(
			&i.WoWLogGroup.ID,
			&i.WoWLogGroup.Owner,
			&i.WoWLogGroup.CreatedAt,
			&i.WoWLogGroup.UpdatedAt,
			&i.OwnerName,
			&i.Files,
			&i.ProcessingOutput,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertGuild = `-- name: UpsertGuild :one
INSERT INTO
  guilds (realm_id, name, created_at)
VALUES
  ($1, $2, $3)
ON CONFLICT (realm_id, name) DO UPDATE
  SET realm_id = EXCLUDED.realm_id  -- no-op, just to return the row
RETURNING id, realm_id, name, created_at
`

type UpsertGuildParams struct {
	RealmID   uuid.UUID          `db:"realm_id" json:"realm_id"`
	Name      string             `db:"name" json:"name"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *sqlQuerier) UpsertGuild(ctx context.Context, arg UpsertGuildParams) (Guild, error) {
	row := q.db.QueryRow(ctx, upsertGuild, arg.RealmID, arg.Name, arg.CreatedAt)
	var i Guild
	err := row.Scan(
		&i.ID,
		&i.RealmID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const deleteThisQuery = `-- name: DeleteThisQuery :exec
SELECT id, name, quality, item_level, required_level, class, sub_class, inventory_slot, icon, unique_limit, bind_type, stack_size, description, created_at, updated_at FROM item_templates
`

func (q *sqlQuerier) DeleteThisQuery(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteThisQuery)
	return err
}

const deleteAllParsedLogsByGroupID = `-- name: DeleteAllParsedLogsByGroupID :exec
DELETE FROM
  parsed_log_group
WHERE
  id = $1
`

func (q *sqlQuerier) DeleteAllParsedLogsByGroupID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllParsedLogsByGroupID, id)
	return err
}

const encountersByInstanceID = `-- name: EncountersByInstanceID :many
SELECT
  id, instance_id, name, kill, remaining, boss, start_time, end_time
FROM
  log_instance_encounters
WHERE
  instance_id = $1
`

func (q *sqlQuerier) EncountersByInstanceID(ctx context.Context, instanceID uuid.UUID) ([]LogInstanceEncounter, error) {
	rows, err := q.db.Query(ctx, encountersByInstanceID, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LogInstanceEncounter
	for rows.Next() {
		var i LogInstanceEncounter
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.Name,
			&i.Kill,
			&i.Remaining,
			&i.Boss,
			&i.StartTime,
			&i.EndTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEncounterSummariesByInstanceID = `-- name: GetEncounterSummariesByInstanceID :many
SELECT
    lie.id,
    lie.name,
    lie.boss,
    lie.kill
FROM log_instance_encounters lie
WHERE lie.instance_id = $1
ORDER BY lie.start_time ASC
`

type GetEncounterSummariesByInstanceIDRow struct {
	ID   uuid.UUID `db:"id" json:"id"`
	Name string    `db:"name" json:"name"`
	Boss bool      `db:"boss" json:"boss"`
	Kill bool      `db:"kill" json:"kill"`
}

func (q *sqlQuerier) GetEncounterSummariesByInstanceID(ctx context.Context, instanceID uuid.UUID) ([]GetEncounterSummariesByInstanceIDRow, error) {
	rows, err := q.db.Query(ctx, getEncounterSummariesByInstanceID, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEncounterSummariesByInstanceIDRow
	for rows.Next() {
		var i GetEncounterSummariesByInstanceIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Boss,
			&i.Kill,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInstanceEncounterCharacterFights = `-- name: GetInstanceEncounterCharacterFights :many
SELECT
  encounter_id, id, periods, boss
FROM
  log_instance_encounter_hostiles
WHERE
  encounter_id IN (SELECT id FROM log_instance_encounters WHERE instance_id = $1)
`

func (q *sqlQuerier) GetInstanceEncounterCharacterFights(ctx context.Context, instanceID uuid.UUID) ([]LogInstanceEncounterHostile, error) {
	rows, err := q.db.Query(ctx, getInstanceEncounterCharacterFights, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LogInstanceEncounterHostile
	for rows.Next() {
		var i LogInstanceEncounterHostile
		if err := rows.Scan(
			&i.EncounterID,
			&i.ID,
			&i.Periods,
			&i.Boss,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertEncounter = `-- name: InsertEncounter :one
INSERT INTO
  log_instance_encounters (id, instance_id, name, kill, remaining, boss, start_time, end_time)
VALUES
  ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, instance_id, name, kill, remaining, boss, start_time, end_time
`

type InsertEncounterParams struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	InstanceID uuid.UUID          `db:"instance_id" json:"instance_id"`
	Name       string             `db:"name" json:"name"`
	Kill       bool               `db:"kill" json:"kill"`
	Remaining  guid.GUIDs         `db:"remaining" json:"remaining"`
	Boss       bool               `db:"boss" json:"boss"`
	StartTime  pgtype.Timestamptz `db:"start_time" json:"start_time"`
	EndTime    pgtype.Timestamptz `db:"end_time" json:"end_time"`
}

func (q *sqlQuerier) InsertEncounter(ctx context.Context, arg InsertEncounterParams) (LogInstanceEncounter, error) {
	row := q.db.QueryRow(ctx, insertEncounter,
		arg.ID,
		arg.InstanceID,
		arg.Name,
		arg.Kill,
		arg.Remaining,
		arg.Boss,
		arg.StartTime,
		arg.EndTime,
	)
	var i LogInstanceEncounter
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.Name,
		&i.Kill,
		&i.Remaining,
		&i.Boss,
		&i.StartTime,
		&i.EndTime,
	)
	return i, err
}

const insertInstance = `-- name: InsertInstance :one
INSERT INTO
  log_instances (id, realm_id, log_group_id, name, hashed_slug, guild_id)
VALUES
  ($1, $2, $3, $4, $5, $6)
RETURNING id, realm_id, log_group_id, name, hashed_slug, guild_id
`

type InsertInstanceParams struct {
	ID         uuid.UUID     `db:"id" json:"id"`
	RealmID    uuid.UUID     `db:"realm_id" json:"realm_id"`
	LogGroupID uuid.UUID     `db:"log_group_id" json:"log_group_id"`
	Name       string        `db:"name" json:"name"`
	HashedSlug pgtype.Text   `db:"hashed_slug" json:"hashed_slug"`
	GuildID    uuid.NullUUID `db:"guild_id" json:"guild_id"`
}

func (q *sqlQuerier) InsertInstance(ctx context.Context, arg InsertInstanceParams) (LogInstance, error) {
	row := q.db.QueryRow(ctx, insertInstance,
		arg.ID,
		arg.RealmID,
		arg.LogGroupID,
		arg.Name,
		arg.HashedSlug,
		arg.GuildID,
	)
	var i LogInstance
	err := row.Scan(
		&i.ID,
		&i.RealmID,
		&i.LogGroupID,
		&i.Name,
		&i.HashedSlug,
		&i.GuildID,
	)
	return i, err
}

const insertParsedLogGroup = `-- name: InsertParsedLogGroup :exec
INSERT INTO
  parsed_log_group (id)
VALUES
  ($1)
`

func (q *sqlQuerier) InsertParsedLogGroup(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, insertParsedLogGroup, id)
	return err
}

const instance = `-- name: Instance :one
SELECT
  id, realm_id, log_group_id, name, hashed_slug, guild_id, guild_name, guild_realm_id, guild_created_at
FROM
  log_instances_guild
WHERE
  log_instances_guild.id = $1
`

func (q *sqlQuerier) Instance(ctx context.Context, id uuid.UUID) (LogInstancesGuild, error) {
	row := q.db.QueryRow(ctx, instance, id)
	var i LogInstancesGuild
	err := row.Scan(
		&i.ID,
		&i.RealmID,
		&i.LogGroupID,
		&i.Name,
		&i.HashedSlug,
		&i.GuildID,
		&i.GuildName,
		&i.GuildRealmID,
		&i.GuildCreatedAt,
	)
	return i, err
}

const instanceBySlug = `-- name: InstanceBySlug :one
SELECT
  id, realm_id, log_group_id, name, hashed_slug, guild_id, guild_name, guild_realm_id, guild_created_at
FROM
  log_instances_guild
WHERE
  hashed_slug = $1 AND hashed_slug != ''
`

func (q *sqlQuerier) InstanceBySlug(ctx context.Context, hashedSlug pgtype.Text) (LogInstancesGuild, error) {
	row := q.db.QueryRow(ctx, instanceBySlug, hashedSlug)
	var i LogInstancesGuild
	err := row.Scan(
		&i.ID,
		&i.RealmID,
		&i.LogGroupID,
		&i.Name,
		&i.HashedSlug,
		&i.GuildID,
		&i.GuildName,
		&i.GuildRealmID,
		&i.GuildCreatedAt,
	)
	return i, err
}

const instancePlayersByInstanceID = `-- name: InstancePlayersByInstanceID :many
SELECT
  instance_id, unit_guid, name, level, class, race, guild_id
FROM
  log_instance_players
WHERE
  instance_id = $1
`

func (q *sqlQuerier) InstancePlayersByInstanceID(ctx context.Context, instanceID uuid.UUID) ([]LogInstancePlayer, error) {
	rows, err := q.db.Query(ctx, instancePlayersByInstanceID, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LogInstancePlayer
	for rows.Next() {
		var i LogInstancePlayer
		if err := rows.Scan(
			&i.InstanceID,
			&i.UnitGuid,
			&i.Name,
			&i.Level,
			&i.Class,
			&i.Race,
			&i.GuildID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const instanceUnitsByInstanceID = `-- name: InstanceUnitsByInstanceID :many
SELECT
  instance_id, unit_guid, name, entry, owner_guid
FROM
  log_instance_units
WHERE
  instance_id = $1
`

func (q *sqlQuerier) InstanceUnitsByInstanceID(ctx context.Context, instanceID uuid.UUID) ([]LogInstanceUnit, error) {
	rows, err := q.db.Query(ctx, instanceUnitsByInstanceID, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LogInstanceUnit
	for rows.Next() {
		var i LogInstanceUnit
		if err := rows.Scan(
			&i.InstanceID,
			&i.UnitGuid,
			&i.Name,
			&i.Entry,
			&i.OwnerGuid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentInstances = `-- name: ListRecentInstances :many
SELECT 
    li.id,
    li.hashed_slug as slug,
    li.name,
    li.realm_id,
    wsr.name as realm_name,
    wlg.owner as uploader_id,
    u.username as uploader_name,
    wlg.created_at as uploaded_at,
    (SELECT COUNT(*) FROM log_instance_players lip WHERE lip.instance_id = li.id) as player_count,
    (SELECT COUNT(*) FROM log_instance_encounters lie WHERE lie.instance_id = li.id AND lie.boss = true) as boss_count,
    (SELECT COUNT(*) FROM log_instance_encounters lie WHERE lie.instance_id = li.id AND lie.boss = true AND lie.kill = true) as boss_kills,
    (SELECT EXTRACT(EPOCH FROM (MAX(lie.end_time) - MIN(lie.start_time))) * 1000 
     FROM log_instance_encounters lie WHERE lie.instance_id = li.id)::float8 as duration_ms
FROM log_instances li
JOIN parsed_log_group plg ON plg.id = li.log_group_id
JOIN wow_log_groups wlg ON wlg.id = plg.id
JOIN users u ON u.id = wlg.owner
JOIN wow_server_realms wsr ON wsr.id = li.realm_id
WHERE true
    -- Filter by instance name
    AND CASE
        WHEN $1 :: text != '' THEN
            li.name = $1
        ELSE true
    END
    -- Filter by realm
    AND CASE
        WHEN $2 :: uuid != '00000000-0000-0000-0000-000000000000'::uuid THEN
            li.realm_id = $2
        ELSE true
    END
    -- Cursor pagination (uploaded_at, id) - pass '0001-01-01' to skip
    AND CASE
        WHEN $3 :: timestamptz != '0001-01-01'::timestamptz THEN
            (wlg.created_at < $3 
             OR (wlg.created_at = $3 AND li.id < $4 :: uuid))
        ELSE true
    END
ORDER BY wlg.created_at DESC, li.id DESC
LIMIT $5
`

type ListRecentInstancesParams struct {
	InstanceName string             `db:"instance_name" json:"instance_name"`
	RealmID      uuid.UUID          `db:"realm_id" json:"realm_id"`
	CursorTime   pgtype.Timestamptz `db:"cursor_time" json:"cursor_time"`
	CursorID     uuid.UUID          `db:"cursor_id" json:"cursor_id"`
	LimitCount   int32              `db:"limit_count" json:"limit_count"`
}

type ListRecentInstancesRow struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	Slug         pgtype.Text        `db:"slug" json:"slug"`
	Name         string             `db:"name" json:"name"`
	RealmID      uuid.UUID          `db:"realm_id" json:"realm_id"`
	RealmName    string             `db:"realm_name" json:"realm_name"`
	UploaderID   uuid.UUID          `db:"uploader_id" json:"uploader_id"`
	UploaderName string             `db:"uploader_name" json:"uploader_name"`
	UploadedAt   pgtype.Timestamptz `db:"uploaded_at" json:"uploaded_at"`
	PlayerCount  int64              `db:"player_count" json:"player_count"`
	BossCount    int64              `db:"boss_count" json:"boss_count"`
	BossKills    int64              `db:"boss_kills" json:"boss_kills"`
	DurationMs   float64            `db:"duration_ms" json:"duration_ms"`
}

func (q *sqlQuerier) ListRecentInstances(ctx context.Context, arg ListRecentInstancesParams) ([]ListRecentInstancesRow, error) {
	rows, err := q.db.Query(ctx, listRecentInstances,
		arg.InstanceName,
		arg.RealmID,
		arg.CursorTime,
		arg.CursorID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentInstancesRow
	for rows.Next() {
		var i ListRecentInstancesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.RealmID,
			&i.RealmName,
			&i.UploaderID,
			&i.UploaderName,
			&i.UploadedAt,
			&i.PlayerCount,
			&i.BossCount,
			&i.BossKills,
			&i.DurationMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentInstancesByPlayer = `-- name: ListRecentInstancesByPlayer :many
SELECT DISTINCT ON (wlg.created_at, li.id)
    li.id,
    li.hashed_slug as slug,
    li.name,
    li.realm_id,
    wsr.name as realm_name,
    wlg.owner as uploader_id,
    u.username as uploader_name,
    wlg.created_at as uploaded_at,
    (SELECT COUNT(*) FROM log_instance_players lip2 WHERE lip2.instance_id = li.id) as player_count,
    (SELECT COUNT(*) FROM log_instance_encounters lie WHERE lie.instance_id = li.id AND lie.boss = true) as boss_count,
    (SELECT COUNT(*) FROM log_instance_encounters lie WHERE lie.instance_id = li.id AND lie.boss = true AND lie.kill = true) as boss_kills,
    (SELECT EXTRACT(EPOCH FROM (MAX(lie.end_time) - MIN(lie.start_time))) * 1000 
     FROM log_instance_encounters lie WHERE lie.instance_id = li.id)::float8 as duration_ms
FROM log_instances li
JOIN log_instance_players lip ON lip.instance_id = li.id
JOIN parsed_log_group plg ON plg.id = li.log_group_id
JOIN wow_log_groups wlg ON wlg.id = plg.id
JOIN users u ON u.id = wlg.owner
JOIN wow_server_realms wsr ON wsr.id = li.realm_id
WHERE lip.name ILIKE $1
    -- Filter by instance name
    AND CASE
        WHEN $2 :: text != '' THEN
            li.name = $2
        ELSE true
    END
    -- Filter by realm
    AND CASE
        WHEN $3 :: uuid != '00000000-0000-0000-0000-000000000000'::uuid THEN
            li.realm_id = $3
        ELSE true
    END
    -- Cursor pagination
    AND CASE
        WHEN $4 :: timestamptz != '0001-01-01'::timestamptz THEN
            (wlg.created_at < $4 
             OR (wlg.created_at = $4 AND li.id < $5 :: uuid))
        ELSE true
    END
ORDER BY wlg.created_at DESC, li.id DESC
LIMIT $6
`

type ListRecentInstancesByPlayerParams struct {
	PlayerName   string             `db:"player_name" json:"player_name"`
	InstanceName string             `db:"instance_name" json:"instance_name"`
	RealmID      uuid.UUID          `db:"realm_id" json:"realm_id"`
	CursorTime   pgtype.Timestamptz `db:"cursor_time" json:"cursor_time"`
	CursorID     uuid.UUID          `db:"cursor_id" json:"cursor_id"`
	LimitCount   int32              `db:"limit_count" json:"limit_count"`
}

type ListRecentInstancesByPlayerRow struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	Slug         pgtype.Text        `db:"slug" json:"slug"`
	Name         string             `db:"name" json:"name"`
	RealmID      uuid.UUID          `db:"realm_id" json:"realm_id"`
	RealmName    string             `db:"realm_name" json:"realm_name"`
	UploaderID   uuid.UUID          `db:"uploader_id" json:"uploader_id"`
	UploaderName string             `db:"uploader_name" json:"uploader_name"`
	UploadedAt   pgtype.Timestamptz `db:"uploaded_at" json:"uploaded_at"`
	PlayerCount  int64              `db:"player_count" json:"player_count"`
	BossCount    int64              `db:"boss_count" json:"boss_count"`
	BossKills    int64              `db:"boss_kills" json:"boss_kills"`
	DurationMs   float64            `db:"duration_ms" json:"duration_ms"`
}

func (q *sqlQuerier) ListRecentInstancesByPlayer(ctx context.Context, arg ListRecentInstancesByPlayerParams) ([]ListRecentInstancesByPlayerRow, error) {
	rows, err := q.db.Query(ctx, listRecentInstancesByPlayer,
		arg.PlayerName,
		arg.InstanceName,
		arg.RealmID,
		arg.CursorTime,
		arg.CursorID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentInstancesByPlayerRow
	for rows.Next() {
		var i ListRecentInstancesByPlayerRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.RealmID,
			&i.RealmName,
			&i.UploaderID,
			&i.UploaderName,
			&i.UploadedAt,
			&i.PlayerCount,
			&i.BossCount,
			&i.BossKills,
			&i.DurationMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserAuthByLinkedID = `-- name: GetUserAuthByLinkedID :one
SELECT
  id, linked_id, user_id, provider, created_at, updated_at
FROM
  user_auth_links
WHERE
  linked_id = $1 AND
  provider = $2
`

type GetUserAuthByLinkedIDParams struct {
	LinkedID string `db:"linked_id" json:"linked_id"`
	Provider string `db:"provider" json:"provider"`
}

func (q *sqlQuerier) GetUserAuthByLinkedID(ctx context.Context, arg GetUserAuthByLinkedIDParams) (UserAuthLink, error) {
	row := q.db.QueryRow(ctx, getUserAuthByLinkedID, arg.LinkedID, arg.Provider)
	var i UserAuthLink
	err := row.Scan(
		&i.ID,
		&i.LinkedID,
		&i.UserID,
		&i.Provider,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserAuthLinkByUserID = `-- name: GetUserAuthLinkByUserID :one
SELECT
  id, linked_id, user_id, provider, created_at, updated_at
FROM
  user_auth_links
WHERE
  user_id = $1
LIMIT 1
`

func (q *sqlQuerier) GetUserAuthLinkByUserID(ctx context.Context, userID uuid.UUID) (UserAuthLink, error) {
	row := q.db.QueryRow(ctx, getUserAuthLinkByUserID, userID)
	var i UserAuthLink
	err := row.Scan(
		&i.ID,
		&i.LinkedID,
		&i.UserID,
		&i.Provider,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserAuthSessionByID = `-- name: GetUserAuthSessionByID :one
SELECT
  id, user_auth_id, user_id, access_token, access_token_secret, refresh_token, expires_at, created_at, updated_at, jwt_id
FROM
  user_auth_session
WHERE
  id = $1
FOR UPDATE
`

func (q *sqlQuerier) GetUserAuthSessionByID(ctx context.Context, id uuid.UUID) (UserAuthSession, error) {
	row := q.db.QueryRow(ctx, getUserAuthSessionByID, id)
	var i UserAuthSession
	err := row.Scan(
		&i.ID,
		&i.UserAuthID,
		&i.UserID,
		&i.AccessToken,
		&i.AccessTokenSecret,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.JwtID,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
  id, username, email, created_at, updated_at, max_storage_bytes, data_limit_updated_at, consumed_storage_bytes
FROM
  chronicle_users
WHERE
  id = $1
`

func (q *sqlQuerier) GetUserByID(ctx context.Context, id uuid.UUID) (ChronicleUser, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i ChronicleUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaxStorageBytes,
		&i.DataLimitUpdatedAt,
		&i.ConsumedStorageBytes,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO
  users(id, username, email, created_at, updated_at)
VALUES
  ($1, $2, $3, $4, $5)
RETURNING id, username, email, created_at, updated_at
`

type InsertUserParams struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Username  string             `db:"username" json:"username"`
	Email     string             `db:"email" json:"email"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *sqlQuerier) InsertUser(ctx context.Context, arg InsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, insertUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertUserAuth = `-- name: InsertUserAuth :one
INSERT INTO
  user_auth_links(id, linked_id, user_id, provider, created_at, updated_at)
VALUES
  ($1, $2, $3, $4, $5, $6)
RETURNING id, linked_id, user_id, provider, created_at, updated_at
`

type InsertUserAuthParams struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	LinkedID  string             `db:"linked_id" json:"linked_id"`
	UserID    uuid.UUID          `db:"user_id" json:"user_id"`
	Provider  string             `db:"provider" json:"provider"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *sqlQuerier) InsertUserAuth(ctx context.Context, arg InsertUserAuthParams) (UserAuthLink, error) {
	row := q.db.QueryRow(ctx, insertUserAuth,
		arg.ID,
		arg.LinkedID,
		arg.UserID,
		arg.Provider,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i UserAuthLink
	err := row.Scan(
		&i.ID,
		&i.LinkedID,
		&i.UserID,
		&i.Provider,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertUserAuthSession = `-- name: InsertUserAuthSession :one
INSERT INTO
  user_auth_session(id, user_id, user_auth_id, access_token, access_token_secret, refresh_token, expires_at, created_at, updated_at, jwt_id)
VALUES
  ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, user_auth_id, user_id, access_token, access_token_secret, refresh_token, expires_at, created_at, updated_at, jwt_id
`

type InsertUserAuthSessionParams struct {
	ID                uuid.UUID          `db:"id" json:"id"`
	UserID            uuid.UUID          `db:"user_id" json:"user_id"`
	UserAuthID        uuid.UUID          `db:"user_auth_id" json:"user_auth_id"`
	AccessToken       string             `db:"access_token" json:"access_token"`
	AccessTokenSecret string             `db:"access_token_secret" json:"access_token_secret"`
	RefreshToken      string             `db:"refresh_token" json:"refresh_token"`
	ExpiresAt         pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	JwtID             uuid.UUID          `db:"jwt_id" json:"jwt_id"`
}

func (q *sqlQuerier) InsertUserAuthSession(ctx context.Context, arg InsertUserAuthSessionParams) (UserAuthSession, error) {
	row := q.db.QueryRow(ctx, insertUserAuthSession,
		arg.ID,
		arg.UserID,
		arg.UserAuthID,
		arg.AccessToken,
		arg.AccessTokenSecret,
		arg.RefreshToken,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.JwtID,
	)
	var i UserAuthSession
	err := row.Scan(
		&i.ID,
		&i.UserAuthID,
		&i.UserID,
		&i.AccessToken,
		&i.AccessTokenSecret,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.JwtID,
	)
	return i, err
}

const listAllUsers = `-- name: ListAllUsers :many
SELECT
  id, username, email, created_at, updated_at, max_storage_bytes, data_limit_updated_at, consumed_storage_bytes
FROM
  chronicle_users
ORDER BY
  created_at DESC
`

func (q *sqlQuerier) ListAllUsers(ctx context.Context) ([]ChronicleUser, error) {
	rows, err := q.db.Query(ctx, listAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChronicleUser
	for rows.Next() {
		var i ChronicleUser
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MaxStorageBytes,
			&i.DataLimitUpdatedAt,
			&i.ConsumedStorageBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserStorageLimit = `-- name: SetUserStorageLimit :one
UPDATE
  data_limit
SET
  max_storage_bytes = $2,
  updated_at = $3
WHERE
  user_id = $1
RETURNING user_id, max_storage_bytes, updated_at
`

type SetUserStorageLimitParams struct {
	UserID          uuid.UUID          `db:"user_id" json:"user_id"`
	MaxStorageBytes int64              `db:"max_storage_bytes" json:"max_storage_bytes"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *sqlQuerier) SetUserStorageLimit(ctx context.Context, arg SetUserStorageLimitParams) (DataLimit, error) {
	row := q.db.QueryRow(ctx, setUserStorageLimit, arg.UserID, arg.MaxStorageBytes, arg.UpdatedAt)
	var i DataLimit
	err := row.Scan(&i.UserID, &i.MaxStorageBytes, &i.UpdatedAt)
	return i, err
}

const updateUserAuthSessionTokens = `-- name: UpdateUserAuthSessionTokens :one
UPDATE
  user_auth_session
SET
  access_token = $2,
  access_token_secret = $3,
  refresh_token = $4,
  expires_at = $5,
  updated_at = $6,
  jwt_id = $7
WHERE
  id = $1
RETURNING id, user_auth_id, user_id, access_token, access_token_secret, refresh_token, expires_at, created_at, updated_at, jwt_id
`

type UpdateUserAuthSessionTokensParams struct {
	ID                uuid.UUID          `db:"id" json:"id"`
	AccessToken       string             `db:"access_token" json:"access_token"`
	AccessTokenSecret string             `db:"access_token_secret" json:"access_token_secret"`
	RefreshToken      string             `db:"refresh_token" json:"refresh_token"`
	ExpiresAt         pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	JwtID             uuid.UUID          `db:"jwt_id" json:"jwt_id"`
}

func (q *sqlQuerier) UpdateUserAuthSessionTokens(ctx context.Context, arg UpdateUserAuthSessionTokensParams) (UserAuthSession, error) {
	row := q.db.QueryRow(ctx, updateUserAuthSessionTokens,
		arg.ID,
		arg.AccessToken,
		arg.AccessTokenSecret,
		arg.RefreshToken,
		arg.ExpiresAt,
		arg.UpdatedAt,
		arg.JwtID,
	)
	var i UserAuthSession
	err := row.Scan(
		&i.ID,
		&i.UserAuthID,
		&i.UserID,
		&i.AccessToken,
		&i.AccessTokenSecret,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.JwtID,
	)
	return i, err
}

const getInstanceYoutubeData = `-- name: GetInstanceYoutubeData :one
SELECT
  log_instance_id, created_at, exported_at, video_url, payload
FROM
  log_instance_youtube_timestamped
WHERE
  log_instance_id = $1
`

func (q *sqlQuerier) GetInstanceYoutubeData(ctx context.Context, logInstanceID uuid.UUID) (LogInstanceYoutubeTimestamped, error) {
	row := q.db.QueryRow(ctx, getInstanceYoutubeData, logInstanceID)
	var i LogInstanceYoutubeTimestamped
	err := row.Scan(
		&i.LogInstanceID,
		&i.CreatedAt,
		&i.ExportedAt,
		&i.VideoUrl,
		&i.Payload,
	)
	return i, err
}

const insertStampedYoutubeVideo = `-- name: InsertStampedYoutubeVideo :exec
INSERT INTO
  log_instance_youtube_timestamped (log_instance_id, created_at, exported_at, video_url, payload)
VALUES
  ($1, $2, $3, $4, $5)
ON CONFLICT (log_instance_id) DO UPDATE
SET
  created_at = EXCLUDED.created_at,
  exported_at = EXCLUDED.exported_at,
  video_url = EXCLUDED.video_url,
  payload = EXCLUDED.payload
`

type InsertStampedYoutubeVideoParams struct {
	LogInstanceID uuid.UUID          `db:"log_instance_id" json:"log_instance_id"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ExportedAt    pgtype.Timestamptz `db:"exported_at" json:"exported_at"`
	VideoUrl      string             `db:"video_url" json:"video_url"`
	Payload       []VideoTimestamp   `db:"payload" json:"payload"`
}

func (q *sqlQuerier) InsertStampedYoutubeVideo(ctx context.Context, arg InsertStampedYoutubeVideoParams) error {
	_, err := q.db.Exec(ctx, insertStampedYoutubeVideo,
		arg.LogInstanceID,
		arg.CreatedAt,
		arg.ExportedAt,
		arg.VideoUrl,
		arg.Payload,
	)
	return err
}
