// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"

	"github.com/google/uuid"
)

type sqlcQuerier interface {
	DeleteAllParsedLogsByGroupID(ctx context.Context, id uuid.UUID) error
	DeleteThisQuery(ctx context.Context) error
	DeleteWoWLogGroup(ctx context.Context, id uuid.UUID) error
	GetUserAuthByLinkedID(ctx context.Context, arg GetUserAuthByLinkedIDParams) (UserAuthLink, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetWoWLogFilesByGroupID(ctx context.Context, wowLogID uuid.UUID) ([]LogFile, error)
	GetWoWLogGroupByID(ctx context.Context, id uuid.UUID) (GetWoWLogGroupByIDRow, error)
	GetWoWLogGroupsByOwner(ctx context.Context, owner uuid.UUID) ([]GetWoWLogGroupsByOwnerRow, error)
	InsertEncounter(ctx context.Context, arg InsertEncounterParams) (LogEncounter, error)
	InsertEncounterDamageSummary(ctx context.Context, arg InsertEncounterDamageSummaryParams) (EncounterDamageUnitsSummary, error)
	InsertInstance(ctx context.Context, arg InsertInstanceParams) (LogInstance, error)
	InsertLogFile(ctx context.Context, arg InsertLogFileParams) (LogFile, error)
	InsertParsedLogGroup(ctx context.Context, id uuid.UUID) error
	InsertUser(ctx context.Context, arg InsertUserParams) (User, error)
	InsertUserAuth(ctx context.Context, arg InsertUserAuthParams) (UserAuthLink, error)
	InsertUserAuthSession(ctx context.Context, arg InsertUserAuthSessionParams) (UserAuthSession, error)
	InsertWoWLogGroup(ctx context.Context, arg InsertWoWLogGroupParams) (WoWLogGroup, error)
}

var _ sqlcQuerier = (*sqlQuerier)(nil)
