// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"

	"github.com/google/uuid"
)

type sqlcQuerier interface {
	DeleteThisQuery(ctx context.Context) error
	GetUserAuthByLinkedID(ctx context.Context, arg GetUserAuthByLinkedIDParams) (UserAuthLink, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	InsertFile(ctx context.Context, arg InsertFileParams) (File, error)
	InsertUser(ctx context.Context, arg InsertUserParams) (User, error)
	InsertUserAuth(ctx context.Context, arg InsertUserAuthParams) (UserAuthLink, error)
	InsertUserAuthSession(ctx context.Context, arg InsertUserAuthSessionParams) (UserAuthSession, error)
	InsertWowLog(ctx context.Context, arg InsertWowLogParams) (WoWLog, error)
}

var _ sqlcQuerier = (*sqlQuerier)(nil)
