import type { WoWSpell } from "@/api/wowdb";

export function buildLayoutSpellTooltip(layout: {
  title: string;
  description: string;
  icon: string;
}): WoWSpell {
  return {
    id: 0,
    name: { "0": layout.title },
    subtext: { "0": "" },
    description: {
      "0": layout.description || "No description",
    },
    aura_description: { "0": "" },
    spell_icon: { ID: 1, TextureFilename: layout.icon || "INV_Misc_Book_09" },
    active_icon: { ID: 1, TextureFilename: layout.icon || "INV_Misc_Book_09" },
    spell_level: 0,
    base_level: 0,
    max_level: 0,
    category: { ID: 0, Flags: 0, UsesPerWeek: 0, Name: "", MaxCharges: 0, ChargeRecoveryTime: 0, TypeMask: 0 },
    school: { value: 0, string: "" },
    spell_class_set: { value: 0, string: "General" },
    spell_class_mask: 0,
    power_type: { value: 0, string: "Mana" },
    mana_cost: 0,
    mana_cost_pct: 0,
    mana_cost_per_level: 0,
    mana_per_second: 0,
    reagent: [],
    reagent_count: [],
    casting_time: { ID: 0, Base: 0, PerLevel: 0, Minimum: 0 },
    range: { ID: 0, RangeMin: 0, RangeMax: 0, Flags: 0, Name: "Self" },
    duration: { ID: 0, Duration: 0, DurationPerLevel: 0, MaxDuration: 0 },
    recovery_time: 0,
    start_recovery_time: 0,
    start_recovery_category: 0,
    category_recovery_time: 0,
    mechanic: { value: 0, string: "None" },
    dispel_type: { value: 0, string: "None" },
    prevention_type: { value: 0, string: "None" },
    defense_type: { value: 0, string: "None" },
    caster_aura_state: { value: 0, string: "None" },
    target_aura_state: { value: 0, string: "None" },
    interrupt_flags: { mask: 0, string: "" },
    aura_interrupt_flags: { mask: 0, string: "" },
    effect: [],
    effect_aura: [],
    effect_base_points: [],
    effect_die_sides: [],
    effect_base_dice: [],
    effect_dice_per_level: [],
    effect_real_points_per_level: [],
    effect_aura_period: [],
    effect_amplitude: [],
    effect_chain_amplitude: [],
    effect_chain_targets: [],
    effect_trigger_spell: [],
    effect_item_type: [],
    effect_misc_value: [],
    effect_mechanic: [],
    effect_points_per_combo: [],
    effect_radius: [],
    implicit_target_a: [],
    implicit_target_b: [],
    proc_chance: 0,
    proc_charges: 0,
    proc_type_mask: { mask: 0, string: "" },
    proc_flags: { mask: 0, string: "" },
    targets: { mask: 0, string: "" },
    max_targets: 0,
    max_target_level: 0,
    target_creature_type: { mask: 0, string: "" },
    attributes: { blocks: [], string: "" },
    equipped_item_class: { value: 0, string: "None" },
    equipped_item_subclass: 0,
    equipped_item_inv_types: { mask: 0, string: "" },
    speed: 0,
    spell_priority: 0,
    stance_bar_order: 0,
    cumulative_aura: 0,
    modal_next_spell: 0,
    requires_spell_focus: { ID: 0, Name: "" },
    totems_id: 0,
    totem: [],
    cast_ui: 0,
    required_aura_vision: 0,
    min_faction_id: 0,
    min_reputation: 0,
    spell_visual_id: [],
    damage_type: 0,
    attack_outcome: 0,
  };
}
