// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package chroniclesdk

import (
	"errors"
	"fmt"
	"strings"
)

const (
	// WoWEventTypeDamage is a WoWEventType of type damage.
	WoWEventTypeDamage WoWEventType = "damage"
	// WoWEventTypeHeal is a WoWEventType of type heal.
	WoWEventTypeHeal WoWEventType = "heal"
	// WoWEventTypeResourceChange is a WoWEventType of type resource_change.
	WoWEventTypeResourceChange WoWEventType = "resource_change"
	// WoWEventTypeExtraAttack is a WoWEventType of type extra_attack.
	WoWEventTypeExtraAttack WoWEventType = "extra_attack"
	// WoWEventTypeSlain is a WoWEventType of type slain.
	WoWEventTypeSlain WoWEventType = "slain"
	// WoWEventTypeCast is a WoWEventType of type cast.
	WoWEventTypeCast WoWEventType = "cast"
	// WoWEventTypeAura is a WoWEventType of type aura.
	WoWEventTypeAura WoWEventType = "aura"
)

var ErrInvalidWoWEventType = errors.New("not a valid WoWEventType")

// WoWEventTypeValues returns a list of the values for WoWEventType
func WoWEventTypeValues() []WoWEventType {
	return []WoWEventType{
		WoWEventTypeDamage,
		WoWEventTypeHeal,
		WoWEventTypeResourceChange,
		WoWEventTypeExtraAttack,
		WoWEventTypeSlain,
		WoWEventTypeCast,
		WoWEventTypeAura,
	}
}

// String implements the Stringer interface.
func (x WoWEventType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x WoWEventType) IsValid() bool {
	_, err := ParseWoWEventType(string(x))
	return err == nil
}

var _WoWEventTypeValue = map[string]WoWEventType{
	"damage":          WoWEventTypeDamage,
	"heal":            WoWEventTypeHeal,
	"resource_change": WoWEventTypeResourceChange,
	"extra_attack":    WoWEventTypeExtraAttack,
	"slain":           WoWEventTypeSlain,
	"cast":            WoWEventTypeCast,
	"aura":            WoWEventTypeAura,
}

// ParseWoWEventType attempts to convert a string to a WoWEventType.
func ParseWoWEventType(name string) (WoWEventType, error) {
	if x, ok := _WoWEventTypeValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _WoWEventTypeValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return WoWEventType(""), fmt.Errorf("%s is %w", name, ErrInvalidWoWEventType)
}
