package compiled

import (
	"bytes"
	"fmt"
	replace "github.com/KromDaniel/regengo/replace"
	stream "github.com/KromDaniel/regengo/stream"
	"io"
	"strings"
	"sync"
	"unicode/utf8"
)

// Code generated by regengo for pattern: (.+[^\s]) creates (.+[^\s])\.
// DO NOT EDIT.

var reCreatesStackPool = sync.Pool{New: func() interface{} {
	stack := make([][3]int, 0, 32)
	return &stack
}}

var reCreatesCaptureStackPool = sync.Pool{New: func() interface{} {
	stack := make([]int, 0, 96)
	return &stack
}}

type ReCreates struct{}

var CompiledReCreates = ReCreates{}

// MinMatchLen is the minimum number of bytes any match can have.
const ReCreatesMinMatchLen = 14

// MaxMatchLen is the maximum number of bytes any match can have.
// -1 means unbounded (pattern contains * or + quantifiers).
const ReCreatesMaxMatchLen = -1

func (ReCreates) MatchLengthInfo() (minLen, maxLen int) {
	return ReCreatesMinMatchLen, ReCreatesMaxMatchLen
}

func (ReCreates) MatchString(input string) bool {
	l := len(input)
	offset := 0
	stackPtr := reCreatesStackPool.Get().(*[][3]int)
	stack := (*stackPtr)[:0]
	defer func() {
		for i := range stack {
			stack[i] = [3]int{0, 0, 0}
		}
		*stackPtr = stack[:0]
		reCreatesStackPool.Put(stackPtr)
	}()
	nextInstruction := 1
	goto StepSelect
TryFallback:
	if len(stack) > 0 {
		last := stack[len(stack)-1]
		offset = last[0]
		nextInstruction = last[1]
		stack = stack[:len(stack)-1]
		goto StepSelect
	} else {
		if l > offset {
			nextInstruction = 1
			offset++
			goto StepSelect
		}
		return false
	}
StepSelect:
	switch nextInstruction {
	case 0:
		goto Ins0
	case 1:
		goto Ins1
	case 2:
		goto Ins2
	case 3:
		goto Ins3
	case 4:
		goto Ins4
	case 5:
		goto Ins5
	case 6:
		goto Ins6
	case 7:
		goto Ins7
	case 8:
		goto Ins8
	case 9:
		goto Ins9
	case 10:
		goto Ins10
	case 11:
		goto Ins11
	case 12:
		goto Ins12
	case 13:
		goto Ins13
	case 14:
		goto Ins14
	case 15:
		goto Ins15
	case 16:
		goto Ins16
	case 17:
		goto Ins17
	case 18:
		goto Ins18
	case 19:
		goto Ins19
	case 20:
		goto Ins20
	case 21:
		goto Ins21
	}
Ins0:
	{
		return false
	}
Ins1:
	{
		goto Ins2
	}
Ins2:
	{
		if l <= offset || input[offset] == uint8(0xa) {
			goto TryFallback
		}
		offset++
		goto Ins3
	}
Ins3:
	{
		stack = append(stack, [3]int{offset, 2, 0})
		goto Ins4
	}
Ins4:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] < uint8(0x80) {
			if [32]byte{uint8(0xff), uint8(0xc9), uint8(0xff), uint8(0xff), uint8(0xfe), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0)}[input[offset]/8]&(1<<(input[offset]%8)) == 0 {
				goto TryFallback
			}
			offset++
			goto Ins5
		}
		r, width := utf8.DecodeRuneInString(input[offset:])
		if !(r >= int32(0) && r <= int32(8)) && !(r >= int32(11) && r <= int32(11)) && !(r >= int32(14) && r <= int32(31)) && !(r >= int32(33) && r <= int32(1114111)) {
			goto TryFallback
		}
		offset += width
		goto Ins5
	}
Ins5:
	{
		goto Ins6
	}
Ins6:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] != uint8(0x20) {
			goto TryFallback
		}
		offset++
		goto Ins7
	}
Ins7:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] != uint8(0x63) {
			goto TryFallback
		}
		offset++
		goto Ins8
	}
Ins8:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] != uint8(0x72) {
			goto TryFallback
		}
		offset++
		goto Ins9
	}
Ins9:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] != uint8(0x65) {
			goto TryFallback
		}
		offset++
		goto Ins10
	}
Ins10:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] != uint8(0x61) {
			goto TryFallback
		}
		offset++
		goto Ins11
	}
Ins11:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] != uint8(0x74) {
			goto TryFallback
		}
		offset++
		goto Ins12
	}
Ins12:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] != uint8(0x65) {
			goto TryFallback
		}
		offset++
		goto Ins13
	}
Ins13:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] != uint8(0x73) {
			goto TryFallback
		}
		offset++
		goto Ins14
	}
Ins14:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] != uint8(0x20) {
			goto TryFallback
		}
		offset++
		goto Ins15
	}
Ins15:
	{
		goto Ins16
	}
Ins16:
	{
		if l <= offset || input[offset] == uint8(0xa) {
			goto TryFallback
		}
		offset++
		goto Ins17
	}
Ins17:
	{
		stack = append(stack, [3]int{offset, 16, 0})
		goto Ins18
	}
Ins18:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] < uint8(0x80) {
			if [32]byte{uint8(0xff), uint8(0xc9), uint8(0xff), uint8(0xff), uint8(0xfe), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0)}[input[offset]/8]&(1<<(input[offset]%8)) == 0 {
				goto TryFallback
			}
			offset++
			goto Ins19
		}
		r, width := utf8.DecodeRuneInString(input[offset:])
		if !(r >= int32(0) && r <= int32(8)) && !(r >= int32(11) && r <= int32(11)) && !(r >= int32(14) && r <= int32(31)) && !(r >= int32(33) && r <= int32(1114111)) {
			goto TryFallback
		}
		offset += width
		goto Ins19
	}
Ins19:
	{
		goto Ins20
	}
Ins20:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] != uint8(0x2e) {
			goto TryFallback
		}
		offset++
		goto Ins21
	}
Ins21:
	{
		return true
	}
}
func (ReCreates) MatchBytes(input []byte) bool {
	l := len(input)
	offset := 0
	stackPtr := reCreatesStackPool.Get().(*[][3]int)
	stack := (*stackPtr)[:0]
	defer func() {
		for i := range stack {
			stack[i] = [3]int{0, 0, 0}
		}
		*stackPtr = stack[:0]
		reCreatesStackPool.Put(stackPtr)
	}()
	nextInstruction := 1
	goto StepSelect
TryFallback:
	if len(stack) > 0 {
		last := stack[len(stack)-1]
		offset = last[0]
		nextInstruction = last[1]
		stack = stack[:len(stack)-1]
		goto StepSelect
	} else {
		if l > offset {
			nextInstruction = 1
			offset++
			goto StepSelect
		}
		return false
	}
StepSelect:
	switch nextInstruction {
	case 0:
		goto Ins0
	case 1:
		goto Ins1
	case 2:
		goto Ins2
	case 3:
		goto Ins3
	case 4:
		goto Ins4
	case 5:
		goto Ins5
	case 6:
		goto Ins6
	case 7:
		goto Ins7
	case 8:
		goto Ins8
	case 9:
		goto Ins9
	case 10:
		goto Ins10
	case 11:
		goto Ins11
	case 12:
		goto Ins12
	case 13:
		goto Ins13
	case 14:
		goto Ins14
	case 15:
		goto Ins15
	case 16:
		goto Ins16
	case 17:
		goto Ins17
	case 18:
		goto Ins18
	case 19:
		goto Ins19
	case 20:
		goto Ins20
	case 21:
		goto Ins21
	}
Ins0:
	{
		return false
	}
Ins1:
	{
		goto Ins2
	}
Ins2:
	{
		if l <= offset || input[offset] == uint8(0xa) {
			goto TryFallback
		}
		offset++
		goto Ins3
	}
Ins3:
	{
		stack = append(stack, [3]int{offset, 2, 0})
		goto Ins4
	}
Ins4:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] < uint8(0x80) {
			if [32]byte{uint8(0xff), uint8(0xc9), uint8(0xff), uint8(0xff), uint8(0xfe), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0)}[input[offset]/8]&(1<<(input[offset]%8)) == 0 {
				goto TryFallback
			}
			offset++
			goto Ins5
		}
		r, width := utf8.DecodeRune(input[offset:])
		if !(r >= int32(0) && r <= int32(8)) && !(r >= int32(11) && r <= int32(11)) && !(r >= int32(14) && r <= int32(31)) && !(r >= int32(33) && r <= int32(1114111)) {
			goto TryFallback
		}
		offset += width
		goto Ins5
	}
Ins5:
	{
		goto Ins6
	}
Ins6:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] != uint8(0x20) {
			goto TryFallback
		}
		offset++
		goto Ins7
	}
Ins7:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] != uint8(0x63) {
			goto TryFallback
		}
		offset++
		goto Ins8
	}
Ins8:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] != uint8(0x72) {
			goto TryFallback
		}
		offset++
		goto Ins9
	}
Ins9:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] != uint8(0x65) {
			goto TryFallback
		}
		offset++
		goto Ins10
	}
Ins10:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] != uint8(0x61) {
			goto TryFallback
		}
		offset++
		goto Ins11
	}
Ins11:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] != uint8(0x74) {
			goto TryFallback
		}
		offset++
		goto Ins12
	}
Ins12:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] != uint8(0x65) {
			goto TryFallback
		}
		offset++
		goto Ins13
	}
Ins13:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] != uint8(0x73) {
			goto TryFallback
		}
		offset++
		goto Ins14
	}
Ins14:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] != uint8(0x20) {
			goto TryFallback
		}
		offset++
		goto Ins15
	}
Ins15:
	{
		goto Ins16
	}
Ins16:
	{
		if l <= offset || input[offset] == uint8(0xa) {
			goto TryFallback
		}
		offset++
		goto Ins17
	}
Ins17:
	{
		stack = append(stack, [3]int{offset, 16, 0})
		goto Ins18
	}
Ins18:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] < uint8(0x80) {
			if [32]byte{uint8(0xff), uint8(0xc9), uint8(0xff), uint8(0xff), uint8(0xfe), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0)}[input[offset]/8]&(1<<(input[offset]%8)) == 0 {
				goto TryFallback
			}
			offset++
			goto Ins19
		}
		r, width := utf8.DecodeRune(input[offset:])
		if !(r >= int32(0) && r <= int32(8)) && !(r >= int32(11) && r <= int32(11)) && !(r >= int32(14) && r <= int32(31)) && !(r >= int32(33) && r <= int32(1114111)) {
			goto TryFallback
		}
		offset += width
		goto Ins19
	}
Ins19:
	{
		goto Ins20
	}
Ins20:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] != uint8(0x2e) {
			goto TryFallback
		}
		offset++
		goto Ins21
	}
Ins21:
	{
		return true
	}
}

type ReCreatesResult struct {
	Match  string // Full match
	Group1 string
	Group2 string
}

type ReCreatesBytesResult struct {
	Match  []byte // Full match
	Group1 []byte
	Group2 []byte
}

func (ReCreates) FindStringReuse(input string, r *ReCreatesResult) (*ReCreatesResult, bool) {
	l := len(input)
	offset := 0
	var captures [6]int
	captureStackPtr := reCreatesCaptureStackPool.Get().(*[]int)
	captureStack := (*captureStackPtr)[:0]
	defer func() {
		*captureStackPtr = captureStack[:0]
		reCreatesCaptureStackPool.Put(captureStackPtr)
	}()
	stackPtr := reCreatesStackPool.Get().(*[][3]int)
	stack := (*stackPtr)[:0]
	defer func() {
		for i := range stack {
			stack[i] = [3]int{0, 0, 0}
		}
		*stackPtr = stack[:0]
		reCreatesStackPool.Put(stackPtr)
	}()
	captures[0] = 0
	nextInstruction := 1
	goto StepSelect
TryFallback:
	if len(stack) > 0 {
		last := stack[len(stack)-1]
		offset = last[0]
		nextInstruction = last[1]
		stack = stack[:len(stack)-1]
		if last[2] == 1 && len(captureStack) > 0 {
			n := len(captures)
			top := len(captureStack) - n
			copy(captures[:], captureStack[top:])
			captureStack = captureStack[:top]
		}
		goto StepSelect
	} else {
		if l > offset {
			offset++
			for i := range captures {
				captures[i] = 0
			}
			captureStack = captureStack[:0]
			captures[0] = offset
			nextInstruction = 1
			goto StepSelect
		}
		return nil, false
	}
StepSelect:
	switch nextInstruction {
	case 0:
		goto Ins0
	case 1:
		goto Ins1
	case 2:
		goto Ins2
	case 3:
		goto Ins3
	case 4:
		goto Ins4
	case 5:
		goto Ins5
	case 6:
		goto Ins6
	case 7:
		goto Ins7
	case 8:
		goto Ins8
	case 9:
		goto Ins9
	case 10:
		goto Ins10
	case 11:
		goto Ins11
	case 12:
		goto Ins12
	case 13:
		goto Ins13
	case 14:
		goto Ins14
	case 15:
		goto Ins15
	case 16:
		goto Ins16
	case 17:
		goto Ins17
	case 18:
		goto Ins18
	case 19:
		goto Ins19
	case 20:
		goto Ins20
	case 21:
		goto Ins21
	}
Ins0:
	{
		return nil, false
	}
Ins1:
	{
		captures[2] = offset
		nextInstruction = 2
		goto StepSelect
	}
Ins2:
	{
		if l <= offset || input[offset] == uint8(0xa) {
			goto TryFallback
		}
		offset++
		goto Ins3
	}
Ins3:
	{
		captureStack = append(captureStack, captures[:]...)
		stack = append(stack, [3]int{offset, 4, 1})
		goto Ins2
	}
Ins4:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] < uint8(0x80) {
			if [32]byte{uint8(0xff), uint8(0xc9), uint8(0xff), uint8(0xff), uint8(0xfe), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0)}[input[offset]/8]&(1<<(input[offset]%8)) == 0 {
				goto TryFallback
			}
			offset++
			goto Ins5
		}
		r, width := utf8.DecodeRuneInString(input[offset:])
		if !(r >= int32(0) && r <= int32(8)) && !(r >= int32(11) && r <= int32(11)) && !(r >= int32(14) && r <= int32(31)) && !(r >= int32(33) && r <= int32(1114111)) {
			goto TryFallback
		}
		offset += width
		goto Ins5
	}
Ins5:
	{
		captures[3] = offset
		nextInstruction = 6
		goto StepSelect
	}
Ins6:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] != uint8(0x20) {
			goto TryFallback
		}
		offset++
		goto Ins7
	}
Ins7:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] != uint8(0x63) {
			goto TryFallback
		}
		offset++
		goto Ins8
	}
Ins8:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] != uint8(0x72) {
			goto TryFallback
		}
		offset++
		goto Ins9
	}
Ins9:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] != uint8(0x65) {
			goto TryFallback
		}
		offset++
		goto Ins10
	}
Ins10:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] != uint8(0x61) {
			goto TryFallback
		}
		offset++
		goto Ins11
	}
Ins11:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] != uint8(0x74) {
			goto TryFallback
		}
		offset++
		goto Ins12
	}
Ins12:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] != uint8(0x65) {
			goto TryFallback
		}
		offset++
		goto Ins13
	}
Ins13:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] != uint8(0x73) {
			goto TryFallback
		}
		offset++
		goto Ins14
	}
Ins14:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] != uint8(0x20) {
			goto TryFallback
		}
		offset++
		goto Ins15
	}
Ins15:
	{
		captures[4] = offset
		nextInstruction = 16
		goto StepSelect
	}
Ins16:
	{
		if l <= offset || input[offset] == uint8(0xa) {
			goto TryFallback
		}
		offset++
		goto Ins17
	}
Ins17:
	{
		captureStack = append(captureStack, captures[:]...)
		stack = append(stack, [3]int{offset, 18, 1})
		goto Ins16
	}
Ins18:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] < uint8(0x80) {
			if [32]byte{uint8(0xff), uint8(0xc9), uint8(0xff), uint8(0xff), uint8(0xfe), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0)}[input[offset]/8]&(1<<(input[offset]%8)) == 0 {
				goto TryFallback
			}
			offset++
			goto Ins19
		}
		r, width := utf8.DecodeRuneInString(input[offset:])
		if !(r >= int32(0) && r <= int32(8)) && !(r >= int32(11) && r <= int32(11)) && !(r >= int32(14) && r <= int32(31)) && !(r >= int32(33) && r <= int32(1114111)) {
			goto TryFallback
		}
		offset += width
		goto Ins19
	}
Ins19:
	{
		captures[5] = offset
		nextInstruction = 20
		goto StepSelect
	}
Ins20:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] != uint8(0x2e) {
			goto TryFallback
		}
		offset++
		goto Ins21
	}
Ins21:
	{
		captures[1] = offset
		if r == nil {
			r = &ReCreatesResult{}
		}
		r.Match = string(input[captures[0]:captures[1]])
		if captures[2] <= captures[3] && captures[3] <= len(input) {
			r.Group1 = string(input[captures[2]:captures[3]])
		} else {
			r.Group1 = ""
		}
		if captures[4] <= captures[5] && captures[5] <= len(input) {
			r.Group2 = string(input[captures[4]:captures[5]])
		} else {
			r.Group2 = ""
		}
		return r, true
	}
}
func (recv ReCreates) FindString(input string) (*ReCreatesResult, bool) {
	return recv.FindStringReuse(input, nil)
}
func (ReCreates) FindAllStringAppend(input string, n int, s []*ReCreatesResult) []*ReCreatesResult {
	if n == 0 {
		return s
	}
	result := s
	l := len(input)
	searchStart := 0
	captureStackPtr := reCreatesCaptureStackPool.Get().(*[]int)
	captureStack := (*captureStackPtr)[:0]
	defer func() {
		*captureStackPtr = captureStack[:0]
		reCreatesCaptureStackPool.Put(captureStackPtr)
	}()
	stackPtr := reCreatesStackPool.Get().(*[][3]int)
	stack := (*stackPtr)[:0]
	defer func() {
		for i := range stack {
			stack[i] = [3]int{0, 0, 0}
		}
		*stackPtr = stack[:0]
		reCreatesStackPool.Put(stackPtr)
	}()
	for true {
		if n > 0 && len(result) >= n {
			break
		}
		if searchStart >= l {
			break
		}
		offset := searchStart
		var captures [6]int
		captureStack = captureStack[:0]
		stack = stack[:0]
		captures[0] = searchStart
		nextInstruction := 1
		goto StepSelect
	TryFallback:
		if len(stack) > 0 {
			last := stack[len(stack)-1]
			offset = last[0]
			nextInstruction = last[1]
			stack = stack[:len(stack)-1]
			if last[2] == 1 && len(captureStack) > 0 {
				n := len(captures)
				top := len(captureStack) - n
				copy(captures[:], captureStack[top:])
				captureStack = captureStack[:top]
			}
			goto StepSelect
		} else {
			searchStart++
			continue
		}
	StepSelect:
		switch nextInstruction {
		case 0:
			goto Ins0
		case 1:
			goto Ins1
		case 2:
			goto Ins2
		case 3:
			goto Ins3
		case 4:
			goto Ins4
		case 5:
			goto Ins5
		case 6:
			goto Ins6
		case 7:
			goto Ins7
		case 8:
			goto Ins8
		case 9:
			goto Ins9
		case 10:
			goto Ins10
		case 11:
			goto Ins11
		case 12:
			goto Ins12
		case 13:
			goto Ins13
		case 14:
			goto Ins14
		case 15:
			goto Ins15
		case 16:
			goto Ins16
		case 17:
			goto Ins17
		case 18:
			goto Ins18
		case 19:
			goto Ins19
		case 20:
			goto Ins20
		case 21:
			goto Ins21
		}
	Ins0:
		{
			goto TryFallback
		}
	Ins1:
		{
			captures[2] = offset
			nextInstruction = 2
			goto StepSelect
		}
	Ins2:
		{
			if l <= offset || input[offset] == uint8(0xa) {
				goto TryFallback
			}
			offset++
			goto Ins3
		}
	Ins3:
		{
			captureStack = append(captureStack, captures[:]...)
			stack = append(stack, [3]int{offset, 4, 1})
			goto Ins2
		}
	Ins4:
		{
			if l <= offset {
				goto TryFallback
			}
		}
		{
			if input[offset] < uint8(0x80) {
				if [32]byte{uint8(0xff), uint8(0xc9), uint8(0xff), uint8(0xff), uint8(0xfe), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0)}[input[offset]/8]&(1<<(input[offset]%8)) == 0 {
					goto TryFallback
				}
				offset++
				goto Ins5
			}
			r, width := utf8.DecodeRuneInString(input[offset:])
			if !(r >= int32(0) && r <= int32(8)) && !(r >= int32(11) && r <= int32(11)) && !(r >= int32(14) && r <= int32(31)) && !(r >= int32(33) && r <= int32(1114111)) {
				goto TryFallback
			}
			offset += width
			goto Ins5
		}
	Ins5:
		{
			captures[3] = offset
			nextInstruction = 6
			goto StepSelect
		}
	Ins6:
		{
			if l <= offset {
				goto TryFallback
			}
		}
		{
			if input[offset] != uint8(0x20) {
				goto TryFallback
			}
			offset++
			goto Ins7
		}
	Ins7:
		{
			if l <= offset {
				goto TryFallback
			}
		}
		{
			if input[offset] != uint8(0x63) {
				goto TryFallback
			}
			offset++
			goto Ins8
		}
	Ins8:
		{
			if l <= offset {
				goto TryFallback
			}
		}
		{
			if input[offset] != uint8(0x72) {
				goto TryFallback
			}
			offset++
			goto Ins9
		}
	Ins9:
		{
			if l <= offset {
				goto TryFallback
			}
		}
		{
			if input[offset] != uint8(0x65) {
				goto TryFallback
			}
			offset++
			goto Ins10
		}
	Ins10:
		{
			if l <= offset {
				goto TryFallback
			}
		}
		{
			if input[offset] != uint8(0x61) {
				goto TryFallback
			}
			offset++
			goto Ins11
		}
	Ins11:
		{
			if l <= offset {
				goto TryFallback
			}
		}
		{
			if input[offset] != uint8(0x74) {
				goto TryFallback
			}
			offset++
			goto Ins12
		}
	Ins12:
		{
			if l <= offset {
				goto TryFallback
			}
		}
		{
			if input[offset] != uint8(0x65) {
				goto TryFallback
			}
			offset++
			goto Ins13
		}
	Ins13:
		{
			if l <= offset {
				goto TryFallback
			}
		}
		{
			if input[offset] != uint8(0x73) {
				goto TryFallback
			}
			offset++
			goto Ins14
		}
	Ins14:
		{
			if l <= offset {
				goto TryFallback
			}
		}
		{
			if input[offset] != uint8(0x20) {
				goto TryFallback
			}
			offset++
			goto Ins15
		}
	Ins15:
		{
			captures[4] = offset
			nextInstruction = 16
			goto StepSelect
		}
	Ins16:
		{
			if l <= offset || input[offset] == uint8(0xa) {
				goto TryFallback
			}
			offset++
			goto Ins17
		}
	Ins17:
		{
			captureStack = append(captureStack, captures[:]...)
			stack = append(stack, [3]int{offset, 18, 1})
			goto Ins16
		}
	Ins18:
		{
			if l <= offset {
				goto TryFallback
			}
		}
		{
			if input[offset] < uint8(0x80) {
				if [32]byte{uint8(0xff), uint8(0xc9), uint8(0xff), uint8(0xff), uint8(0xfe), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0)}[input[offset]/8]&(1<<(input[offset]%8)) == 0 {
					goto TryFallback
				}
				offset++
				goto Ins19
			}
			r, width := utf8.DecodeRuneInString(input[offset:])
			if !(r >= int32(0) && r <= int32(8)) && !(r >= int32(11) && r <= int32(11)) && !(r >= int32(14) && r <= int32(31)) && !(r >= int32(33) && r <= int32(1114111)) {
				goto TryFallback
			}
			offset += width
			goto Ins19
		}
	Ins19:
		{
			captures[5] = offset
			nextInstruction = 20
			goto StepSelect
		}
	Ins20:
		{
			if l <= offset {
				goto TryFallback
			}
		}
		{
			if input[offset] != uint8(0x2e) {
				goto TryFallback
			}
			offset++
			goto Ins21
		}
	Ins21:
		{
			captures[1] = offset
			var item *ReCreatesResult
			if len(result) < cap(result) {
				result = result[:len(result)+1]
				item = result[len(result)-1]
				if item == nil {
					item = &ReCreatesResult{}
					result[len(result)-1] = item
				}
			} else {
				item = &ReCreatesResult{}
				result = append(result, item)
			}
			item.Match = string(input[captures[0]:captures[1]])
			if captures[2] <= captures[3] && captures[3] <= len(input) {
				item.Group1 = string(input[captures[2]:captures[3]])
			} else {
				item.Group1 = ""
			}
			if captures[4] <= captures[5] && captures[5] <= len(input) {
				item.Group2 = string(input[captures[4]:captures[5]])
			} else {
				item.Group2 = ""
			}
			if captures[1] > searchStart {
				searchStart = captures[1]
			} else {
				searchStart++
			}
			continue
		}
	}
	return result
}
func (r ReCreates) FindAllString(input string, n int) []*ReCreatesResult {
	return r.FindAllStringAppend(input, n, nil)
}
func (ReCreates) FindBytesReuse(input []byte, r *ReCreatesBytesResult) (*ReCreatesBytesResult, bool) {
	l := len(input)
	offset := 0
	var captures [6]int
	captureStackPtr := reCreatesCaptureStackPool.Get().(*[]int)
	captureStack := (*captureStackPtr)[:0]
	defer func() {
		*captureStackPtr = captureStack[:0]
		reCreatesCaptureStackPool.Put(captureStackPtr)
	}()
	stackPtr := reCreatesStackPool.Get().(*[][3]int)
	stack := (*stackPtr)[:0]
	defer func() {
		for i := range stack {
			stack[i] = [3]int{0, 0, 0}
		}
		*stackPtr = stack[:0]
		reCreatesStackPool.Put(stackPtr)
	}()
	captures[0] = 0
	nextInstruction := 1
	goto StepSelect
TryFallback:
	if len(stack) > 0 {
		last := stack[len(stack)-1]
		offset = last[0]
		nextInstruction = last[1]
		stack = stack[:len(stack)-1]
		if last[2] == 1 && len(captureStack) > 0 {
			n := len(captures)
			top := len(captureStack) - n
			copy(captures[:], captureStack[top:])
			captureStack = captureStack[:top]
		}
		goto StepSelect
	} else {
		if l > offset {
			offset++
			for i := range captures {
				captures[i] = 0
			}
			captureStack = captureStack[:0]
			captures[0] = offset
			nextInstruction = 1
			goto StepSelect
		}
		return nil, false
	}
StepSelect:
	switch nextInstruction {
	case 0:
		goto Ins0
	case 1:
		goto Ins1
	case 2:
		goto Ins2
	case 3:
		goto Ins3
	case 4:
		goto Ins4
	case 5:
		goto Ins5
	case 6:
		goto Ins6
	case 7:
		goto Ins7
	case 8:
		goto Ins8
	case 9:
		goto Ins9
	case 10:
		goto Ins10
	case 11:
		goto Ins11
	case 12:
		goto Ins12
	case 13:
		goto Ins13
	case 14:
		goto Ins14
	case 15:
		goto Ins15
	case 16:
		goto Ins16
	case 17:
		goto Ins17
	case 18:
		goto Ins18
	case 19:
		goto Ins19
	case 20:
		goto Ins20
	case 21:
		goto Ins21
	}
Ins0:
	{
		return nil, false
	}
Ins1:
	{
		captures[2] = offset
		nextInstruction = 2
		goto StepSelect
	}
Ins2:
	{
		if l <= offset || input[offset] == uint8(0xa) {
			goto TryFallback
		}
		offset++
		goto Ins3
	}
Ins3:
	{
		captureStack = append(captureStack, captures[:]...)
		stack = append(stack, [3]int{offset, 4, 1})
		goto Ins2
	}
Ins4:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] < uint8(0x80) {
			if [32]byte{uint8(0xff), uint8(0xc9), uint8(0xff), uint8(0xff), uint8(0xfe), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0)}[input[offset]/8]&(1<<(input[offset]%8)) == 0 {
				goto TryFallback
			}
			offset++
			goto Ins5
		}
		r, width := utf8.DecodeRune(input[offset:])
		if !(r >= int32(0) && r <= int32(8)) && !(r >= int32(11) && r <= int32(11)) && !(r >= int32(14) && r <= int32(31)) && !(r >= int32(33) && r <= int32(1114111)) {
			goto TryFallback
		}
		offset += width
		goto Ins5
	}
Ins5:
	{
		captures[3] = offset
		nextInstruction = 6
		goto StepSelect
	}
Ins6:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] != uint8(0x20) {
			goto TryFallback
		}
		offset++
		goto Ins7
	}
Ins7:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] != uint8(0x63) {
			goto TryFallback
		}
		offset++
		goto Ins8
	}
Ins8:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] != uint8(0x72) {
			goto TryFallback
		}
		offset++
		goto Ins9
	}
Ins9:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] != uint8(0x65) {
			goto TryFallback
		}
		offset++
		goto Ins10
	}
Ins10:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] != uint8(0x61) {
			goto TryFallback
		}
		offset++
		goto Ins11
	}
Ins11:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] != uint8(0x74) {
			goto TryFallback
		}
		offset++
		goto Ins12
	}
Ins12:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] != uint8(0x65) {
			goto TryFallback
		}
		offset++
		goto Ins13
	}
Ins13:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] != uint8(0x73) {
			goto TryFallback
		}
		offset++
		goto Ins14
	}
Ins14:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] != uint8(0x20) {
			goto TryFallback
		}
		offset++
		goto Ins15
	}
Ins15:
	{
		captures[4] = offset
		nextInstruction = 16
		goto StepSelect
	}
Ins16:
	{
		if l <= offset || input[offset] == uint8(0xa) {
			goto TryFallback
		}
		offset++
		goto Ins17
	}
Ins17:
	{
		captureStack = append(captureStack, captures[:]...)
		stack = append(stack, [3]int{offset, 18, 1})
		goto Ins16
	}
Ins18:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] < uint8(0x80) {
			if [32]byte{uint8(0xff), uint8(0xc9), uint8(0xff), uint8(0xff), uint8(0xfe), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0)}[input[offset]/8]&(1<<(input[offset]%8)) == 0 {
				goto TryFallback
			}
			offset++
			goto Ins19
		}
		r, width := utf8.DecodeRune(input[offset:])
		if !(r >= int32(0) && r <= int32(8)) && !(r >= int32(11) && r <= int32(11)) && !(r >= int32(14) && r <= int32(31)) && !(r >= int32(33) && r <= int32(1114111)) {
			goto TryFallback
		}
		offset += width
		goto Ins19
	}
Ins19:
	{
		captures[5] = offset
		nextInstruction = 20
		goto StepSelect
	}
Ins20:
	{
		if l <= offset {
			goto TryFallback
		}
	}
	{
		if input[offset] != uint8(0x2e) {
			goto TryFallback
		}
		offset++
		goto Ins21
	}
Ins21:
	{
		captures[1] = offset
		if r == nil {
			r = &ReCreatesBytesResult{}
		}
		r.Match = input[captures[0]:captures[1]]
		if captures[2] <= captures[3] && captures[3] <= len(input) {
			r.Group1 = input[captures[2]:captures[3]]
		} else {
			r.Group1 = nil
		}
		if captures[4] <= captures[5] && captures[5] <= len(input) {
			r.Group2 = input[captures[4]:captures[5]]
		} else {
			r.Group2 = nil
		}
		return r, true
	}
}
func (recv ReCreates) FindBytes(input []byte) (*ReCreatesBytesResult, bool) {
	return recv.FindBytesReuse(input, nil)
}
func (ReCreates) FindAllBytesAppend(input []byte, n int, s []*ReCreatesBytesResult) []*ReCreatesBytesResult {
	if n == 0 {
		return s
	}
	result := s
	l := len(input)
	searchStart := 0
	captureStackPtr := reCreatesCaptureStackPool.Get().(*[]int)
	captureStack := (*captureStackPtr)[:0]
	defer func() {
		*captureStackPtr = captureStack[:0]
		reCreatesCaptureStackPool.Put(captureStackPtr)
	}()
	stackPtr := reCreatesStackPool.Get().(*[][3]int)
	stack := (*stackPtr)[:0]
	defer func() {
		for i := range stack {
			stack[i] = [3]int{0, 0, 0}
		}
		*stackPtr = stack[:0]
		reCreatesStackPool.Put(stackPtr)
	}()
	for true {
		if n > 0 && len(result) >= n {
			break
		}
		if searchStart >= l {
			break
		}
		offset := searchStart
		var captures [6]int
		captureStack = captureStack[:0]
		stack = stack[:0]
		captures[0] = searchStart
		nextInstruction := 1
		goto StepSelect
	TryFallback:
		if len(stack) > 0 {
			last := stack[len(stack)-1]
			offset = last[0]
			nextInstruction = last[1]
			stack = stack[:len(stack)-1]
			if last[2] == 1 && len(captureStack) > 0 {
				n := len(captures)
				top := len(captureStack) - n
				copy(captures[:], captureStack[top:])
				captureStack = captureStack[:top]
			}
			goto StepSelect
		} else {
			searchStart++
			continue
		}
	StepSelect:
		switch nextInstruction {
		case 0:
			goto Ins0
		case 1:
			goto Ins1
		case 2:
			goto Ins2
		case 3:
			goto Ins3
		case 4:
			goto Ins4
		case 5:
			goto Ins5
		case 6:
			goto Ins6
		case 7:
			goto Ins7
		case 8:
			goto Ins8
		case 9:
			goto Ins9
		case 10:
			goto Ins10
		case 11:
			goto Ins11
		case 12:
			goto Ins12
		case 13:
			goto Ins13
		case 14:
			goto Ins14
		case 15:
			goto Ins15
		case 16:
			goto Ins16
		case 17:
			goto Ins17
		case 18:
			goto Ins18
		case 19:
			goto Ins19
		case 20:
			goto Ins20
		case 21:
			goto Ins21
		}
	Ins0:
		{
			goto TryFallback
		}
	Ins1:
		{
			captures[2] = offset
			nextInstruction = 2
			goto StepSelect
		}
	Ins2:
		{
			if l <= offset || input[offset] == uint8(0xa) {
				goto TryFallback
			}
			offset++
			goto Ins3
		}
	Ins3:
		{
			captureStack = append(captureStack, captures[:]...)
			stack = append(stack, [3]int{offset, 4, 1})
			goto Ins2
		}
	Ins4:
		{
			if l <= offset {
				goto TryFallback
			}
		}
		{
			if input[offset] < uint8(0x80) {
				if [32]byte{uint8(0xff), uint8(0xc9), uint8(0xff), uint8(0xff), uint8(0xfe), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0)}[input[offset]/8]&(1<<(input[offset]%8)) == 0 {
					goto TryFallback
				}
				offset++
				goto Ins5
			}
			r, width := utf8.DecodeRune(input[offset:])
			if !(r >= int32(0) && r <= int32(8)) && !(r >= int32(11) && r <= int32(11)) && !(r >= int32(14) && r <= int32(31)) && !(r >= int32(33) && r <= int32(1114111)) {
				goto TryFallback
			}
			offset += width
			goto Ins5
		}
	Ins5:
		{
			captures[3] = offset
			nextInstruction = 6
			goto StepSelect
		}
	Ins6:
		{
			if l <= offset {
				goto TryFallback
			}
		}
		{
			if input[offset] != uint8(0x20) {
				goto TryFallback
			}
			offset++
			goto Ins7
		}
	Ins7:
		{
			if l <= offset {
				goto TryFallback
			}
		}
		{
			if input[offset] != uint8(0x63) {
				goto TryFallback
			}
			offset++
			goto Ins8
		}
	Ins8:
		{
			if l <= offset {
				goto TryFallback
			}
		}
		{
			if input[offset] != uint8(0x72) {
				goto TryFallback
			}
			offset++
			goto Ins9
		}
	Ins9:
		{
			if l <= offset {
				goto TryFallback
			}
		}
		{
			if input[offset] != uint8(0x65) {
				goto TryFallback
			}
			offset++
			goto Ins10
		}
	Ins10:
		{
			if l <= offset {
				goto TryFallback
			}
		}
		{
			if input[offset] != uint8(0x61) {
				goto TryFallback
			}
			offset++
			goto Ins11
		}
	Ins11:
		{
			if l <= offset {
				goto TryFallback
			}
		}
		{
			if input[offset] != uint8(0x74) {
				goto TryFallback
			}
			offset++
			goto Ins12
		}
	Ins12:
		{
			if l <= offset {
				goto TryFallback
			}
		}
		{
			if input[offset] != uint8(0x65) {
				goto TryFallback
			}
			offset++
			goto Ins13
		}
	Ins13:
		{
			if l <= offset {
				goto TryFallback
			}
		}
		{
			if input[offset] != uint8(0x73) {
				goto TryFallback
			}
			offset++
			goto Ins14
		}
	Ins14:
		{
			if l <= offset {
				goto TryFallback
			}
		}
		{
			if input[offset] != uint8(0x20) {
				goto TryFallback
			}
			offset++
			goto Ins15
		}
	Ins15:
		{
			captures[4] = offset
			nextInstruction = 16
			goto StepSelect
		}
	Ins16:
		{
			if l <= offset || input[offset] == uint8(0xa) {
				goto TryFallback
			}
			offset++
			goto Ins17
		}
	Ins17:
		{
			captureStack = append(captureStack, captures[:]...)
			stack = append(stack, [3]int{offset, 18, 1})
			goto Ins16
		}
	Ins18:
		{
			if l <= offset {
				goto TryFallback
			}
		}
		{
			if input[offset] < uint8(0x80) {
				if [32]byte{uint8(0xff), uint8(0xc9), uint8(0xff), uint8(0xff), uint8(0xfe), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0xff), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0), uint8(0x0)}[input[offset]/8]&(1<<(input[offset]%8)) == 0 {
					goto TryFallback
				}
				offset++
				goto Ins19
			}
			r, width := utf8.DecodeRune(input[offset:])
			if !(r >= int32(0) && r <= int32(8)) && !(r >= int32(11) && r <= int32(11)) && !(r >= int32(14) && r <= int32(31)) && !(r >= int32(33) && r <= int32(1114111)) {
				goto TryFallback
			}
			offset += width
			goto Ins19
		}
	Ins19:
		{
			captures[5] = offset
			nextInstruction = 20
			goto StepSelect
		}
	Ins20:
		{
			if l <= offset {
				goto TryFallback
			}
		}
		{
			if input[offset] != uint8(0x2e) {
				goto TryFallback
			}
			offset++
			goto Ins21
		}
	Ins21:
		{
			captures[1] = offset
			var item *ReCreatesBytesResult
			if len(result) < cap(result) {
				result = result[:len(result)+1]
				item = result[len(result)-1]
				if item == nil {
					item = &ReCreatesBytesResult{}
					result[len(result)-1] = item
				}
			} else {
				item = &ReCreatesBytesResult{}
				result = append(result, item)
			}
			item.Match = input[captures[0]:captures[1]]
			if captures[2] <= captures[3] && captures[3] <= len(input) {
				item.Group1 = input[captures[2]:captures[3]]
			} else {
				item.Group1 = nil
			}
			if captures[4] <= captures[5] && captures[5] <= len(input) {
				item.Group2 = input[captures[4]:captures[5]]
			} else {
				item.Group2 = nil
			}
			if captures[1] > searchStart {
				searchStart = captures[1]
			} else {
				searchStart++
			}
			continue
		}
	}
	return result
}
func (r ReCreates) FindAllBytes(input []byte, n int) []*ReCreatesBytesResult {
	return r.FindAllBytesAppend(input, n, nil)
}

// DefaultMaxLeftover returns the recommended MaxLeftover value for streaming.
// For bounded patterns, this is 10 * MaxMatchLen.
// For unbounded patterns, this returns 1MB as a safety limit.
func (ReCreates) DefaultMaxLeftover() int {
	return 1048576
}

// FindReader streams matches from an io.Reader.
//
// The onMatch callback is called for each match found. Return false to stop
// processing early. The StreamMatch.Result points into an internal buffer
// and is only valid during the callback - copy if needed.
//
// Returns nil on success (including early termination via callback).
// Returns error on read failure.
func (ReCreates) FindReader(r io.Reader, cfg stream.Config, onMatch func(stream.Match[*ReCreatesBytesResult]) bool) error {
	if err := cfg.Validate(65536); err != nil {
		return err
	}
	cfg = cfg.ApplyDefaults(65536, 1048576)

	buf := make([]byte, cfg.BufferSize)
	leftover := 0
	streamOffset := int64(0)
	chunkIndex := 0

	reuseResult := &ReCreatesBytesResult{}

	for {
		n, err := r.Read(buf[leftover:])
		if n == 0 && err != nil {
			if err == io.EOF {
				// Process any remaining data in leftover
				if leftover > 0 {
					chunk := buf[:leftover]
					searchPos := 0
					for searchPos < len(chunk) {
						result, ok := ReCreates{}.FindBytesReuse(chunk[searchPos:], reuseResult)
						if !ok {
							break
						}
						matchIdx := bytes.Index(chunk[searchPos:], result.Match)
						if matchIdx < 0 {
							break
						}
						matchStart := searchPos + matchIdx

						m := stream.Match[*ReCreatesBytesResult]{
							ChunkIndex:   chunkIndex,
							Result:       result,
							StreamOffset: streamOffset + int64(matchStart),
						}
						if !onMatch(m) {
							return nil
						}
						if len(result.Match) > 0 {
							searchPos = matchStart + len(result.Match)
						} else {
							searchPos++
						}
					}
				}
				return nil
			}
			return err
		}

		dataLen := leftover + n
		chunk := buf[:dataLen]
		isFull := n == cfg.BufferSize-leftover

		searchPos := 0
		committed := 0
		for searchPos < len(chunk) {
			result, ok := ReCreates{}.FindBytesReuse(chunk[searchPos:], reuseResult)
			if !ok {
				break
			}
			matchIdx := bytes.Index(chunk[searchPos:], result.Match)
			if matchIdx < 0 {
				break
			}
			matchStart := searchPos + matchIdx
			matchEnd := matchStart + len(result.Match)

			if isFull && matchEnd > dataLen-cfg.MaxLeftover {
				// Match too close to boundary, defer to next chunk
				break
			}

			m := stream.Match[*ReCreatesBytesResult]{
				ChunkIndex:   chunkIndex,
				Result:       result,
				StreamOffset: streamOffset + int64(matchStart),
			}
			if !onMatch(m) {
				return nil
			}
			committed = matchEnd
			if len(result.Match) > 0 {
				searchPos = matchEnd
			} else {
				searchPos++
			}
		}

		// Prepare leftover for next iteration
		if isFull {
			// Buffer was full, need to keep leftover
			keepFrom := dataLen - cfg.MaxLeftover
			if keepFrom < committed {
				keepFrom = committed
			}
			leftover = dataLen - keepFrom
			streamOffset += int64(keepFrom)
			copy(buf[:leftover], buf[keepFrom:dataLen])
		} else {
			// Reached EOF or short read, no more data
			leftover = 0
		}
		chunkIndex++
		if err == io.EOF {
			return nil
		}
	}
}

// FindReaderCount counts matches without allocating result structs.
// More efficient when you only need the count.
func (ReCreates) FindReaderCount(r io.Reader, cfg stream.Config) (int64, error) {
	var count int64
	err := ReCreates{}.FindReader(r, cfg, func(_ stream.Match[*ReCreatesBytesResult]) bool {
		count++
		return true
	})
	return count, err
}

// FindReaderFirst returns the first match, or nil if none found.
// The returned result is a copy (safe to use after call returns).
func (ReCreates) FindReaderFirst(r io.Reader, cfg stream.Config) (*ReCreatesBytesResult, int64, error) {
	var result *ReCreatesBytesResult
	var offset int64
	err := ReCreates{}.FindReader(r, cfg, func(m stream.Match[*ReCreatesBytesResult]) bool {
		// Copy the result since buffer will be reused
		result = ReCreates{}.copyBytesResult(m.Result)
		offset = m.StreamOffset
		return false
	})
	return result, offset, err
}

// copyBytesResult creates a deep copy of a BytesResult.
// This is needed because the original slices point into the stream buffer.
func (ReCreates) copyBytesResult(src *ReCreatesBytesResult) *ReCreatesBytesResult {
	if src == nil {
		return nil
	}
	dst := &ReCreatesBytesResult{}
	// Copy Match slice
	dst.Match = append([]byte{}, src.Match...)
	return dst
}

// NewTransformReader returns an io.Reader that transforms matches in the input stream.
//
// The onMatch callback is called for each match. Use emit to output replacement bytes.
// If emit is not called, the match is dropped (filter behavior).
// Non-matching segments are automatically passed through to output.
//
// Example usage:
//
//	r := pattern.NewTransformReader(input, stream.DefaultTransformConfig(),
//	    func(m *PatternBytesResult, emit func([]byte)) {
//	        emit([]byte("REDACTED"))
//	    })
//	io.Copy(os.Stdout, r)
func (ReCreates) NewTransformReader(r io.Reader, cfg stream.TransformConfig, onMatch func(match *ReCreatesBytesResult, emit func([]byte))) io.Reader {
	if cfg.BufferSize == 0 {
		cfg.BufferSize = 65536
	}
	if cfg.MaxLeftover == 0 {
		cfg.MaxLeftover = 1048576
	}

	processor := func(data []byte, isEOF bool, _ stream.TransformFunc, emitOut func([]byte)) int {
		return ReCreates{}.processTransform(data, isEOF, onMatch, emitOut)
	}

	return stream.NewTransformer(r, cfg, processor, func(_ []byte, emit func([]byte)) {})
}

// processTransform processes data for transformation.
func (ReCreates) processTransform(data []byte, isEOF bool, onMatch func(match *ReCreatesBytesResult, emit func([]byte)), emitOut func([]byte)) int {
	processed := 0
	reuseResult := &ReCreatesBytesResult{}

	for {
		result, ok := ReCreates{}.FindBytesReuse(data[processed:], reuseResult)
		if !ok {
			// No more matches
			if isEOF {
				if processed < len(data) {
					emitOut(data[processed:])
				}
				return len(data)
			}
			// Keep potential partial match data
			safePoint := len(data) - 104857
			if safePoint < processed {
				safePoint = processed
			}
			if safePoint > processed {
				emitOut(data[processed:safePoint])
			}
			return safePoint
		}

		matchIdx := bytes.Index(data[processed:], result.Match)
		if matchIdx < 0 {
			break
		}

		matchStart := processed + matchIdx
		matchEnd := matchStart + len(result.Match)

		if matchStart > processed {
			emitOut(data[processed:matchStart])
		}

		onMatch(result, emitOut)

		if len(result.Match) > 0 {
			processed = matchEnd
		} else {
			processed++
		}
	}
	return processed
}

// ReplaceReader returns an io.Reader that replaces all matches with the template.
//
// Template syntax:
//
//	$0 or ${0}: full match
//	$1, $2, ...: capture group by index
//	$name or ${name}: capture group by name
//	$$: literal dollar sign
//
// Example:
//
//	r := pattern.ReplaceReader(input, "[$1]")
//	io.Copy(os.Stdout, r)
func (ReCreates) ReplaceReader(r io.Reader, template string) io.Reader {
	parsed, err := replace.Parse(template)
	if err != nil {
		return &reCreatesTransformErrReader{err: err}
	}

	captureNames := map[string]int{}
	resolved, err := parsed.ValidateAndResolve(captureNames, 2)
	if err != nil {
		return &reCreatesTransformErrReader{err: err}
	}

	return ReCreates{}.NewTransformReader(r, stream.DefaultTransformConfig(), func(m *ReCreatesBytesResult, emit func([]byte)) {
		result := make([]byte, 0, len(template)+64)
		for _, seg := range resolved {
			switch seg.Type {
			case replace.SegmentLiteral:
				result = append(result, seg.Literal...)
			case replace.SegmentFullMatch:
				result = append(result, m.Match...)
			case replace.SegmentCaptureIndex:
				capture := (ReCreates{}).getCaptureByIndex(m, seg.CaptureIndex)
				if capture != nil {
					result = append(result, capture...)
				}
			}
		}
		emit(result)
	})
}

// reCreatesTransformErrReader is a reader that always returns an error.
type reCreatesTransformErrReader struct {
	err error
}

func (r *reCreatesTransformErrReader) Read(p []byte) (int, error) {
	return 0, r.err
}

// getCaptureByIndex returns the capture group value by its index.
func (ReCreates) getCaptureByIndex(m *ReCreatesBytesResult, index int) []byte {
	switch index {
	case 0:
		return m.Match
	default:
		return nil
	}
}

// SelectReader returns an io.Reader that outputs only matches satisfying the predicate.
// Non-matching segments are dropped. Only matches where pred returns true are output.
//
// Example - extract all email addresses:
//
//	r := emailPattern.SelectReader(input, func(m *EmailBytesResult) bool {
//	    return true // Keep all matches
//	})
func (ReCreates) SelectReader(r io.Reader, pred func(*ReCreatesBytesResult) bool) io.Reader {
	cfg := stream.DefaultTransformConfig()
	cfg.MaxLeftover = 1048576

	processor := func(data []byte, isEOF bool, _ stream.TransformFunc, emitOut func([]byte)) int {
		return ReCreates{}.processSelect(data, isEOF, pred, emitOut)
	}

	return stream.NewTransformer(r, cfg, processor, func(_ []byte, emit func([]byte)) {})
}

// processSelect processes data for select filtering.
func (ReCreates) processSelect(data []byte, isEOF bool, pred func(*ReCreatesBytesResult) bool, emitOut func([]byte)) int {
	processed := 0
	reuseResult := &ReCreatesBytesResult{}

	for {
		result, ok := ReCreates{}.FindBytesReuse(data[processed:], reuseResult)
		if !ok {
			if isEOF {
				return len(data)
			}
			return processed
		}

		matchIdx := bytes.Index(data[processed:], result.Match)
		if matchIdx < 0 {
			break
		}

		matchEnd := processed + matchIdx + len(result.Match)

		if pred(result) {
			emitOut(result.Match)
		}

		if len(result.Match) > 0 {
			processed = matchEnd
		} else {
			processed++
		}
	}
	return processed
}

// RejectReader returns an io.Reader that removes matches satisfying the predicate.
// Non-matching segments pass through. Matches where pred returns true are dropped.
//
// Example - remove all sensitive data:
//
//	r := sensitivePattern.RejectReader(input, func(m *SensitiveBytesResult) bool {
//	    return true // Remove all matches
//	})
func (ReCreates) RejectReader(r io.Reader, pred func(*ReCreatesBytesResult) bool) io.Reader {
	cfg := stream.DefaultTransformConfig()
	cfg.MaxLeftover = 1048576

	processor := func(data []byte, isEOF bool, _ stream.TransformFunc, emitOut func([]byte)) int {
		return ReCreates{}.processReject(data, isEOF, pred, emitOut)
	}

	return stream.NewTransformer(r, cfg, processor, func(_ []byte, emit func([]byte)) {})
}

// processReject processes data for reject filtering.
func (ReCreates) processReject(data []byte, isEOF bool, pred func(*ReCreatesBytesResult) bool, emitOut func([]byte)) int {
	processed := 0
	reuseResult := &ReCreatesBytesResult{}

	for {
		result, ok := ReCreates{}.FindBytesReuse(data[processed:], reuseResult)
		if !ok {
			if isEOF {
				if processed < len(data) {
					emitOut(data[processed:])
				}
				return len(data)
			}
			safePoint := len(data) - 104857
			if safePoint < processed {
				safePoint = processed
			}
			if safePoint > processed {
				emitOut(data[processed:safePoint])
			}
			return safePoint
		}

		matchIdx := bytes.Index(data[processed:], result.Match)
		if matchIdx < 0 {
			break
		}

		matchStart := processed + matchIdx
		matchEnd := matchStart + len(result.Match)

		if matchStart > processed {
			emitOut(data[processed:matchStart])
		}

		if !pred(result) {
			emitOut(result.Match)
		}

		if len(result.Match) > 0 {
			processed = matchEnd
		} else {
			processed++
		}
	}
	return processed
}

// CaptureByIndex returns the capture group value by its 0-based index.
// Index 0 returns the full match, 1+ returns capture groups.
func (r *ReCreatesResult) CaptureByIndex(idx int) string {
	switch idx {
	case 0:
		return r.Match
	case 1:
		return r.Group1
	case 2:
		return r.Group2
	default:
		return ""
	}
}

// CaptureByIndex returns the capture group value by its 0-based index.
// Index 0 returns the full match, 1+ returns capture groups.
func (r *ReCreatesBytesResult) CaptureByIndex(idx int) []byte {
	switch idx {
	case 0:
		return r.Match
	case 1:
		return r.Group1
	case 2:
		return r.Group2
	default:
		return nil
	}
}

// ReplaceAllString replaces all matches in input with the template expansion.
// Template syntax: $0 (full match), $1/$2 (by index), $name (by name), $$ (literal $)
func (ReCreates) ReplaceAllString(input string, template string) string {
	tmpl, err := replace.Parse(template)
	if err != nil {
		panic(fmt.Sprintf("regengo: invalid replace template: %v", err))
	}

	var result strings.Builder
	lastEnd := 0
	var r ReCreatesResult

	remaining := input
	offset := 0

	for {
		match, ok := ReCreates{}.FindStringReuse(remaining, &r)
		if !ok {
			break
		}

		matchIdx := strings.Index(remaining, match.Match)
		if matchIdx < 0 {
			break
		}

		matchStart := offset + matchIdx
		matchEnd := matchStart + len(match.Match)

		result.WriteString(input[lastEnd:matchStart])

		for _, seg := range tmpl.Segments {
			switch seg.Type {
			case replace.SegmentLiteral:
				result.WriteString(seg.Literal)
			case replace.SegmentFullMatch:
				result.WriteString(match.Match)
			case replace.SegmentCaptureIndex:
				result.WriteString(match.CaptureByIndex(seg.CaptureIndex))
			case replace.SegmentCaptureName:
				// No named captures in pattern
			}
		}

		lastEnd = matchEnd
		if len(match.Match) > 0 {
			remaining = input[matchEnd:]
			offset = matchEnd
		} else {
			if matchEnd < len(input) {
				remaining = input[matchEnd+1:]
				offset = matchEnd + 1
			} else {
				break
			}
		}
	}

	result.WriteString(input[lastEnd:])
	return result.String()
}

// ReplaceAllBytes replaces all matches in input with the template expansion.
// Template syntax: $0 (full match), $1/$2 (by index), $name (by name), $$ (literal $)
func (ReCreates) ReplaceAllBytes(input []byte, template string) []byte {
	return ReCreates{}.ReplaceAllBytesAppend(input, template, nil)
}

// ReplaceAllBytesAppend replaces all matches and appends to buf.
// If buf has sufficient capacity, no allocation occurs.
// Template syntax: $0 (full match), $1/$2 (by index), $name (by name), $$ (literal $)
func (ReCreates) ReplaceAllBytesAppend(input []byte, template string, buf []byte) []byte {
	tmpl, err := replace.Parse(template)
	if err != nil {
		panic(fmt.Sprintf("regengo: invalid replace template: %v", err))
	}

	result := buf[:0]
	lastEnd := 0
	var r ReCreatesBytesResult

	remaining := input
	offset := 0

	for {
		match, ok := ReCreates{}.FindBytesReuse(remaining, &r)
		if !ok {
			break
		}

		matchIdx := bytes.Index(remaining, match.Match)
		if matchIdx < 0 {
			break
		}

		matchStart := offset + matchIdx
		matchEnd := matchStart + len(match.Match)

		result = append(result, input[lastEnd:matchStart]...)

		for _, seg := range tmpl.Segments {
			switch seg.Type {
			case replace.SegmentLiteral:
				result = append(result, seg.Literal...)
			case replace.SegmentFullMatch:
				result = append(result, match.Match...)
			case replace.SegmentCaptureIndex:
				result = append(result, match.CaptureByIndex(seg.CaptureIndex)...)
			case replace.SegmentCaptureName:
				// No named captures in pattern
			}
		}

		lastEnd = matchEnd
		if len(match.Match) > 0 {
			remaining = input[matchEnd:]
			offset = matchEnd
		} else {
			if matchEnd < len(input) {
				remaining = input[matchEnd+1:]
				offset = matchEnd + 1
			} else {
				break
			}
		}
	}

	result = append(result, input[lastEnd:]...)
	return result
}

// ReplaceFirstString replaces only the first match in input with the template expansion.
// Template syntax: $0 (full match), $1/$2 (by index), $name (by name), $$ (literal $)
func (ReCreates) ReplaceFirstString(input string, template string) string {
	tmpl, err := replace.Parse(template)
	if err != nil {
		panic(fmt.Sprintf("regengo: invalid replace template: %v", err))
	}

	var r ReCreatesResult
	match, ok := ReCreates{}.FindStringReuse(input, &r)
	if !ok {
		return input
	}

	matchIdx := strings.Index(input, match.Match)
	if matchIdx < 0 {
		return input
	}

	var result strings.Builder
	result.WriteString(input[:matchIdx])

	for _, seg := range tmpl.Segments {
		switch seg.Type {
		case replace.SegmentLiteral:
			result.WriteString(seg.Literal)
		case replace.SegmentFullMatch:
			result.WriteString(match.Match)
		case replace.SegmentCaptureIndex:
			result.WriteString(match.CaptureByIndex(seg.CaptureIndex))
		case replace.SegmentCaptureName:
			// No named captures in pattern
		}
	}

	result.WriteString(input[matchIdx+len(match.Match):])
	return result.String()
}

// ReplaceFirstBytes replaces only the first match in input with the template expansion.
// Template syntax: $0 (full match), $1/$2 (by index), $name (by name), $$ (literal $)
func (ReCreates) ReplaceFirstBytes(input []byte, template string) []byte {
	tmpl, err := replace.Parse(template)
	if err != nil {
		panic(fmt.Sprintf("regengo: invalid replace template: %v", err))
	}

	var r ReCreatesBytesResult
	match, ok := ReCreates{}.FindBytesReuse(input, &r)
	if !ok {
		return append([]byte{}, input...)
	}

	matchIdx := bytes.Index(input, match.Match)
	if matchIdx < 0 {
		return append([]byte{}, input...)
	}

	var result []byte
	result = append(result, input[:matchIdx]...)

	for _, seg := range tmpl.Segments {
		switch seg.Type {
		case replace.SegmentLiteral:
			result = append(result, seg.Literal...)
		case replace.SegmentFullMatch:
			result = append(result, match.Match...)
		case replace.SegmentCaptureIndex:
			result = append(result, match.CaptureByIndex(seg.CaptureIndex)...)
		case replace.SegmentCaptureName:
			// No named captures in pattern
		}
	}

	result = append(result, input[matchIdx+len(match.Match):]...)
	return result
}

// ReCreatesReplaceTemplate holds a pre-compiled replace template for the ReCreates pattern.
// Use CompileReplaceTemplate to create one, then call its Replace methods.
type ReCreatesReplaceTemplate struct {
	original string
	segments []replace.Segment
}

// CompileReplaceTemplate parses and validates a replace template.
// Returns an error if the template syntax is invalid or references non-existent captures.
// The compiled template can be reused for multiple replacements without re-parsing.
//
// Template syntax: $0 (full match), $1/$2 (by index), $name (by name), $$ (literal $)
func (ReCreates) CompileReplaceTemplate(template string) (*ReCreatesReplaceTemplate, error) {
	tmpl, err := replace.Parse(template)
	if err != nil {
		return nil, err
	}

	captureNames := map[string]int{}

	resolved, err := tmpl.ValidateAndResolve(captureNames, 2)
	if err != nil {
		return nil, err
	}

	return &ReCreatesReplaceTemplate{
		original: template,
		segments: resolved,
	}, nil
}

// String returns the original template string.
func (t *ReCreatesReplaceTemplate) String() string {
	return t.original
}

// ReplaceAllString replaces all matches in input using this compiled template.
func (t *ReCreatesReplaceTemplate) ReplaceAllString(input string) string {
	var result strings.Builder
	lastEnd := 0
	var r ReCreatesResult

	remaining := input
	offset := 0

	for {
		match, ok := ReCreates{}.FindStringReuse(remaining, &r)
		if !ok {
			break
		}

		matchIdx := strings.Index(remaining, match.Match)
		if matchIdx < 0 {
			break
		}

		absMatchStart := offset + matchIdx
		absMatchEnd := absMatchStart + len(match.Match)

		result.WriteString(input[lastEnd:absMatchStart])

		for _, seg := range t.segments {
			switch seg.Type {
			case replace.SegmentLiteral:
				result.WriteString(seg.Literal)
			case replace.SegmentFullMatch:
				result.WriteString(match.Match)
			case replace.SegmentCaptureIndex:
				result.WriteString(match.CaptureByIndex(seg.CaptureIndex))
			}
		}

		lastEnd = absMatchEnd
		remaining = input[absMatchEnd:]
		offset = absMatchEnd
	}

	result.WriteString(input[lastEnd:])
	return result.String()
}

// ReplaceAllBytes replaces all matches in input using this compiled template.
func (t *ReCreatesReplaceTemplate) ReplaceAllBytes(input []byte) []byte {
	return t.ReplaceAllBytesAppend(input, nil)
}

// ReplaceAllBytesAppend replaces all matches and appends to buf.
// If buf has sufficient capacity, no allocation occurs.
func (t *ReCreatesReplaceTemplate) ReplaceAllBytesAppend(input []byte, buf []byte) []byte {
	result := buf[:0]
	lastEnd := 0
	var r ReCreatesBytesResult

	remaining := input
	offset := 0

	for {
		match, ok := ReCreates{}.FindBytesReuse(remaining, &r)
		if !ok {
			break
		}

		matchIdx := bytes.Index(remaining, match.Match)
		if matchIdx < 0 {
			break
		}

		absMatchStart := offset + matchIdx
		absMatchEnd := absMatchStart + len(match.Match)

		result = append(result, input[lastEnd:absMatchStart]...)

		for _, seg := range t.segments {
			switch seg.Type {
			case replace.SegmentLiteral:
				result = append(result, seg.Literal...)
			case replace.SegmentFullMatch:
				result = append(result, match.Match...)
			case replace.SegmentCaptureIndex:
				result = append(result, match.CaptureByIndex(seg.CaptureIndex)...)
			}
		}

		lastEnd = absMatchEnd
		remaining = input[absMatchEnd:]
		offset = absMatchEnd
	}

	result = append(result, input[lastEnd:]...)
	return result
}

// ReplaceFirstString replaces only the first match using this compiled template.
func (t *ReCreatesReplaceTemplate) ReplaceFirstString(input string) string {
	var r ReCreatesResult
	match, ok := ReCreates{}.FindStringReuse(input, &r)
	if !ok {
		return input
	}

	matchIdx := strings.Index(input, match.Match)
	if matchIdx < 0 {
		return input
	}

	var result strings.Builder
	result.WriteString(input[:matchIdx])

	for _, seg := range t.segments {
		switch seg.Type {
		case replace.SegmentLiteral:
			result.WriteString(seg.Literal)
		case replace.SegmentFullMatch:
			result.WriteString(match.Match)
		case replace.SegmentCaptureIndex:
			result.WriteString(match.CaptureByIndex(seg.CaptureIndex))
		}
	}

	result.WriteString(input[matchIdx+len(match.Match):])
	return result.String()
}

// ReplaceFirstBytes replaces only the first match using this compiled template.
func (t *ReCreatesReplaceTemplate) ReplaceFirstBytes(input []byte) []byte {
	var r ReCreatesBytesResult
	match, ok := ReCreates{}.FindBytesReuse(input, &r)
	if !ok {
		return append([]byte{}, input...)
	}

	matchIdx := bytes.Index(input, match.Match)
	if matchIdx < 0 {
		return append([]byte{}, input...)
	}

	var result []byte
	result = append(result, input[:matchIdx]...)

	for _, seg := range t.segments {
		switch seg.Type {
		case replace.SegmentLiteral:
			result = append(result, seg.Literal...)
		case replace.SegmentFullMatch:
			result = append(result, match.Match...)
		case replace.SegmentCaptureIndex:
			result = append(result, match.CaptureByIndex(seg.CaptureIndex)...)
		}
	}

	result = append(result, input[matchIdx+len(match.Match):]...)
	return result
}
