ALTER DEFAULT PRIVILEGES IN SCHEMA public
  REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM chronicle;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  REVOKE USAGE, SELECT ON SEQUENCES FROM chronicle;

REVOKE ALL ON ALL TABLES IN SCHEMA public FROM chronicle;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM chronicle;
REVOKE USAGE ON SCHEMA public FROM chronicle;

DROP ROLE IF EXISTS chronicle;
