// Code generated by "stringer -type ArmorSubclass -trimprefix=ArmorSubclass"; DO NOT EDIT.

package chrondbc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ArmorSubclassMisc-1]
	_ = x[ArmorSubclassCloth-2]
	_ = x[ArmorSubclassLeather-4]
	_ = x[ArmorSubclassMail-8]
	_ = x[ArmorSubclassPlate-16]
	_ = x[ArmorSubclassBuckler-32]
	_ = x[ArmorSubclassShield-64]
	_ = x[ArmorSubclassLibram-128]
	_ = x[ArmorSubclassIdol-256]
	_ = x[ArmorSubclassTotem-512]
}

const (
	_ArmorSubclass_name_0 = "MiscCloth"
	_ArmorSubclass_name_1 = "Leather"
	_ArmorSubclass_name_2 = "Mail"
	_ArmorSubclass_name_3 = "Plate"
	_ArmorSubclass_name_4 = "Buckler"
	_ArmorSubclass_name_5 = "Shield"
	_ArmorSubclass_name_6 = "Libram"
	_ArmorSubclass_name_7 = "Idol"
	_ArmorSubclass_name_8 = "Totem"
)

var (
	_ArmorSubclass_index_0 = [...]uint8{0, 4, 9}
)

func (i ArmorSubclass) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _ArmorSubclass_name_0[_ArmorSubclass_index_0[i]:_ArmorSubclass_index_0[i+1]]
	case i == 4:
		return _ArmorSubclass_name_1
	case i == 8:
		return _ArmorSubclass_name_2
	case i == 16:
		return _ArmorSubclass_name_3
	case i == 32:
		return _ArmorSubclass_name_4
	case i == 64:
		return _ArmorSubclass_name_5
	case i == 128:
		return _ArmorSubclass_name_6
	case i == 256:
		return _ArmorSubclass_name_7
	case i == 512:
		return _ArmorSubclass_name_8
	default:
		return "ArmorSubclass(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
