// Code generated by "stringer -type AuraState -trimprefix AuraState"; DO NOT EDIT.

package chrondbc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AuraStateNone-0]
	_ = x[AuraStateDefense-1]
	_ = x[AuraStateHealthLess20Pct-2]
	_ = x[AuraStateBerserking-3]
	_ = x[AuraStateJudgement-5]
	_ = x[AuraStateHunterParry-7]
	_ = x[AuraStateRogue-10]
	_ = x[AuraStateDruidCatForm-11]
	_ = x[AuraStateWarriorVictoryRush-12]
	_ = x[AuraStateCritical-13]
	_ = x[AuraStateRecentlyBandaged-14]
	_ = x[AuraStateHealthLess35Pct-16]
	_ = x[AuraStateImmolate-17]
	_ = x[AuraStateDodged-18]
	_ = x[AuraStateBlocked-19]
	_ = x[AuraStateFrozen-21]
	_ = x[AuraStateStealthInvis-23]
}

const (
	_AuraState_name_0 = "NoneDefenseHealthLess20PctBerserking"
	_AuraState_name_1 = "Judgement"
	_AuraState_name_2 = "HunterParry"
	_AuraState_name_3 = "RogueDruidCatFormWarriorVictoryRushCriticalRecentlyBandaged"
	_AuraState_name_4 = "HealthLess35PctImmolateDodgedBlocked"
	_AuraState_name_5 = "Frozen"
	_AuraState_name_6 = "StealthInvis"
)

var (
	_AuraState_index_0 = [...]uint8{0, 4, 11, 26, 36}
	_AuraState_index_3 = [...]uint8{0, 5, 17, 35, 43, 59}
	_AuraState_index_4 = [...]uint8{0, 15, 23, 29, 36}
)

func (i AuraState) String() string {
	switch {
	case 0 <= i && i <= 3:
		return _AuraState_name_0[_AuraState_index_0[i]:_AuraState_index_0[i+1]]
	case i == 5:
		return _AuraState_name_1
	case i == 7:
		return _AuraState_name_2
	case 10 <= i && i <= 14:
		i -= 10
		return _AuraState_name_3[_AuraState_index_3[i]:_AuraState_index_3[i+1]]
	case 16 <= i && i <= 19:
		i -= 16
		return _AuraState_name_4[_AuraState_index_4[i]:_AuraState_index_4[i+1]]
	case i == 21:
		return _AuraState_name_5
	case i == 23:
		return _AuraState_name_6
	default:
		return "AuraState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
