// Code generated by "stringer -type DefenseType -trimprefix DefenseType"; DO NOT EDIT.

package chrondbc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DefenseTypeNone-0]
	_ = x[DefenseTypeMagic-1]
	_ = x[DefenseTypeMelee-2]
	_ = x[DefenseTypeRanged-3]
}

const _DefenseType_name = "NoneMagicMeleeRanged"

var _DefenseType_index = [...]uint8{0, 4, 9, 14, 20}

func (i DefenseType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_DefenseType_index)-1 {
		return "DefenseType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DefenseType_name[_DefenseType_index[idx]:_DefenseType_index[idx+1]]
}
