// Code generated by "stringer -type DispelType -trimprefix=DispelType"; DO NOT EDIT.

package chrondbc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DispelTypeNone-0]
	_ = x[DispelTypeMagic-1]
	_ = x[DispelTypeCurse-2]
	_ = x[DispelTypeDisease-3]
	_ = x[DispelTypePoison-4]
	_ = x[DispelTypeStealth-5]
	_ = x[DispelTypeInvisibility-6]
}

const _DispelType_name = "NoneMagicCurseDiseasePoisonStealthInvisibility"

var _DispelType_index = [...]uint8{0, 4, 9, 14, 21, 27, 34, 46}

func (i DispelType) String() string {
	if i < 0 || i >= DispelType(len(_DispelType_index)-1) {
		return "DispelType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DispelType_name[_DispelType_index[i]:_DispelType_index[i+1]]
}
