// Code generated by "stringer -type EquippedItemInvTypes -trimprefix=EquippedItemInvTypes"; DO NOT EDIT.

package chrondbc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InvTypeHead-1]
	_ = x[InvTypeNeck-2]
	_ = x[InvTypeShoulder-4]
	_ = x[InvTypeBody-8]
	_ = x[InvTypeChest-16]
	_ = x[InvTypeWaist-32]
	_ = x[InvTypeLegs-64]
	_ = x[InvTypeFeet-128]
	_ = x[InvTypeWrists-256]
	_ = x[InvTypeHands-512]
	_ = x[InvTypeFinger-1024]
	_ = x[InvTypeTrinket-2048]
	_ = x[InvTypeOneHand-4096]
	_ = x[InvTypeShield-8192]
	_ = x[InvTypeRanged-16384]
	_ = x[InvTypeBack-32768]
	_ = x[InvTypeTwoHand-65536]
	_ = x[InvTypeBag-131072]
	_ = x[InvTypeTabard-262144]
	_ = x[InvTypeRobe-524288]
	_ = x[InvTypeMainHand-1048576]
	_ = x[InvTypeOffHand-2097152]
	_ = x[InvTypeHoldable-4194304]
	_ = x[InvTypeAmmo-8388608]
	_ = x[InvTypeThrown-16777216]
	_ = x[InvTypeRangedRight-33554432]
	_ = x[InvType_END-67108864]
}

const _EquippedItemInvTypes_name = "InvTypeHeadInvTypeNeckInvTypeShoulderInvTypeBodyInvTypeChestInvTypeWaistInvTypeLegsInvTypeFeetInvTypeWristsInvTypeHandsInvTypeFingerInvTypeTrinketInvTypeOneHandInvTypeShieldInvTypeRangedInvTypeBackInvTypeTwoHandInvTypeBagInvTypeTabardInvTypeRobeInvTypeMainHandInvTypeOffHandInvTypeHoldableInvTypeAmmoInvTypeThrownInvTypeRangedRightInvType_END"

var _EquippedItemInvTypes_map = map[EquippedItemInvTypes]string{
	1:        _EquippedItemInvTypes_name[0:11],
	2:        _EquippedItemInvTypes_name[11:22],
	4:        _EquippedItemInvTypes_name[22:37],
	8:        _EquippedItemInvTypes_name[37:48],
	16:       _EquippedItemInvTypes_name[48:60],
	32:       _EquippedItemInvTypes_name[60:72],
	64:       _EquippedItemInvTypes_name[72:83],
	128:      _EquippedItemInvTypes_name[83:94],
	256:      _EquippedItemInvTypes_name[94:107],
	512:      _EquippedItemInvTypes_name[107:119],
	1024:     _EquippedItemInvTypes_name[119:132],
	2048:     _EquippedItemInvTypes_name[132:146],
	4096:     _EquippedItemInvTypes_name[146:160],
	8192:     _EquippedItemInvTypes_name[160:173],
	16384:    _EquippedItemInvTypes_name[173:186],
	32768:    _EquippedItemInvTypes_name[186:197],
	65536:    _EquippedItemInvTypes_name[197:211],
	131072:   _EquippedItemInvTypes_name[211:221],
	262144:   _EquippedItemInvTypes_name[221:234],
	524288:   _EquippedItemInvTypes_name[234:245],
	1048576:  _EquippedItemInvTypes_name[245:260],
	2097152:  _EquippedItemInvTypes_name[260:274],
	4194304:  _EquippedItemInvTypes_name[274:289],
	8388608:  _EquippedItemInvTypes_name[289:300],
	16777216: _EquippedItemInvTypes_name[300:313],
	33554432: _EquippedItemInvTypes_name[313:331],
	67108864: _EquippedItemInvTypes_name[331:342],
}

func (i EquippedItemInvTypes) String() string {
	if str, ok := _EquippedItemInvTypes_map[i]; ok {
		return str
	}
	return "EquippedItemInvTypes(" + strconv.FormatInt(int64(i), 10) + ")"
}
