// Code generated by "stringer -type EquippedItemClass -trimprefix=EquippedItemClass"; DO NOT EDIT.

package chrondbc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ItemClassConsumable-0]
	_ = x[ItemClassContainer-1]
	_ = x[ItemClassWeapon-2]
	_ = x[ItemClassGem-3]
	_ = x[ItemClassArmor-4]
	_ = x[ItemClassReagent-5]
	_ = x[ItemClassProjectile-6]
	_ = x[ItemClassTradeGoods-7]
	_ = x[ItemClassGeneric-8]
	_ = x[ItemClassRecipe-9]
	_ = x[ItemClassMoney-10]
	_ = x[ItemClassQuiver-11]
	_ = x[ItemClassQuest-12]
	_ = x[ItemClassKey-13]
	_ = x[ItemClassPermanent-14]
	_ = x[ItemClassMiscellaneous-15]
	_ = x[ItemClassGlyph-16]
}

const _EquippedItemClass_name = "ItemClassConsumableItemClassContainerItemClassWeaponItemClassGemItemClassArmorItemClassReagentItemClassProjectileItemClassTradeGoodsItemClassGenericItemClassRecipeItemClassMoneyItemClassQuiverItemClassQuestItemClassKeyItemClassPermanentItemClassMiscellaneousItemClassGlyph"

var _EquippedItemClass_index = [...]uint16{0, 19, 37, 52, 64, 78, 94, 113, 132, 148, 163, 177, 192, 206, 218, 236, 258, 272}

func (i EquippedItemClass) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_EquippedItemClass_index)-1 {
		return "EquippedItemClass(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EquippedItemClass_name[_EquippedItemClass_index[idx]:_EquippedItemClass_index[idx+1]]
}
