// Code generated by "stringer -type ImplicitTarget -trimprefix ImplicitTarget"; DO NOT EDIT.

package chrondbc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ImplicitTargetNone-0]
	_ = x[ImplicitTargetUnitCaster-1]
	_ = x[ImplicitTargetUnitNearbyEnemy-2]
	_ = x[ImplicitTargetUnitNearbyParty-3]
	_ = x[ImplicitTargetUnitNearbyAlly-4]
	_ = x[ImplicitTargetUnitPet-5]
	_ = x[ImplicitTargetUnitTargetEnemy-6]
	_ = x[ImplicitTargetUnitSrcAreaEntry-7]
	_ = x[ImplicitTargetUnitDestAreaEntry-8]
	_ = x[ImplicitTargetDestHome-9]
	_ = x[ImplicitTargetUnitSrcAreaUnk11-11]
	_ = x[ImplicitTargetUnitSrcAreaEnemy-15]
	_ = x[ImplicitTargetUnitDestAreaEnemy-16]
	_ = x[ImplicitTargetDestDB-17]
	_ = x[ImplicitTargetDestCaster-18]
	_ = x[ImplicitTargetUnitCasterAreaParty-20]
	_ = x[ImplicitTargetUnitTargetAlly-21]
	_ = x[ImplicitTargetSrcCaster-22]
	_ = x[ImplicitTargetGameobjectTarget-23]
	_ = x[ImplicitTargetUnitConeEnemy-24]
	_ = x[ImplicitTargetUnitTargetAny-25]
	_ = x[ImplicitTargetGameobjectItemTarget-26]
	_ = x[ImplicitTargetUnitMaster-27]
	_ = x[ImplicitTargetDestDynobjEnemy-28]
	_ = x[ImplicitTargetDestDynobjAlly-29]
	_ = x[ImplicitTargetUnitSrcAreaAlly-30]
	_ = x[ImplicitTargetUnitDestAreaAlly-31]
	_ = x[ImplicitTargetDestCasterSummon-32]
	_ = x[ImplicitTargetUnitSrcAreaParty-33]
	_ = x[ImplicitTargetUnitDestAreaParty-34]
	_ = x[ImplicitTargetUnitTargetParty-35]
	_ = x[ImplicitTargetDestCasterUnk36-36]
	_ = x[ImplicitTargetUnitLastTargetAreaParty-37]
	_ = x[ImplicitTargetUnitNearbyEntry-38]
	_ = x[ImplicitTargetDestCasterFrontLeft-39]
	_ = x[ImplicitTargetDestCasterBackLeft-40]
	_ = x[ImplicitTargetDestCasterBackRight-41]
	_ = x[ImplicitTargetDestCasterFrontRight-42]
	_ = x[ImplicitTargetUnitChainhealAlly-45]
	_ = x[ImplicitTargetDestNearbyEntry-46]
	_ = x[ImplicitTargetDestCasterFront-47]
	_ = x[ImplicitTargetDestCasterBack-48]
	_ = x[ImplicitTargetDestCasterRight-49]
	_ = x[ImplicitTargetDestCasterLeft-50]
	_ = x[ImplicitTargetGameobjectSrcArea-51]
	_ = x[ImplicitTargetGameobjectDestArea-52]
	_ = x[ImplicitTargetDestTargetEnemy-53]
	_ = x[ImplicitTargetUnitConeCasterToDestEnemy-54]
	_ = x[ImplicitTargetDestCasterFrontLeap-55]
	_ = x[ImplicitTargetUnitCasterAreaRaid-56]
	_ = x[ImplicitTargetUnitTargetRaid-57]
	_ = x[ImplicitTargetUnitNearbyRaid-58]
	_ = x[ImplicitTargetUnitConeCasterToDestAlly-59]
	_ = x[ImplicitTargetUnitDestAreaRaidClass-60]
	_ = x[ImplicitTargetDestCasterMovementDir-61]
	_ = x[ImplicitTargetCorpseEnemy-64]
	_ = x[ImplicitTargetUnitDestAreaEnemySrc-65]
	_ = x[ImplicitTargetUnitDestAreaEnemyDst-66]
	_ = x[ImplicitTargetDestCasterRandom-72]
	_ = x[ImplicitTargetDestCasterRadius-73]
	_ = x[ImplicitTargetDestTargetRandom-74]
	_ = x[ImplicitTargetDestTargetRadius-75]
	_ = x[ImplicitTargetDestChannelTarget-77]
	_ = x[ImplicitTargetUnitChannelTarget-78]
	_ = x[ImplicitTargetDestDestFront-79]
	_ = x[ImplicitTargetDestDestBack-80]
	_ = x[ImplicitTargetDestDestRight-81]
	_ = x[ImplicitTargetDestDestLeft-82]
	_ = x[ImplicitTargetCorpseSrcAreaEnemy-87]
	_ = x[ImplicitTargetUnitVehicle-94]
	_ = x[ImplicitTargetUnitTargetPassenger-95]
}

const (
	_ImplicitTarget_name_0 = "NoneUnitCasterUnitNearbyEnemyUnitNearbyPartyUnitNearbyAllyUnitPetUnitTargetEnemyUnitSrcAreaEntryUnitDestAreaEntryDestHome"
	_ImplicitTarget_name_1 = "UnitSrcAreaUnk11"
	_ImplicitTarget_name_2 = "UnitSrcAreaEnemyUnitDestAreaEnemyDestDBDestCaster"
	_ImplicitTarget_name_3 = "UnitCasterAreaPartyUnitTargetAllySrcCasterGameobjectTargetUnitConeEnemyUnitTargetAnyGameobjectItemTargetUnitMasterDestDynobjEnemyDestDynobjAllyUnitSrcAreaAllyUnitDestAreaAllyDestCasterSummonUnitSrcAreaPartyUnitDestAreaPartyUnitTargetPartyDestCasterUnk36UnitLastTargetAreaPartyUnitNearbyEntryDestCasterFrontLeftDestCasterBackLeftDestCasterBackRightDestCasterFrontRight"
	_ImplicitTarget_name_4 = "UnitChainhealAllyDestNearbyEntryDestCasterFrontDestCasterBackDestCasterRightDestCasterLeftGameobjectSrcAreaGameobjectDestAreaDestTargetEnemyUnitConeCasterToDestEnemyDestCasterFrontLeapUnitCasterAreaRaidUnitTargetRaidUnitNearbyRaidUnitConeCasterToDestAllyUnitDestAreaRaidClassDestCasterMovementDir"
	_ImplicitTarget_name_5 = "CorpseEnemyUnitDestAreaEnemySrcUnitDestAreaEnemyDst"
	_ImplicitTarget_name_6 = "DestCasterRandomDestCasterRadiusDestTargetRandomDestTargetRadius"
	_ImplicitTarget_name_7 = "DestChannelTargetUnitChannelTargetDestDestFrontDestDestBackDestDestRightDestDestLeft"
	_ImplicitTarget_name_8 = "CorpseSrcAreaEnemy"
	_ImplicitTarget_name_9 = "UnitVehicleUnitTargetPassenger"
)

var (
	_ImplicitTarget_index_0 = [...]uint8{0, 4, 14, 29, 44, 58, 65, 80, 96, 113, 121}
	_ImplicitTarget_index_2 = [...]uint8{0, 16, 33, 39, 49}
	_ImplicitTarget_index_3 = [...]uint16{0, 19, 33, 42, 58, 71, 84, 104, 114, 129, 143, 158, 174, 190, 206, 223, 238, 253, 276, 291, 310, 328, 347, 367}
	_ImplicitTarget_index_4 = [...]uint16{0, 17, 32, 47, 61, 76, 90, 107, 125, 140, 165, 184, 202, 216, 230, 254, 275, 296}
	_ImplicitTarget_index_5 = [...]uint8{0, 11, 31, 51}
	_ImplicitTarget_index_6 = [...]uint8{0, 16, 32, 48, 64}
	_ImplicitTarget_index_7 = [...]uint8{0, 17, 34, 47, 59, 72, 84}
	_ImplicitTarget_index_9 = [...]uint8{0, 11, 30}
)

func (i ImplicitTarget) String() string {
	switch {
	case 0 <= i && i <= 9:
		return _ImplicitTarget_name_0[_ImplicitTarget_index_0[i]:_ImplicitTarget_index_0[i+1]]
	case i == 11:
		return _ImplicitTarget_name_1
	case 15 <= i && i <= 18:
		i -= 15
		return _ImplicitTarget_name_2[_ImplicitTarget_index_2[i]:_ImplicitTarget_index_2[i+1]]
	case 20 <= i && i <= 42:
		i -= 20
		return _ImplicitTarget_name_3[_ImplicitTarget_index_3[i]:_ImplicitTarget_index_3[i+1]]
	case 45 <= i && i <= 61:
		i -= 45
		return _ImplicitTarget_name_4[_ImplicitTarget_index_4[i]:_ImplicitTarget_index_4[i+1]]
	case 64 <= i && i <= 66:
		i -= 64
		return _ImplicitTarget_name_5[_ImplicitTarget_index_5[i]:_ImplicitTarget_index_5[i+1]]
	case 72 <= i && i <= 75:
		i -= 72
		return _ImplicitTarget_name_6[_ImplicitTarget_index_6[i]:_ImplicitTarget_index_6[i+1]]
	case 77 <= i && i <= 82:
		i -= 77
		return _ImplicitTarget_name_7[_ImplicitTarget_index_7[i]:_ImplicitTarget_index_7[i+1]]
	case i == 87:
		return _ImplicitTarget_name_8
	case 94 <= i && i <= 95:
		i -= 94
		return _ImplicitTarget_name_9[_ImplicitTarget_index_9[i]:_ImplicitTarget_index_9[i+1]]
	default:
		return "ImplicitTarget(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
