// Code generated by "stringer -type InterruptFlags -trimprefix=InterruptFlags"; DO NOT EDIT.

package chrondbc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InterruptFlagMovement-1]
	_ = x[InterruptFlagPushback-2]
	_ = x[InterruptFlagInterrupt-4]
	_ = x[InterruptFlagAutoAttack-8]
	_ = x[InterruptFlagDamage-16]
	_ = x[InterruptFlag_END-32]
}

const (
	_InterruptFlags_name_0 = "InterruptFlagMovementInterruptFlagPushback"
	_InterruptFlags_name_1 = "InterruptFlagInterrupt"
	_InterruptFlags_name_2 = "InterruptFlagAutoAttack"
	_InterruptFlags_name_3 = "InterruptFlagDamage"
	_InterruptFlags_name_4 = "InterruptFlag_END"
)

var (
	_InterruptFlags_index_0 = [...]uint8{0, 21, 42}
)

func (i InterruptFlags) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _InterruptFlags_name_0[_InterruptFlags_index_0[i]:_InterruptFlags_index_0[i+1]]
	case i == 4:
		return _InterruptFlags_name_1
	case i == 8:
		return _InterruptFlags_name_2
	case i == 16:
		return _InterruptFlags_name_3
	case i == 32:
		return _InterruptFlags_name_4
	default:
		return "InterruptFlags(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
