// Code generated by "stringer -type Mechanic -trimprefix Mechanic"; DO NOT EDIT.

package chrondbc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MechanicNone-0]
	_ = x[MechanicCharm-1]
	_ = x[MechanicDisoriented-2]
	_ = x[MechanicDisarm-3]
	_ = x[MechanicDistract-4]
	_ = x[MechanicFlee-5]
	_ = x[MechanicGrip-6]
	_ = x[MechanicRoot-7]
	_ = x[MechanicSlow-8]
	_ = x[MechanicSilence-9]
	_ = x[MechanicSleep-10]
	_ = x[MechanicSnare-11]
	_ = x[MechanicStun-12]
	_ = x[MechanicFreeze-13]
	_ = x[MechanicKnockout-14]
	_ = x[MechanicBleed-15]
	_ = x[MechanicBandage-16]
	_ = x[MechanicPolymorph-17]
	_ = x[MechanicBanish-18]
	_ = x[MechanicShield-19]
	_ = x[MechanicShackle-20]
	_ = x[MechanicMount-21]
	_ = x[MechanicInfected-22]
	_ = x[MechanicTurn-23]
	_ = x[MechanicHorror-24]
	_ = x[MechanicInvulnerable-25]
	_ = x[MechanicInterrupt-26]
	_ = x[MechanicDaze-27]
	_ = x[MechanicDiscovery-28]
	_ = x[MechanicImmuneShield-29]
	_ = x[MechanicSapped-30]
	_ = x[MechanicEnraged-31]
}

const _Mechanic_name = "NoneCharmDisorientedDisarmDistractFleeGripRootSlowSilenceSleepSnareStunFreezeKnockoutBleedBandagePolymorphBanishShieldShackleMountInfectedTurnHorrorInvulnerableInterruptDazeDiscoveryImmuneShieldSappedEnraged"

var _Mechanic_index = [...]uint8{0, 4, 9, 20, 26, 34, 38, 42, 46, 50, 57, 62, 67, 71, 77, 85, 90, 97, 106, 112, 118, 125, 130, 138, 142, 148, 160, 169, 173, 182, 194, 200, 207}

func (i Mechanic) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Mechanic_index)-1 {
		return "Mechanic(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Mechanic_name[_Mechanic_index[idx]:_Mechanic_index[idx+1]]
}
