// Code generated by "stringer -type Power -trimprefix=Power"; DO NOT EDIT.

package chrondbc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PowerMana-0]
	_ = x[PowerRage-1]
	_ = x[PowerFocus-2]
	_ = x[PowerEnergy-3]
}

const _Power_name = "ManaRageFocusEnergy"

var _Power_index = [...]uint8{0, 4, 8, 13, 19}

func (i Power) String() string {
	if i < 0 || i >= Power(len(_Power_index)-1) {
		return "Power(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Power_name[_Power_index[i]:_Power_index[i+1]]
}
