// Code generated by "stringer -type Power -trimprefix=Power"; DO NOT EDIT.

package chrondbc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PowerMana-0]
	_ = x[PowerRage-1]
	_ = x[PowerFocus-2]
	_ = x[PowerEnergy-3]
	_ = x[PowerHappiness-4]
	_ = x[PowerRunes-5]
	_ = x[PowerRunicPower-6]
}

const _Power_name = "ManaRageFocusEnergyHappinessRunesRunicPower"

var _Power_index = [...]uint8{0, 4, 8, 13, 19, 28, 33, 43}

func (i Power) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Power_index)-1 {
		return "Power(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Power_name[_Power_index[idx]:_Power_index[idx+1]]
}
