// Code generated by "stringer -type PreventionType -trimprefix PreventionType"; DO NOT EDIT.

package chrondbc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PreventionTypeNone-0]
	_ = x[PreventionTypeSilence-1]
	_ = x[PreventionTypePacify-2]
}

const _PreventionType_name = "NoneSilencePacify"

var _PreventionType_index = [...]uint8{0, 4, 11, 17}

func (i PreventionType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_PreventionType_index)-1 {
		return "PreventionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PreventionType_name[_PreventionType_index[idx]:_PreventionType_index[idx+1]]
}
