// Code generated by "stringer -type ProcFlagsEx -trimprefix=ProcFlagsEx"; DO NOT EDIT.

package chrondbc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ProcExNone-0]
	_ = x[ProcExNormalHit-1]
	_ = x[ProcExCriticalHit-2]
	_ = x[ProcExMiss-4]
	_ = x[ProcExResist-8]
	_ = x[ProcExDodge-16]
	_ = x[ProcExParry-32]
	_ = x[ProcExBlock-64]
	_ = x[ProcExEvade-128]
	_ = x[ProcExImmune-256]
	_ = x[ProcExDeflect-512]
	_ = x[ProcExAbsorb-1024]
	_ = x[ProcExReflect-2048]
	_ = x[ProcExInterrupt-4096]
	_ = x[ProcExFullBlock-8192]
	_ = x[ProcExOnCastEnd-16384]
	_ = x[ProcExNotActiveSpell-32768]
	_ = x[ProcExTriggerAlways-65536]
	_ = x[ProcExOneTimeTrigger-131072]
	_ = x[ProcExOnlyActiveSpell-262144]
	_ = x[ProcEx_END-524288]
}

const _ProcFlagsEx_name = "ProcExNoneProcExNormalHitProcExCriticalHitProcExMissProcExResistProcExDodgeProcExParryProcExBlockProcExEvadeProcExImmuneProcExDeflectProcExAbsorbProcExReflectProcExInterruptProcExFullBlockProcExOnCastEndProcExNotActiveSpellProcExTriggerAlwaysProcExOneTimeTriggerProcExOnlyActiveSpellProcEx_END"

var _ProcFlagsEx_map = map[ProcFlagsEx]string{
	0:      _ProcFlagsEx_name[0:10],
	1:      _ProcFlagsEx_name[10:25],
	2:      _ProcFlagsEx_name[25:42],
	4:      _ProcFlagsEx_name[42:52],
	8:      _ProcFlagsEx_name[52:64],
	16:     _ProcFlagsEx_name[64:75],
	32:     _ProcFlagsEx_name[75:86],
	64:     _ProcFlagsEx_name[86:97],
	128:    _ProcFlagsEx_name[97:108],
	256:    _ProcFlagsEx_name[108:120],
	512:    _ProcFlagsEx_name[120:133],
	1024:   _ProcFlagsEx_name[133:145],
	2048:   _ProcFlagsEx_name[145:158],
	4096:   _ProcFlagsEx_name[158:173],
	8192:   _ProcFlagsEx_name[173:188],
	16384:  _ProcFlagsEx_name[188:203],
	32768:  _ProcFlagsEx_name[203:223],
	65536:  _ProcFlagsEx_name[223:242],
	131072: _ProcFlagsEx_name[242:262],
	262144: _ProcFlagsEx_name[262:283],
	524288: _ProcFlagsEx_name[283:293],
}

func (i ProcFlagsEx) String() string {
	if str, ok := _ProcFlagsEx_map[i]; ok {
		return str
	}
	return "ProcFlagsEx(" + strconv.FormatInt(int64(i), 10) + ")"
}
