// Code generated by "stringer -type ProcFlags -trimprefix=ProcFlag"; DO NOT EDIT.

package chrondbc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ProcFlagNone-0]
	_ = x[ProcFlagKilled-1]
	_ = x[ProcFlagKill-2]
	_ = x[ProcFlagDoneMeleeAutoAttack-4]
	_ = x[ProcFlagTakenMeleeAutoAttack-8]
	_ = x[ProcFlagDoneSpellMeleeDmgClass-16]
	_ = x[ProcFlagTakenSpellMeleeDmgClass-32]
	_ = x[ProcFlagDoneRangedAutoAttack-64]
	_ = x[ProcFlagTakenRangedAutoAttack-128]
	_ = x[ProcFlagDoneSpellRangedDmgClass-256]
	_ = x[ProcFlagTakenSpellRangedDmgClass-512]
	_ = x[ProcFlagDoneSpellNoneDmgClassPos-1024]
	_ = x[ProcFlagTakenSpellNoneDmgClassPos-2048]
	_ = x[ProcFlagDoneSpellNoneDmgClassNeg-4096]
	_ = x[ProcFlagTakenSpellNoneDmgClassNeg-8192]
	_ = x[ProcFlagDoneSpellMagicDmgClassPos-16384]
	_ = x[ProcFlagTakenSpellMagicDmgClassPos-32768]
	_ = x[ProcFlagDoneSpellMagicDmgClassNeg-65536]
	_ = x[ProcFlagTakenSpellMagicDmgClassNeg-131072]
	_ = x[ProcFlagDonePeriodic-262144]
	_ = x[ProcFlagTakenPeriodic-524288]
	_ = x[ProcFlagTakenDamage-1048576]
	_ = x[ProcFlagDoneTrapActivation-2097152]
	_ = x[ProcFlagDoneMainhandAttack-4194304]
	_ = x[ProcFlagDoneOffhandAttack-8388608]
	_ = x[ProcFlagDeath-16777216]
	_ = x[ProcFlag_END-33554432]
}

const _ProcFlags_name = "NoneKilledKillDoneMeleeAutoAttackTakenMeleeAutoAttackDoneSpellMeleeDmgClassTakenSpellMeleeDmgClassDoneRangedAutoAttackTakenRangedAutoAttackDoneSpellRangedDmgClassTakenSpellRangedDmgClassDoneSpellNoneDmgClassPosTakenSpellNoneDmgClassPosDoneSpellNoneDmgClassNegTakenSpellNoneDmgClassNegDoneSpellMagicDmgClassPosTakenSpellMagicDmgClassPosDoneSpellMagicDmgClassNegTakenSpellMagicDmgClassNegDonePeriodicTakenPeriodicTakenDamageDoneTrapActivationDoneMainhandAttackDoneOffhandAttackDeath_END"

var _ProcFlags_map = map[ProcFlags]string{
	0:        _ProcFlags_name[0:4],
	1:        _ProcFlags_name[4:10],
	2:        _ProcFlags_name[10:14],
	4:        _ProcFlags_name[14:33],
	8:        _ProcFlags_name[33:53],
	16:       _ProcFlags_name[53:75],
	32:       _ProcFlags_name[75:98],
	64:       _ProcFlags_name[98:118],
	128:      _ProcFlags_name[118:139],
	256:      _ProcFlags_name[139:162],
	512:      _ProcFlags_name[162:186],
	1024:     _ProcFlags_name[186:210],
	2048:     _ProcFlags_name[210:235],
	4096:     _ProcFlags_name[235:259],
	8192:     _ProcFlags_name[259:284],
	16384:    _ProcFlags_name[284:309],
	32768:    _ProcFlags_name[309:335],
	65536:    _ProcFlags_name[335:360],
	131072:   _ProcFlags_name[360:386],
	262144:   _ProcFlags_name[386:398],
	524288:   _ProcFlags_name[398:411],
	1048576:  _ProcFlags_name[411:422],
	2097152:  _ProcFlags_name[422:440],
	4194304:  _ProcFlags_name[440:458],
	8388608:  _ProcFlags_name[458:475],
	16777216: _ProcFlags_name[475:480],
	33554432: _ProcFlags_name[480:484],
}

func (i ProcFlags) String() string {
	if str, ok := _ProcFlags_map[i]; ok {
		return str
	}
	return "ProcFlags(" + strconv.FormatInt(int64(i), 10) + ")"
}
