// Code generated by "stringer -type School -trimprefix=School"; DO NOT EDIT.

package chrondbc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SchoolNone-0]
	_ = x[SchoolHoly-1]
	_ = x[SchoolFire-2]
	_ = x[SchoolNature-3]
	_ = x[SchoolFrost-4]
	_ = x[SchoolShadow-5]
	_ = x[SchoolArcane-6]
}

const _School_name = "NoneHolyFireNatureFrostShadowArcane"

var _School_index = [...]uint8{0, 4, 8, 12, 18, 23, 29, 35}

func (i School) String() string {
	if i < 0 || i >= School(len(_School_index)-1) {
		return "School(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _School_name[_School_index[i]:_School_index[i+1]]
}
