// Code generated by "stringer -type School -trimprefix=School"; DO NOT EDIT.

package chrondbc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SchoolPhysical-0]
	_ = x[SchoolHoly-1]
	_ = x[SchoolFire-2]
	_ = x[SchoolNature-4]
	_ = x[SchoolFrost-8]
	_ = x[SchoolShadow-16]
	_ = x[SchoolArcane-32]
}

const (
	_School_name_0 = "PhysicalHolyFire"
	_School_name_1 = "Nature"
	_School_name_2 = "Frost"
	_School_name_3 = "Shadow"
	_School_name_4 = "Arcane"
)

var (
	_School_index_0 = [...]uint8{0, 8, 12, 16}
)

func (i School) String() string {
	switch {
	case i <= 2:
		return _School_name_0[_School_index_0[i]:_School_index_0[i+1]]
	case i == 4:
		return _School_name_1
	case i == 8:
		return _School_name_2
	case i == 16:
		return _School_name_3
	case i == 32:
		return _School_name_4
	default:
		return "School(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
