// Code generated by "stringer -type SpellClassSet -trimprefix=SpellClassSet"; DO NOT EDIT.

package chrondbc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SpellClassSetGeneric-0]
	_ = x[SpellClassSet1-1]
	_ = x[SpellClassSet2-2]
	_ = x[SpellClassSetMage-3]
	_ = x[SpellClassSetWarrior-4]
	_ = x[SpellClassSetWarlock-5]
	_ = x[SpellClassSetPriest-6]
	_ = x[SpellClassSetDruid-7]
	_ = x[SpellClassSetRogue-8]
	_ = x[SpellClassSetHunter-9]
	_ = x[SpellClassSetPaladin-10]
	_ = x[SpellClassSetShaman-11]
}

const _SpellClassSet_name = "Generic12MageWarriorWarlockPriestDruidRogueHunterPaladinShaman"

var _SpellClassSet_index = [...]uint8{0, 7, 8, 9, 13, 20, 27, 33, 38, 43, 49, 56, 62}

func (i SpellClassSet) String() string {
	if i < 0 || i >= SpellClassSet(len(_SpellClassSet_index)-1) {
		return "SpellClassSet(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SpellClassSet_name[_SpellClassSet_index[i]:_SpellClassSet_index[i+1]]
}
