// Code generated by "stringer -type TargetFlags -trimprefix=TargetFlags"; DO NOT EDIT.

package chrondbc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TargetSelf-0]
	_ = x[TargetSpellDynamic1-1]
	_ = x[TargetUnit-2]
	_ = x[TargetUnitRaid-4]
	_ = x[TargetUnitParty-8]
	_ = x[TargetItem-16]
	_ = x[TargetSourceLocation-32]
	_ = x[TargetDestinationLocation-64]
	_ = x[TargetUnitEnemy-128]
	_ = x[TargetUnitAlly-256]
	_ = x[TargetCorpseEnemy-512]
	_ = x[TargetUnitDead-1024]
	_ = x[TargetGameObject-2048]
	_ = x[TargetTradeItem-4096]
	_ = x[TargetNameString-8192]
	_ = x[TargetGameObjectItem-16384]
	_ = x[TargetCorpseAlly-32768]
	_ = x[TargetUnitMinipet-65536]
	_ = x[TargetGlyph-131072]
	_ = x[TargetDestinationTarget-262144]
	_ = x[TargetExtraTargets-524288]
	_ = x[TargetUnitPassenger-1048576]
	_ = x[TargetUnk400000-4194304]
	_ = x[TargetUnk1000000-16777216]
	_ = x[TargetUnk4000000-67108864]
	_ = x[TargetUnk10000000-268435456]
	_ = x[TargetUnk40000000-1073741824]
}

const _TargetFlags_name = "TargetSelfTargetSpellDynamic1TargetUnitTargetUnitRaidTargetUnitPartyTargetItemTargetSourceLocationTargetDestinationLocationTargetUnitEnemyTargetUnitAllyTargetCorpseEnemyTargetUnitDeadTargetGameObjectTargetTradeItemTargetNameStringTargetGameObjectItemTargetCorpseAllyTargetUnitMinipetTargetGlyphTargetDestinationTargetTargetExtraTargetsTargetUnitPassengerTargetUnk400000TargetUnk1000000TargetUnk4000000TargetUnk10000000TargetUnk40000000"

var _TargetFlags_map = map[TargetFlags]string{
	0:          _TargetFlags_name[0:10],
	1:          _TargetFlags_name[10:29],
	2:          _TargetFlags_name[29:39],
	4:          _TargetFlags_name[39:53],
	8:          _TargetFlags_name[53:68],
	16:         _TargetFlags_name[68:78],
	32:         _TargetFlags_name[78:98],
	64:         _TargetFlags_name[98:123],
	128:        _TargetFlags_name[123:138],
	256:        _TargetFlags_name[138:152],
	512:        _TargetFlags_name[152:169],
	1024:       _TargetFlags_name[169:183],
	2048:       _TargetFlags_name[183:199],
	4096:       _TargetFlags_name[199:214],
	8192:       _TargetFlags_name[214:230],
	16384:      _TargetFlags_name[230:250],
	32768:      _TargetFlags_name[250:266],
	65536:      _TargetFlags_name[266:283],
	131072:     _TargetFlags_name[283:294],
	262144:     _TargetFlags_name[294:317],
	524288:     _TargetFlags_name[317:335],
	1048576:    _TargetFlags_name[335:354],
	4194304:    _TargetFlags_name[354:369],
	16777216:   _TargetFlags_name[369:385],
	67108864:   _TargetFlags_name[385:401],
	268435456:  _TargetFlags_name[401:418],
	1073741824: _TargetFlags_name[418:435],
}

func (i TargetFlags) String() string {
	if str, ok := _TargetFlags_map[i]; ok {
		return str
	}
	return "TargetFlags(" + strconv.FormatInt(int64(i), 10) + ")"
}
