// Code generated by "stringer -type TargetCreatureType -trimprefix TargetCreatureType"; DO NOT EDIT.

package chrondbc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CreatureTypeBeast-1]
	_ = x[CreatureTypeDragonkin-2]
	_ = x[CreatureTypeDemon-4]
	_ = x[CreatureTypeElemental-8]
	_ = x[CreatureTypeGiant-16]
	_ = x[CreatureTypeUndead-32]
	_ = x[CreatureTypeHumanoid-64]
	_ = x[CreatureTypeCritter-128]
	_ = x[CreatureTypeMechanical-256]
	_ = x[CreatureTypeNotSpecified-512]
	_ = x[CreatureTypeTotem-1024]
	_ = x[CreatureTypeNonCombatPet-2048]
	_ = x[CreatureTypeGasCloud-4096]
	_ = x[CreatureType_END-8192]
}

const _TargetCreatureType_name = "CreatureTypeBeastCreatureTypeDragonkinCreatureTypeDemonCreatureTypeElementalCreatureTypeGiantCreatureTypeUndeadCreatureTypeHumanoidCreatureTypeCritterCreatureTypeMechanicalCreatureTypeNotSpecifiedCreatureTypeTotemCreatureTypeNonCombatPetCreatureTypeGasCloudCreatureType_END"

var _TargetCreatureType_map = map[TargetCreatureType]string{
	1:    _TargetCreatureType_name[0:17],
	2:    _TargetCreatureType_name[17:38],
	4:    _TargetCreatureType_name[38:55],
	8:    _TargetCreatureType_name[55:76],
	16:   _TargetCreatureType_name[76:93],
	32:   _TargetCreatureType_name[93:111],
	64:   _TargetCreatureType_name[111:131],
	128:  _TargetCreatureType_name[131:150],
	256:  _TargetCreatureType_name[150:172],
	512:  _TargetCreatureType_name[172:196],
	1024: _TargetCreatureType_name[196:213],
	2048: _TargetCreatureType_name[213:237],
	4096: _TargetCreatureType_name[237:257],
	8192: _TargetCreatureType_name[257:273],
}

func (i TargetCreatureType) String() string {
	if str, ok := _TargetCreatureType_map[i]; ok {
		return str
	}
	return "TargetCreatureType(" + strconv.FormatInt(int64(i), 10) + ")"
}
