// Code generated by "stringer -type WeaponSubclass -trimprefix=WeaponSubclass"; DO NOT EDIT.

package chrondbc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[WeaponSubclassAxe1H-1]
	_ = x[WeaponSubclassAxe2H-2]
	_ = x[WeaponSubclassBow-4]
	_ = x[WeaponSubclassGun-8]
	_ = x[WeaponSubclassMace1H-16]
	_ = x[WeaponSubclassMace2H-32]
	_ = x[WeaponSubclassPolearm-64]
	_ = x[WeaponSubclassSword1H-128]
	_ = x[WeaponSubclassSword2H-256]
	_ = x[WeaponSubclassObsolete-512]
	_ = x[WeaponSubclassStaff-1024]
	_ = x[WeaponSubclassExotic1-2048]
	_ = x[WeaponSubclassExotic2-4096]
	_ = x[WeaponSubclassFist-8192]
	_ = x[WeaponSubclassMisc-16384]
	_ = x[WeaponSubclassDagger-32768]
	_ = x[WeaponSubclassThrown-65536]
	_ = x[WeaponSubclassSpear-131072]
	_ = x[WeaponSubclassCrossbow-262144]
	_ = x[WeaponSubclassWand-524288]
	_ = x[WeaponSubclassFishingPole-1048576]
}

const _WeaponSubclass_name = "Axe1HAxe2HBowGunMace1HMace2HPolearmSword1HSword2HObsoleteStaffExotic1Exotic2FistMiscDaggerThrownSpearCrossbowWandFishingPole"

var _WeaponSubclass_map = map[WeaponSubclass]string{
	1:       _WeaponSubclass_name[0:5],
	2:       _WeaponSubclass_name[5:10],
	4:       _WeaponSubclass_name[10:13],
	8:       _WeaponSubclass_name[13:16],
	16:      _WeaponSubclass_name[16:22],
	32:      _WeaponSubclass_name[22:28],
	64:      _WeaponSubclass_name[28:35],
	128:     _WeaponSubclass_name[35:42],
	256:     _WeaponSubclass_name[42:49],
	512:     _WeaponSubclass_name[49:57],
	1024:    _WeaponSubclass_name[57:62],
	2048:    _WeaponSubclass_name[62:69],
	4096:    _WeaponSubclass_name[69:76],
	8192:    _WeaponSubclass_name[76:80],
	16384:   _WeaponSubclass_name[80:84],
	32768:   _WeaponSubclass_name[84:90],
	65536:   _WeaponSubclass_name[90:96],
	131072:  _WeaponSubclass_name[96:101],
	262144:  _WeaponSubclass_name[101:109],
	524288:  _WeaponSubclass_name[109:113],
	1048576: _WeaponSubclass_name[113:124],
}

func (i WeaponSubclass) String() string {
	if str, ok := _WeaponSubclass_map[i]; ok {
		return str
	}
	return "WeaponSubclass(" + strconv.FormatInt(int64(i), 10) + ")"
}
