syntax = "proto3";

package chronicleproto;

option go_package = "github.com/Emyrk/chronicle/api/chronicleproto";

enum School {
  Unknown = 0;
  None = 1;
  Physical = 2;
  Holy = 3;
  Fire = 4;
  Nature = 5;
  Frost = 6;
  Shadow = 7;
  Arcane = 8;
}

message Tailer {
  optional uint32 amount = 1;
  uint32 hitType = 2;
}

message EventMeta {
  int32 index = 1;
  int64 offsetMilli = 2;
}

message Heal {
  EventMeta meta = 1;
  string caster = 3;
  string target = 4;
  string sourceName = 5;
  int32 amount = 6;
  uint32 hitType = 7;
}

message Damage {
  EventMeta meta = 1;

  optional string caster = 3;
  // sourceName is the spell or ability name (or environmental source)
  string sourceName = 4;
  string target = 5;
  uint32 hitType = 6;
  int32 amount = 7;
  School school = 8;
  repeated Tailer tailers = 9;
}

message ResourceChange {
  EventMeta meta = 1;
  string target = 3;
  int32 amount = 4;
  string resourceType = 5;
  optional string caster = 6;
  optional string sourceName = 7;
  string direction = 8;
}

message ExtraAttack {
  EventMeta meta = 1;
  string target = 2;
  int32 amount = 3;
  string sourceName = 5;
}