// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: chronicle.proto

package chronicleproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type School int32

const (
	School_Unknown  School = 0
	School_None     School = 1
	School_Physical School = 2
	School_Holy     School = 3
	School_Fire     School = 4
	School_Nature   School = 5
	School_Frost    School = 6
	School_Shadow   School = 7
	School_Arcane   School = 8
)

// Enum value maps for School.
var (
	School_name = map[int32]string{
		0: "Unknown",
		1: "None",
		2: "Physical",
		3: "Holy",
		4: "Fire",
		5: "Nature",
		6: "Frost",
		7: "Shadow",
		8: "Arcane",
	}
	School_value = map[string]int32{
		"Unknown":  0,
		"None":     1,
		"Physical": 2,
		"Holy":     3,
		"Fire":     4,
		"Nature":   5,
		"Frost":    6,
		"Shadow":   7,
		"Arcane":   8,
	}
)

func (x School) Enum() *School {
	p := new(School)
	*p = x
	return p
}

func (x School) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (School) Descriptor() protoreflect.EnumDescriptor {
	return file_chronicle_proto_enumTypes[0].Descriptor()
}

func (School) Type() protoreflect.EnumType {
	return &file_chronicle_proto_enumTypes[0]
}

func (x School) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use School.Descriptor instead.
func (School) EnumDescriptor() ([]byte, []int) {
	return file_chronicle_proto_rawDescGZIP(), []int{0}
}

type Tailer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        *uint32                `protobuf:"varint,1,opt,name=amount,proto3,oneof" json:"amount,omitempty"`
	HitType       uint32                 `protobuf:"varint,2,opt,name=hitType,proto3" json:"hitType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tailer) Reset() {
	*x = Tailer{}
	mi := &file_chronicle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tailer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tailer) ProtoMessage() {}

func (x *Tailer) ProtoReflect() protoreflect.Message {
	mi := &file_chronicle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tailer.ProtoReflect.Descriptor instead.
func (*Tailer) Descriptor() ([]byte, []int) {
	return file_chronicle_proto_rawDescGZIP(), []int{0}
}

func (x *Tailer) GetAmount() uint32 {
	if x != nil && x.Amount != nil {
		return *x.Amount
	}
	return 0
}

func (x *Tailer) GetHitType() uint32 {
	if x != nil {
		return x.HitType
	}
	return 0
}

type EventMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	OffsetMilli   int64                  `protobuf:"varint,2,opt,name=offsetMilli,proto3" json:"offsetMilli,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventMeta) Reset() {
	*x = EventMeta{}
	mi := &file_chronicle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventMeta) ProtoMessage() {}

func (x *EventMeta) ProtoReflect() protoreflect.Message {
	mi := &file_chronicle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventMeta.ProtoReflect.Descriptor instead.
func (*EventMeta) Descriptor() ([]byte, []int) {
	return file_chronicle_proto_rawDescGZIP(), []int{1}
}

func (x *EventMeta) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *EventMeta) GetOffsetMilli() int64 {
	if x != nil {
		return x.OffsetMilli
	}
	return 0
}

type Heal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *EventMeta             `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Caster        string                 `protobuf:"bytes,3,opt,name=caster,proto3" json:"caster,omitempty"`
	Target        string                 `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`
	SourceName    string                 `protobuf:"bytes,5,opt,name=sourceName,proto3" json:"sourceName,omitempty"`
	Amount        int32                  `protobuf:"varint,6,opt,name=amount,proto3" json:"amount,omitempty"`
	HitType       uint32                 `protobuf:"varint,7,opt,name=hitType,proto3" json:"hitType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heal) Reset() {
	*x = Heal{}
	mi := &file_chronicle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heal) ProtoMessage() {}

func (x *Heal) ProtoReflect() protoreflect.Message {
	mi := &file_chronicle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heal.ProtoReflect.Descriptor instead.
func (*Heal) Descriptor() ([]byte, []int) {
	return file_chronicle_proto_rawDescGZIP(), []int{2}
}

func (x *Heal) GetMeta() *EventMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Heal) GetCaster() string {
	if x != nil {
		return x.Caster
	}
	return ""
}

func (x *Heal) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Heal) GetSourceName() string {
	if x != nil {
		return x.SourceName
	}
	return ""
}

func (x *Heal) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Heal) GetHitType() uint32 {
	if x != nil {
		return x.HitType
	}
	return 0
}

type Damage struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Meta   *EventMeta             `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Caster *string                `protobuf:"bytes,3,opt,name=caster,proto3,oneof" json:"caster,omitempty"`
	// sourceName is the spell or ability name (or environmental source)
	SourceName    string    `protobuf:"bytes,4,opt,name=sourceName,proto3" json:"sourceName,omitempty"`
	Target        string    `protobuf:"bytes,5,opt,name=target,proto3" json:"target,omitempty"`
	HitType       uint32    `protobuf:"varint,6,opt,name=hitType,proto3" json:"hitType,omitempty"`
	Amount        int32     `protobuf:"varint,7,opt,name=amount,proto3" json:"amount,omitempty"`
	School        School    `protobuf:"varint,8,opt,name=school,proto3,enum=chronicleproto.School" json:"school,omitempty"`
	Tailers       []*Tailer `protobuf:"bytes,9,rep,name=tailers,proto3" json:"tailers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Damage) Reset() {
	*x = Damage{}
	mi := &file_chronicle_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Damage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Damage) ProtoMessage() {}

func (x *Damage) ProtoReflect() protoreflect.Message {
	mi := &file_chronicle_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Damage.ProtoReflect.Descriptor instead.
func (*Damage) Descriptor() ([]byte, []int) {
	return file_chronicle_proto_rawDescGZIP(), []int{3}
}

func (x *Damage) GetMeta() *EventMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Damage) GetCaster() string {
	if x != nil && x.Caster != nil {
		return *x.Caster
	}
	return ""
}

func (x *Damage) GetSourceName() string {
	if x != nil {
		return x.SourceName
	}
	return ""
}

func (x *Damage) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Damage) GetHitType() uint32 {
	if x != nil {
		return x.HitType
	}
	return 0
}

func (x *Damage) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Damage) GetSchool() School {
	if x != nil {
		return x.School
	}
	return School_Unknown
}

func (x *Damage) GetTailers() []*Tailer {
	if x != nil {
		return x.Tailers
	}
	return nil
}

type ResourceChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *EventMeta             `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Target        string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	Amount        int32                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	ResourceType  string                 `protobuf:"bytes,5,opt,name=resourceType,proto3" json:"resourceType,omitempty"`
	Caster        *string                `protobuf:"bytes,6,opt,name=caster,proto3,oneof" json:"caster,omitempty"`
	SourceName    *string                `protobuf:"bytes,7,opt,name=sourceName,proto3,oneof" json:"sourceName,omitempty"`
	Direction     string                 `protobuf:"bytes,8,opt,name=direction,proto3" json:"direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceChange) Reset() {
	*x = ResourceChange{}
	mi := &file_chronicle_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceChange) ProtoMessage() {}

func (x *ResourceChange) ProtoReflect() protoreflect.Message {
	mi := &file_chronicle_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceChange.ProtoReflect.Descriptor instead.
func (*ResourceChange) Descriptor() ([]byte, []int) {
	return file_chronicle_proto_rawDescGZIP(), []int{4}
}

func (x *ResourceChange) GetMeta() *EventMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ResourceChange) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *ResourceChange) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ResourceChange) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *ResourceChange) GetCaster() string {
	if x != nil && x.Caster != nil {
		return *x.Caster
	}
	return ""
}

func (x *ResourceChange) GetSourceName() string {
	if x != nil && x.SourceName != nil {
		return *x.SourceName
	}
	return ""
}

func (x *ResourceChange) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

type ExtraAttack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *EventMeta             `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Caster        string                 `protobuf:"bytes,3,opt,name=caster,proto3" json:"caster,omitempty"`
	Target        string                 `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`
	SourceName    string                 `protobuf:"bytes,5,opt,name=sourceName,proto3" json:"sourceName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtraAttack) Reset() {
	*x = ExtraAttack{}
	mi := &file_chronicle_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtraAttack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtraAttack) ProtoMessage() {}

func (x *ExtraAttack) ProtoReflect() protoreflect.Message {
	mi := &file_chronicle_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtraAttack.ProtoReflect.Descriptor instead.
func (*ExtraAttack) Descriptor() ([]byte, []int) {
	return file_chronicle_proto_rawDescGZIP(), []int{5}
}

func (x *ExtraAttack) GetMeta() *EventMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ExtraAttack) GetCaster() string {
	if x != nil {
		return x.Caster
	}
	return ""
}

func (x *ExtraAttack) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *ExtraAttack) GetSourceName() string {
	if x != nil {
		return x.SourceName
	}
	return ""
}

var File_chronicle_proto protoreflect.FileDescriptor

const file_chronicle_proto_rawDesc = "" +
	"\n" +
	"\x0fchronicle.proto\x12\x0echronicleproto\"J\n" +
	"\x06Tailer\x12\x1b\n" +
	"\x06amount\x18\x01 \x01(\rH\x00R\x06amount\x88\x01\x01\x12\x18\n" +
	"\ahitType\x18\x02 \x01(\rR\ahitTypeB\t\n" +
	"\a_amount\"C\n" +
	"\tEventMeta\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12 \n" +
	"\voffsetMilli\x18\x02 \x01(\x03R\voffsetMilli\"\xb7\x01\n" +
	"\x04Heal\x12-\n" +
	"\x04meta\x18\x01 \x01(\v2\x19.chronicleproto.EventMetaR\x04meta\x12\x16\n" +
	"\x06caster\x18\x03 \x01(\tR\x06caster\x12\x16\n" +
	"\x06target\x18\x04 \x01(\tR\x06target\x12\x1e\n" +
	"\n" +
	"sourceName\x18\x05 \x01(\tR\n" +
	"sourceName\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\x05R\x06amount\x12\x18\n" +
	"\ahitType\x18\a \x01(\rR\ahitType\"\xab\x02\n" +
	"\x06Damage\x12-\n" +
	"\x04meta\x18\x01 \x01(\v2\x19.chronicleproto.EventMetaR\x04meta\x12\x1b\n" +
	"\x06caster\x18\x03 \x01(\tH\x00R\x06caster\x88\x01\x01\x12\x1e\n" +
	"\n" +
	"sourceName\x18\x04 \x01(\tR\n" +
	"sourceName\x12\x16\n" +
	"\x06target\x18\x05 \x01(\tR\x06target\x12\x18\n" +
	"\ahitType\x18\x06 \x01(\rR\ahitType\x12\x16\n" +
	"\x06amount\x18\a \x01(\x05R\x06amount\x12.\n" +
	"\x06school\x18\b \x01(\x0e2\x16.chronicleproto.SchoolR\x06school\x120\n" +
	"\atailers\x18\t \x03(\v2\x16.chronicleproto.TailerR\atailersB\t\n" +
	"\a_caster\"\x8d\x02\n" +
	"\x0eResourceChange\x12-\n" +
	"\x04meta\x18\x01 \x01(\v2\x19.chronicleproto.EventMetaR\x04meta\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x05R\x06amount\x12\"\n" +
	"\fresourceType\x18\x05 \x01(\tR\fresourceType\x12\x1b\n" +
	"\x06caster\x18\x06 \x01(\tH\x00R\x06caster\x88\x01\x01\x12#\n" +
	"\n" +
	"sourceName\x18\a \x01(\tH\x01R\n" +
	"sourceName\x88\x01\x01\x12\x1c\n" +
	"\tdirection\x18\b \x01(\tR\tdirectionB\t\n" +
	"\a_casterB\r\n" +
	"\v_sourceName\"\x8c\x01\n" +
	"\vExtraAttack\x12-\n" +
	"\x04meta\x18\x01 \x01(\v2\x19.chronicleproto.EventMetaR\x04meta\x12\x16\n" +
	"\x06caster\x18\x03 \x01(\tR\x06caster\x12\x16\n" +
	"\x06target\x18\x04 \x01(\tR\x06target\x12\x1e\n" +
	"\n" +
	"sourceName\x18\x05 \x01(\tR\n" +
	"sourceName*p\n" +
	"\x06School\x12\v\n" +
	"\aUnknown\x10\x00\x12\b\n" +
	"\x04None\x10\x01\x12\f\n" +
	"\bPhysical\x10\x02\x12\b\n" +
	"\x04Holy\x10\x03\x12\b\n" +
	"\x04Fire\x10\x04\x12\n" +
	"\n" +
	"\x06Nature\x10\x05\x12\t\n" +
	"\x05Frost\x10\x06\x12\n" +
	"\n" +
	"\x06Shadow\x10\a\x12\n" +
	"\n" +
	"\x06Arcane\x10\bB/Z-github.com/Emyrk/chronicle/api/chronicleprotob\x06proto3"

var (
	file_chronicle_proto_rawDescOnce sync.Once
	file_chronicle_proto_rawDescData []byte
)

func file_chronicle_proto_rawDescGZIP() []byte {
	file_chronicle_proto_rawDescOnce.Do(func() {
		file_chronicle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chronicle_proto_rawDesc), len(file_chronicle_proto_rawDesc)))
	})
	return file_chronicle_proto_rawDescData
}

var file_chronicle_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_chronicle_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_chronicle_proto_goTypes = []any{
	(School)(0),            // 0: chronicleproto.School
	(*Tailer)(nil),         // 1: chronicleproto.Tailer
	(*EventMeta)(nil),      // 2: chronicleproto.EventMeta
	(*Heal)(nil),           // 3: chronicleproto.Heal
	(*Damage)(nil),         // 4: chronicleproto.Damage
	(*ResourceChange)(nil), // 5: chronicleproto.ResourceChange
	(*ExtraAttack)(nil),    // 6: chronicleproto.ExtraAttack
}
var file_chronicle_proto_depIdxs = []int32{
	2, // 0: chronicleproto.Heal.meta:type_name -> chronicleproto.EventMeta
	2, // 1: chronicleproto.Damage.meta:type_name -> chronicleproto.EventMeta
	0, // 2: chronicleproto.Damage.school:type_name -> chronicleproto.School
	1, // 3: chronicleproto.Damage.tailers:type_name -> chronicleproto.Tailer
	2, // 4: chronicleproto.ResourceChange.meta:type_name -> chronicleproto.EventMeta
	2, // 5: chronicleproto.ExtraAttack.meta:type_name -> chronicleproto.EventMeta
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_chronicle_proto_init() }
func file_chronicle_proto_init() {
	if File_chronicle_proto != nil {
		return
	}
	file_chronicle_proto_msgTypes[0].OneofWrappers = []any{}
	file_chronicle_proto_msgTypes[3].OneofWrappers = []any{}
	file_chronicle_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chronicle_proto_rawDesc), len(file_chronicle_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chronicle_proto_goTypes,
		DependencyIndexes: file_chronicle_proto_depIdxs,
		EnumInfos:         file_chronicle_proto_enumTypes,
		MessageInfos:      file_chronicle_proto_msgTypes,
	}.Build()
	File_chronicle_proto = out.File
	file_chronicle_proto_goTypes = nil
	file_chronicle_proto_depIdxs = nil
}
