package cli

import (
	"fmt"
	"os"
	"text/template"

	"github.com/Emyrk/chronicle/database/gamedb/chrondbc"
	"github.com/Emyrk/chronicle/database/gamedb/dbcdb"
	"github.com/coder/serpent"
)

func ExtraAttacksCmd() *serpent.Command {
	var goOutput string
	var tsOutput string
	var dbcPath string
	return &serpent.Command{
		Use:   "extra-attacks",
		Short: "Generate extra attack spell map from DBC data.",
		Options: serpent.OptionSet{
			{
				Name:        "go-out",
				Description: "Output path for Go file.",
				Flag:        "go-out",
				Value:       serpent.StringOf(&goOutput),
			},
			{
				Name:        "ts-out",
				Description: "Output path for TypeScript file.",
				Flag:        "ts-out",
				Value:       serpent.StringOf(&tsOutput),
			},
			{
				Name:        "dbc",
				Description: "Path to WoW client directory.",
				Flag:        "dbc",
				Value:       serpent.StringOf(&dbcPath),
				Default:     "/home/steven/Games/turtlewow/drive_c/Program Files (x86)/TurtleWoW",
			},
		},
		Handler: func(inv *serpent.Invocation) error {
			wc, err := dbcdb.New(dbcPath)
			if err != nil {
				return fmt.Errorf("open wow client: %w", err)
			}

			entries, err := collectExtraAttackSpells(wc)
			if err != nil {
				return err
			}

			if goOutput != "" {
				if err := writeTemplate(goOutput, extraAttacksGoTemplate, entries); err != nil {
					return fmt.Errorf("write go file: %w", err)
				}
			}

			if tsOutput != "" {
				if err := writeTemplate(tsOutput, extraAttacksTSTemplate, entries); err != nil {
					return fmt.Errorf("write ts file: %w", err)
				}
			}

			return nil
		},
	}
}

type extraAttackEntry struct {
	ID   int32
	Name string
}

func collectExtraAttackSpells(wc *dbcdb.WoWClient) ([]extraAttackEntry, error) {
	spellsDBC, err := wc.Spells()
	if err != nil {
		return nil, fmt.Errorf("read spells: %w", err)
	}

	spells := chrondbc.NewSpells(spellsDBC.Underlying())
	var entries []extraAttackEntry

	err = spells.Range(func(spell *chrondbc.Spell) bool {
		for _, e := range spell.Effect {
			if e == chrondbc.EffectAddExtraAttacks {
				entries = append(entries, extraAttackEntry{
					ID:   int32(spell.ID),
					Name: spell.String(),
				})
				break
			}
		}
		return true
	})
	if err != nil {
		return nil, fmt.Errorf("iterate spells: %w", err)
	}

	return entries, nil
}

func writeTemplate(path string, tmpl *template.Template, data any) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()
	return tmpl.Execute(f, data)
}

var extraAttacksGoTemplate = template.Must(template.New("extraattacks-go").Parse(`// Code generated by scripts/dbcdata. DO NOT EDIT.

package spelldata

import "github.com/Emyrk/chronicle/database/gamedb/chrondbc"

// ExtraAttackSpells maps spell IDs to spell names for all spells
// with the EffectAddExtraAttacks effect.
var ExtraAttackSpells = map[chrondbc.SpellID]string{
{{- range .}}
	{{.ID}}: {{printf "%q" .Name}},
{{- end}}
}
`))

var extraAttacksTSTemplate = template.Must(template.New("extraattacks-ts").Parse(`// Code generated by scripts/dbcdata. DO NOT EDIT.

export const ExtraAttackSpells: Record<number, string> = {
{{- range .}}
  {{.ID}}: {{printf "%q" .Name}},
{{- end}}
};
`))
