package cli

import (
	"fmt"
	"text/template"

	"github.com/Emyrk/chronicle/database/gamedb/chrondbc"
	"github.com/Emyrk/chronicle/database/gamedb/dbcdb"
)

type extraAttackEntry struct {
	ID   int32
	Name string
}

func collectExtraAttackSpells(wc *dbcdb.WoWClient) ([]extraAttackEntry, error) {
	spellsDBC, err := wc.Spells()
	if err != nil {
		return nil, fmt.Errorf("read spells: %w", err)
	}

	spells := chrondbc.NewSpells(spellsDBC.Underlying())
	var entries []extraAttackEntry

	err = spells.Range(func(spell *chrondbc.Spell) bool {
		for _, effect := range spell.Effect {
			if effect == chrondbc.EffectAddExtraAttacks {
				entries = append(entries, extraAttackEntry{
					ID:   int32(spell.ID),
					Name: spell.String(),
				})
				break
			}
		}
		return true
	})
	if err != nil {
		return nil, fmt.Errorf("iterate spells: %w", err)
	}

	return entries, nil
}

var extraAttacksGoTemplate = template.Must(template.New("extraattacks-go").Parse(`// Code generated by scripts/dbcdata. DO NOT EDIT.

package dbcmem

// ExtraAttackSpells maps spell IDs to spell names for all spells
// with the EffectAddExtraAttacks effect.
var ExtraAttackSpells = map[int32]string{
{{- range .}}
	{{.ID}}: {{printf "%q" .Name}},
{{- end}}
}
`))

var extraAttacksTSTemplate = template.Must(template.New("extraattacks-ts").Parse(`// Code generated by scripts/dbcdata. DO NOT EDIT.

export const ExtraAttackSpells: Record<number, string> = {
{{- range .}}
  {{.ID}}: {{printf "%q" .Name}},
{{- end}}
};
`))
