package cli

import (
	"fmt"
	"text/template"

	"github.com/Emyrk/chronicle/database/gamedb/chrondbc"
	"github.com/Emyrk/chronicle/database/gamedb/dbcdb"
)

type periodicSpellEntry struct {
	ID        int32
	Name      string
	HasDirect bool
}

func collectPeriodicSpells(wc *dbcdb.WoWClient) ([]periodicSpellEntry, error) {
	rawSpells, err := wc.Spells()
	if err != nil {
		return nil, fmt.Errorf("read spells: %w", err)
	}

	spells := chrondbc.NewSpells(rawSpells.Underlying())
	var entries []periodicSpellEntry

	err = spells.Range(func(spell *chrondbc.Spell) bool {
		dmgType := spell.SpellDamageType()
		if dmgType.Has(chrondbc.SpellDamagePeriodic) {
			entries = append(entries, periodicSpellEntry{
				ID:        int32(spell.ID),
				Name:      spell.Name(),
				HasDirect: dmgType.Has(chrondbc.SpellDamageDirect),
			})
		}
		return true
	})
	if err != nil {
		return nil, fmt.Errorf("iterate spells: %w", err)
	}

	return entries, nil
}

var periodicSpellsGoTemplate = template.Must(template.New("periodicspells-go").Parse(`// Code generated by scripts/dbcdata. DO NOT EDIT.

package dbcmem

// PeriodicSpell holds metadata about a periodic spell.
type PeriodicSpell struct {
	Name      string
	HasDirect bool // true if the spell also has a direct damage/healing component
}

// PeriodicSpells maps spell IDs to their metadata for all periodic spells.
// Periodic spells have effects like periodic damage, healing, energize, etc.
var PeriodicSpells = map[int32]PeriodicSpell{
{{- range .}}
	{{.ID}}: {Name: {{printf "%q" .Name}}, HasDirect: {{.HasDirect}}},
{{- end}}
}
`))
