package cli

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/Emyrk/chronicle/database/gamedb/dbcdb"
	"github.com/Gophercraft/core/format/dbc/dbdefs"

	"github.com/coder/serpent"
)

func StaticPopulateCmd() *serpent.Command {
	var outputDir string
	var dbcPath string
	return &serpent.Command{
		Use:   "static",
		Short: "Generate static Go code from DBC data.",
		Options: serpent.OptionSet{
			{
				Name:          "output-dir",
				Description:   "Output directory for generated files. Defaults to stdout.",
				Flag:          "output-dir",
				FlagShorthand: "o",
				Value:         serpent.StringOf(&outputDir),
			},
			{
				Name:        "dbc",
				Description: "Path to WoW client directory.",
				Flag:        "dbc",
				Value:       serpent.StringOf(&dbcPath),
				Default:     "/home/steven/Games/turtlewow/drive_c/Program Files (x86)/TurtleWoW",
			},
		},
		Handler: func(inv *serpent.Invocation) error {
			wc, err := dbcdb.New(dbcPath)
			if err != nil {
				return fmt.Errorf("open wow client: %w", err)
			}

			// Generate cast times
			if err := generateCastTimes(wc, outputDir, inv.Stdout); err != nil {
				return fmt.Errorf("generate cast times: %w", err)
			}

			// Generate spell icons
			if err := generateSpellIcons(wc, outputDir, inv.Stdout); err != nil {
				return fmt.Errorf("generate spell icons: %w", err)
			}

			// Generate spell durations
			if err := generateSpellDurations(wc, outputDir, inv.Stdout); err != nil {
				return fmt.Errorf("generate spell durations: %w", err)
			}

			// Generate spell ranges
			if err := generateSpellRanges(wc, outputDir, inv.Stdout); err != nil {
				return fmt.Errorf("generate spell ranges: %w", err)
			}

			// Generate spell categories
			if err := generateSpellCategories(wc, outputDir, inv.Stdout); err != nil {
				return fmt.Errorf("generate spell categories: %w", err)
			}

			// Generate spell radii
			if err := generateSpellRadii(wc, outputDir, inv.Stdout); err != nil {
				return fmt.Errorf("generate spell radii: %w", err)
			}

			// Generate spell focus objects
			if err := generateSpellFocusObjects(wc, outputDir, inv.Stdout); err != nil {
				return fmt.Errorf("generate spell focus objects: %w", err)
			}

			return nil
		},
	}
}

func generateCastTimes(wc *dbcdb.WoWClient, outputDir string, stdout io.Writer) error {
	sct, err := wc.SpellCastTimes()
	if err != nil {
		return fmt.Errorf("read spell cast times: %w", err)
	}

	var entries []dbdefs.Ent_SpellCastTimes
	err = sct.Range(func(cursor *dbdefs.Ent_SpellCastTimes) bool {
		entries = append(entries, *cursor)
		return true
	})
	if err != nil {
		return fmt.Errorf("iterate spell cast times: %w", err)
	}

	out, cleanup, err := outputWriter(outputDir, "casttimes.go", stdout)
	if err != nil {
		return err
	}
	defer cleanup()

	return castTimesTemplate.Execute(out, entries)
}

type spellIconEntry struct {
	ID              int32
	TextureFilename string
}

func generateSpellIcons(wc *dbcdb.WoWClient, outputDir string, stdout io.Writer) error {
	icons, err := wc.SpellIcons()
	if err != nil {
		return fmt.Errorf("read spell icons: %w", err)
	}

	var entries []spellIconEntry
	err = icons.Range(func(cursor *dbdefs.Ent_SpellIcon) bool {
		entries = append(entries, spellIconEntry{
			ID:              cursor.ID,
			TextureFilename: strings.TrimPrefix(cursor.TextureFilename, "Interface\\Icons\\"),
		})
		return true
	})
	if err != nil {
		return fmt.Errorf("iterate spell icons: %w", err)
	}

	out, cleanup, err := outputWriter(outputDir, "spellicons.go", stdout)
	if err != nil {
		return err
	}
	defer cleanup()

	return spellIconsTemplate.Execute(out, entries)
}

// outputWriter returns a writer for the given filename.
// If outputDir is empty, returns stdout.
// The cleanup function must be called to close any opened file.
func outputWriter(outputDir, filename string, stdout io.Writer) (io.Writer, func(), error) {
	if outputDir == "" {
		return stdout, func() {}, nil
	}

	path := filepath.Join(outputDir, filename)
	f, err := os.Create(path)
	if err != nil {
		return nil, nil, fmt.Errorf("create %s: %w", path, err)
	}
	return f, func() { f.Close() }, nil
}

var castTimesTemplate = template.Must(template.New("casttimes").Parse(`// Code generated by scripts/dbcdata. DO NOT EDIT.

package dbcmem

// SpellCastTime represents a cast time entry from SpellCastTimes.dbc
type SpellCastTime struct {
	ID       int32
	Base     int32 // Base cast time in milliseconds
	PerLevel int32 // Cast time reduction per level (negative = faster)
	Minimum  int32 // Minimum cast time in milliseconds
}

// SpellCastTimes is a lookup table for cast times by ID.
var SpellCastTimes = map[int32]SpellCastTime{
{{- range .}}
	{{.ID}}: {ID: {{.ID}}, Base: {{.Base}}, PerLevel: {{.PerLevel}}, Minimum: {{.Minimum}}},
{{- end}}
}

// GetCastTime returns the SpellCastTime for the given ID.
// Returns zero value if not found.
func GetCastTime(id int32) SpellCastTime {
	return SpellCastTimes[id]
}
`))

var spellIconsTemplate = template.Must(template.New("spellicons").Parse(`// Code generated by scripts/dbcdata. DO NOT EDIT.

package dbcmem

// SpellIcon represents an icon entry from SpellIcon.dbc
type SpellIcon struct {
	ID              int32
	TextureFilename string
}

// SpellIcons is a lookup table for spell icons by ID.
var SpellIcons = map[int32]SpellIcon{
{{- range .}}
	{{.ID}}: {ID: {{.ID}}, TextureFilename: {{printf "%q" .TextureFilename}}},
{{- end}}
}

// GetSpellIcon returns the SpellIcon for the given ID.
// Returns zero value if not found.
func GetSpellIcon(id int32) SpellIcon {
	return SpellIcons[id]
}
`))

func generateSpellDurations(wc *dbcdb.WoWClient, outputDir string, stdout io.Writer) error {
	durations, err := wc.SpellDuration()
	if err != nil {
		return fmt.Errorf("read spell durations: %w", err)
	}

	var entries []dbdefs.Ent_SpellDuration
	err = durations.Range(func(cursor *dbdefs.Ent_SpellDuration) bool {
		entries = append(entries, *cursor)
		return true
	})
	if err != nil {
		return fmt.Errorf("iterate spell durations: %w", err)
	}

	out, cleanup, err := outputWriter(outputDir, "spellduration.go", stdout)
	if err != nil {
		return err
	}
	defer cleanup()

	return spellDurationTemplate.Execute(out, entries)
}

var spellDurationTemplate = template.Must(template.New("spellduration").Parse(`// Code generated by scripts/dbcdata. DO NOT EDIT.

package dbcmem

// SpellDuration represents a duration entry from SpellDuration.dbc
type SpellDuration struct {
	ID               int32
	Duration         int32 // Base duration in milliseconds
	DurationPerLevel int32 // Duration increase per level
	MaxDuration      int32 // Maximum duration in milliseconds
}

// SpellDurations is a lookup table for spell durations by ID.
var SpellDurations = map[int32]SpellDuration{
{{- range .}}
	{{.ID}}: {ID: {{.ID}}, Duration: {{.Duration}}, DurationPerLevel: {{.DurationPerLevel}}, MaxDuration: {{.MaxDuration}}},
{{- end}}
}

// GetSpellDuration returns the SpellDuration for the given ID.
// Returns zero value if not found.
func GetSpellDuration(id int32) SpellDuration {
	return SpellDurations[id]
}
`))

type spellRangeEntry struct {
	ID       int32
	RangeMin float32
	RangeMax float32
	Flags    int32
	Name     string
}

func generateSpellRanges(wc *dbcdb.WoWClient, outputDir string, stdout io.Writer) error {
	ranges, err := wc.SpellRange()
	if err != nil {
		return fmt.Errorf("read spell ranges: %w", err)
	}

	var entries []spellRangeEntry
	err = ranges.Range(func(cursor *dbdefs.Ent_SpellRange) bool {
		// RangeMin/RangeMax are slices with [0]=friendly, [1]=hostile
		// We take the hostile range (index 1) as the primary value
		var rangeMin, rangeMax float32
		if len(cursor.RangeMin) > 1 {
			rangeMin = cursor.RangeMin[1]
		} else if len(cursor.RangeMin) > 0 {
			rangeMin = cursor.RangeMin[0]
		}
		if len(cursor.RangeMax) > 1 {
			rangeMax = cursor.RangeMax[1]
		} else if len(cursor.RangeMax) > 0 {
			rangeMax = cursor.RangeMax[0]
		}

		entries = append(entries, spellRangeEntry{
			ID:       cursor.ID,
			RangeMin: rangeMin,
			RangeMax: rangeMax,
			Flags:    cursor.Flags,
			Name:     cursor.DisplayName_lang.String(),
		})
		return true
	})
	if err != nil {
		return fmt.Errorf("iterate spell ranges: %w", err)
	}

	out, cleanup, err := outputWriter(outputDir, "spellrange.go", stdout)
	if err != nil {
		return err
	}
	defer cleanup()

	return spellRangeTemplate.Execute(out, entries)
}

var spellRangeTemplate = template.Must(template.New("spellrange").Parse(`// Code generated by scripts/dbcdata. DO NOT EDIT.

package dbcmem

// SpellRange represents a range entry from SpellRange.dbc
type SpellRange struct {
	ID       int32
	RangeMin float32 // Minimum range in yards
	RangeMax float32 // Maximum range in yards
	Flags    int32
	Name     string
}

// SpellRanges is a lookup table for spell ranges by ID.
var SpellRanges = map[int32]SpellRange{
{{- range .}}
	{{.ID}}: {ID: {{.ID}}, RangeMin: {{.RangeMin}}, RangeMax: {{.RangeMax}}, Flags: {{.Flags}}, Name: {{printf "%q" .Name}}},
{{- end}}
}

// GetSpellRange returns the SpellRange for the given ID.
// Returns zero value if not found.
func GetSpellRange(id int32) SpellRange {
	return SpellRanges[id]
}
`))

type spellCategoryEntry struct {
	ID                 int32
	Flags              int32
	UsesPerWeek        int32
	Name               string
	MaxCharges         int32
	ChargeRecoveryTime int32
	TypeMask           int32
}

func generateSpellCategories(wc *dbcdb.WoWClient, outputDir string, stdout io.Writer) error {
	categories, err := wc.SpellCategory()
	if err != nil {
		return fmt.Errorf("read spell categories: %w", err)
	}

	var entries []spellCategoryEntry
	err = categories.Range(func(cursor *dbdefs.Ent_SpellCategory) bool {
		entries = append(entries, spellCategoryEntry{
			ID:                 cursor.ID,
			Flags:              cursor.Flags,
			UsesPerWeek:        cursor.UsesPerWeek,
			Name:               cursor.Name_lang.String(),
			MaxCharges:         cursor.MaxCharges,
			ChargeRecoveryTime: cursor.ChargeRecoveryTime,
			TypeMask:           cursor.TypeMask,
		})
		return true
	})
	if err != nil {
		return fmt.Errorf("iterate spell categories: %w", err)
	}

	out, cleanup, err := outputWriter(outputDir, "spellcategory.go", stdout)
	if err != nil {
		return err
	}
	defer cleanup()

	return spellCategoryTemplate.Execute(out, entries)
}

var spellCategoryTemplate = template.Must(template.New("spellcategory").Parse(`// Code generated by scripts/dbcdata. DO NOT EDIT.

package dbcmem

// SpellCategory represents a category entry from SpellCategory.dbc
type SpellCategory struct {
	ID                 int32
	Flags              int32
	UsesPerWeek        int32
	Name               string
	MaxCharges         int32
	ChargeRecoveryTime int32 // Charge recovery time in milliseconds
	TypeMask           int32
}

// SpellCategories is a lookup table for spell categories by ID.
var SpellCategories = map[int32]SpellCategory{
{{- range .}}
	{{.ID}}: {ID: {{.ID}}, Flags: {{.Flags}}, UsesPerWeek: {{.UsesPerWeek}}, Name: {{printf "%q" .Name}}, MaxCharges: {{.MaxCharges}}, ChargeRecoveryTime: {{.ChargeRecoveryTime}}, TypeMask: {{.TypeMask}}},
{{- end}}
}

// GetSpellCategory returns the SpellCategory for the given ID.
// Returns zero value if not found.
func GetSpellCategory(id int32) SpellCategory {
	return SpellCategories[id]
}
`))

func generateSpellRadii(wc *dbcdb.WoWClient, outputDir string, stdout io.Writer) error {
	radii, err := wc.SpellRadius()
	if err != nil {
		return fmt.Errorf("read spell radii: %w", err)
	}

	var entries []dbdefs.Ent_SpellRadius
	err = radii.Range(func(cursor *dbdefs.Ent_SpellRadius) bool {
		entries = append(entries, *cursor)
		return true
	})
	if err != nil {
		return fmt.Errorf("iterate spell radii: %w", err)
	}

	out, cleanup, err := outputWriter(outputDir, "spellradius.go", stdout)
	if err != nil {
		return err
	}
	defer cleanup()

	return spellRadiusTemplate.Execute(out, entries)
}

var spellRadiusTemplate = template.Must(template.New("spellradius").Parse(`// Code generated by scripts/dbcdata. DO NOT EDIT.

package dbcmem

// SpellRadius represents a radius entry from SpellRadius.dbc
type SpellRadius struct {
	ID             int32
	Radius         float32 // Base radius in yards
	RadiusPerLevel float32 // Radius increase per level
	RadiusMin      float32 // Minimum radius in yards
	RadiusMax      float32 // Maximum radius in yards
}

// SpellRadii is a lookup table for spell radii by ID.
var SpellRadii = map[int32]SpellRadius{
{{- range .}}
	{{.ID}}: {ID: {{.ID}}, Radius: {{.Radius}}, RadiusPerLevel: {{.RadiusPerLevel}}, RadiusMin: {{.RadiusMin}}, RadiusMax: {{.RadiusMax}}},
{{- end}}
}

// GetSpellRadius returns the SpellRadius for the given ID.
// Returns zero value if not found.
func GetSpellRadius(id int32) SpellRadius {
	return SpellRadii[id]
}
`))

type spellFocusObjectEntry struct {
	ID   int32
	Name string
}

func generateSpellFocusObjects(wc *dbcdb.WoWClient, outputDir string, stdout io.Writer) error {
	focusObjects, err := wc.SpellFocusObject()
	if err != nil {
		return fmt.Errorf("read spell focus objects: %w", err)
	}

	var entries []spellFocusObjectEntry
	err = focusObjects.Range(func(cursor *dbdefs.Ent_SpellFocusObject) bool {
		entries = append(entries, spellFocusObjectEntry{
			ID:   cursor.ID,
			Name: cursor.Name_lang.String(),
		})
		return true
	})
	if err != nil {
		return fmt.Errorf("iterate spell focus objects: %w", err)
	}

	out, cleanup, err := outputWriter(outputDir, "spellfocusobject.go", stdout)
	if err != nil {
		return err
	}
	defer cleanup()

	return spellFocusObjectTemplate.Execute(out, entries)
}

var spellFocusObjectTemplate = template.Must(template.New("spellfocusobject").Parse(`// Code generated by scripts/dbcdata. DO NOT EDIT.

package dbcmem

// SpellFocusObject represents a focus object entry from SpellFocusObject.dbc
// These are world objects (anvils, forges, moonwells, etc.) required to cast certain spells.
type SpellFocusObject struct {
	ID   int32
	Name string
}

// SpellFocusObjects is a lookup table for spell focus objects by ID.
var SpellFocusObjects = map[int32]SpellFocusObject{
{{- range .}}
	{{.ID}}: {ID: {{.ID}}, Name: {{printf "%q" .Name}}},
{{- end}}
}

// GetSpellFocusObject returns the SpellFocusObject for the given ID.
// Returns zero value if not found.
func GetSpellFocusObject(id int32) SpellFocusObject {
	return SpellFocusObjects[id]
}
`))
