package cli

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/Emyrk/chronicle/scripts/dbcdata/dbcdb"
	"github.com/Gophercraft/core/format/dbc/dbdefs"

	"github.com/coder/serpent"
)

func StaticPopulateCmd() *serpent.Command {
	var outputDir string
	var dbcPath string
	return &serpent.Command{
		Use:   "static",
		Short: "Generate static Go code from DBC data.",
		Options: serpent.OptionSet{
			{
				Name:          "output-dir",
				Description:   "Output directory for generated files. Defaults to stdout.",
				Flag:          "output-dir",
				FlagShorthand: "o",
				Value:         serpent.StringOf(&outputDir),
			},
			{
				Name:        "dbc",
				Description: "Path to WoW client directory.",
				Flag:        "dbc",
				Value:       serpent.StringOf(&dbcPath),
				Default:     "/home/steven/Games/turtlewow/drive_c/Program Files (x86)/TurtleWoW",
			},
		},
		Handler: func(inv *serpent.Invocation) error {
			wc, err := dbcdb.New(dbcPath)
			if err != nil {
				return fmt.Errorf("open wow client: %w", err)
			}

			// Generate cast times
			if err := generateCastTimes(wc, outputDir, inv.Stdout); err != nil {
				return fmt.Errorf("generate cast times: %w", err)
			}

			// Generate spell icons
			if err := generateSpellIcons(wc, outputDir, inv.Stdout); err != nil {
				return fmt.Errorf("generate spell icons: %w", err)
			}

			return nil
		},
	}
}

func generateCastTimes(wc *dbcdb.WoWClient, outputDir string, stdout io.Writer) error {
	sct, err := wc.SpellCastTimes()
	if err != nil {
		return fmt.Errorf("read spell cast times: %w", err)
	}

	var entries []dbdefs.Ent_SpellCastTimes
	err = sct.Range(func(cursor *dbdefs.Ent_SpellCastTimes) bool {
		entries = append(entries, *cursor)
		return true
	})
	if err != nil {
		return fmt.Errorf("iterate spell cast times: %w", err)
	}

	out, cleanup, err := outputWriter(outputDir, "casttimes.go", stdout)
	if err != nil {
		return err
	}
	defer cleanup()

	return castTimesTemplate.Execute(out, entries)
}

type spellIconEntry struct {
	ID              int32
	TextureFilename string
}

func generateSpellIcons(wc *dbcdb.WoWClient, outputDir string, stdout io.Writer) error {
	icons, err := wc.SpellIcons()
	if err != nil {
		return fmt.Errorf("read spell icons: %w", err)
	}

	var entries []spellIconEntry
	err = icons.Range(func(cursor *dbdefs.Ent_SpellIcon) bool {
		entries = append(entries, spellIconEntry{
			ID:              cursor.ID,
			TextureFilename: strings.TrimPrefix(cursor.TextureFilename, "Interface\\Icons\\"),
		})
		return true
	})
	if err != nil {
		return fmt.Errorf("iterate spell icons: %w", err)
	}

	out, cleanup, err := outputWriter(outputDir, "spellicons.go", stdout)
	if err != nil {
		return err
	}
	defer cleanup()

	return spellIconsTemplate.Execute(out, entries)
}

// outputWriter returns a writer for the given filename.
// If outputDir is empty, returns stdout.
// The cleanup function must be called to close any opened file.
func outputWriter(outputDir, filename string, stdout io.Writer) (io.Writer, func(), error) {
	if outputDir == "" {
		return stdout, func() {}, nil
	}

	path := filepath.Join(outputDir, filename)
	f, err := os.Create(path)
	if err != nil {
		return nil, nil, fmt.Errorf("create %s: %w", path, err)
	}
	return f, func() { f.Close() }, nil
}

var castTimesTemplate = template.Must(template.New("casttimes").Parse(`// Code generated by scripts/dbcdata. DO NOT EDIT.

package dbcmem

// SpellCastTime represents a cast time entry from SpellCastTimes.dbc
type SpellCastTime struct {
	ID       int32
	Base     int32 // Base cast time in milliseconds
	PerLevel int32 // Cast time reduction per level (negative = faster)
	Minimum  int32 // Minimum cast time in milliseconds
}

// SpellCastTimes is a lookup table for cast times by ID.
var SpellCastTimes = map[int32]SpellCastTime{
{{- range .}}
	{{.ID}}: {ID: {{.ID}}, Base: {{.Base}}, PerLevel: {{.PerLevel}}, Minimum: {{.Minimum}}},
{{- end}}
}

// GetCastTime returns the SpellCastTime for the given ID.
// Returns zero value if not found.
func GetCastTime(id int32) SpellCastTime {
	return SpellCastTimes[id]
}
`))

var spellIconsTemplate = template.Must(template.New("spellicons").Parse(`// Code generated by scripts/dbcdata. DO NOT EDIT.

package dbcmem

// SpellIcon represents an icon entry from SpellIcon.dbc
type SpellIcon struct {
	ID              int32
	TextureFilename string
}

// SpellIcons is a lookup table for spell icons by ID.
var SpellIcons = map[int32]SpellIcon{
{{- range .}}
	{{.ID}}: {ID: {{.ID}}, TextureFilename: {{printf "%q" .TextureFilename}}},
{{- end}}
}

// GetSpellIcon returns the SpellIcon for the given ID.
// Returns zero value if not found.
func GetSpellIcon(id int32) SpellIcon {
	return SpellIcons[id]
}
`))
